$axure.loadCurrentPage({
  "url":"一起约.html",
  "generationDate":new Date(1495872722189.68),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"text_keyword"],
  "page":{
    "packageId":"a32d05f6570c4915b6c94189d267c836",
    "type":"Axure:Page",
    "name":"一起约",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ff0a939e4e0a4ce595f7e417a82c033c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":39},
            "size":{
              "width":530,
              "height":960}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9cbed364508472dac4ddb669b8215d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":39},
                "size":{
                  "width":530,
                  "height":960}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/校园社交/u0.png"}},
{
          "id":"8363aca48b6244b1b79d3880d8f7a07d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":120},
            "size":{
              "width":480,
              "height":794}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef4c60b69bf9496a98d1cb5c22379b1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":120},
                "size":{
                  "width":480,
                  "height":794}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动直播/u2.png"}},
{
          "id":"b76ef2be61864d2d89eb79860719ca31",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":120},
            "size":{
              "width":480,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2150bafaa42c498591c82a960082d585",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":120},
                "size":{
                  "width":480,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动直播/u4.png"}},
{
          "id":"cfaa4c3822e54dc9a60bac156e825064",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":189},
            "size":{
              "width":480,
              "height":107}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7332a62e81a461b8e280969bdef4264",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":189},
                "size":{
                  "width":480,
                  "height":107}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动直播/u6.png"}},
{
          "id":"87cd99629495451793b1593981b4ba5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":423,
              "y":212},
            "size":{
              "width":30,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4251ce24c5704ccd846656d470354b42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":423,
                  "y":212},
                "size":{
                  "width":30,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"52ed3fa727b443838dc0768e23b5e2af",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":423,
              "y":236},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95a796276c5c44aab0e9da0b2a8af82a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":423,
                  "y":236},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"91fd1ecca1bc4b96849ca7702238932e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":296},
            "size":{
              "width":480,
              "height":107}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c635b91ac944610b46b26f139437516",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":296},
                "size":{
                  "width":480,
                  "height":107}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动直播/u6.png"}},
{
          "id":"79b0e04586344797b037e04b4c20acf3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":423,
              "y":316},
            "size":{
              "width":30,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d835e53f7d7432b92afe533e2d50510",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":423,
                  "y":316},
                "size":{
                  "width":30,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6662e51fb63b44b6ab1415c2a7ecca2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":423,
              "y":343},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aad10f9c30874e23b80439f32f34a9ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":423,
                  "y":343},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21b360d443624e6c8efbd4de00a33a9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":403},
            "size":{
              "width":480,
              "height":107}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67114063f9e3450a993bea0c5b60a03a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":403},
                "size":{
                  "width":480,
                  "height":107}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动直播/u6.png"}},
{
          "id":"fba39add9c5d4ca18bcdb40733971189",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":423,
              "y":424},
            "size":{
              "width":30,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"954d10818f504e8ca5b462f7fc656f26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":423,
                  "y":424},
                "size":{
                  "width":30,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ee47c81783d4d6fb45193a4ca6e417c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":423,
              "y":450},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"830dc40defc54f95b71576e45f5847aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":423,
                  "y":450},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ad0f75f11294d6da41c283a262affcd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":510},
            "size":{
              "width":480,
              "height":107}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64b693768db94deb82cd2589a26a65b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":510},
                "size":{
                  "width":480,
                  "height":107}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动直播/u6.png"}},
{
          "id":"dc4be858109049d9b5078fc88045b197",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":423,
              "y":530},
            "size":{
              "width":30,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56df17a7ab34418b9b1578296736b6e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":423,
                  "y":530},
                "size":{
                  "width":30,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d082df11013479fb995a2e997e5df22",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":423,
              "y":558},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45c451b88a5f4094981851174dde63ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":423,
                  "y":558},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"675a2260e2d5440bbe8b968fe264d3dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":618},
            "size":{
              "width":480,
              "height":107}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65169b8184dc431da1ad0cabf8656e71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":618},
                "size":{
                  "width":480,
                  "height":107}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动直播/u6.png"}},
{
          "id":"c2819be228154848ab3a95a576ab7455",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":423,
              "y":636},
            "size":{
              "width":30,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2187116bb534ff48696671f106fb52d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":423,
                  "y":636},
                "size":{
                  "width":30,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2af9014497c45289f4ec4dd12901cd2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":423,
              "y":665},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"091053b1e96b4e4f840dce58d8191364",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":423,
                  "y":665},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea124eecbe1540e9b23a1f6acaeffb63",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":725},
            "size":{
              "width":480,
              "height":107}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ba3c7dd71f74cb6a56813b8c5109159",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":725},
                "size":{
                  "width":480,
                  "height":107}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动直播/u6.png"}},
{
          "id":"eee197652cf14f3c93f50a971ae3bacc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":423,
              "y":741},
            "size":{
              "width":30,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"267d2615eb0a4bb090f0867016e5de36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":423,
                  "y":741},
                "size":{
                  "width":30,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0559526bd578464cba4cef39acbc6a2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":423,
              "y":772},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff64c26d30d6430d9d92fd7dd73585dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":423,
                  "y":772},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"776d3f7fad594e429f8afea97bbc2617",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":832},
            "size":{
              "width":480,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b872b0c5a127465f8607f023bdaf1a40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":832},
                "size":{
                  "width":480,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动直播/u42.png"}},
{
          "id":"6a179d9c135f43de9275703ba0f43d9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":423,
              "y":849},
            "size":{
              "width":30,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1086c6b7505a4b448a1f7fc3fc3f2d0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":423,
                  "y":849},
                "size":{
                  "width":30,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d9930a537b94ed6ad1319f558b28613",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":423,
              "y":879},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3ca4832dbcb483fbd900e8f28e48fb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":423,
                  "y":879},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb34f61ba8ea4c14a8f27a3414862533",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"36px",
            "fontWeight":"500",
            "location":{
              "x":290,
              "y":224},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2221d90841264221ad3489801839058c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"36px",
                "fontWeight":"500",
                "location":{
                  "x":290,
                  "y":224},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"099baf26065347e390b79500e15502cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"36px",
            "fontWeight":"500",
            "location":{
              "x":290,
              "y":330},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fb6c2704da24f1f89acd8dcd5d03346",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"36px",
                "fontWeight":"500",
                "location":{
                  "x":290,
                  "y":330},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9642539f66754f9b9ead3303500223be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"36px",
            "fontWeight":"500",
            "location":{
              "x":290,
              "y":438},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5fa0b1925764a3fb8b0478b79f231a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"36px",
                "fontWeight":"500",
                "location":{
                  "x":290,
                  "y":438},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08be4805643a40f7a76fca11d1814383",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"36px",
            "fontWeight":"500",
            "location":{
              "x":290,
              "y":546},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eeb62fe925be408981bd7075e7eda899",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"36px",
                "fontWeight":"500",
                "location":{
                  "x":290,
                  "y":546},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1510bfb21ae64096b5a8d4572ab4637e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"36px",
            "fontWeight":"500",
            "location":{
              "x":290,
              "y":652},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cee806785a9b40e6b0d9c85b389449b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"36px",
                "fontWeight":"500",
                "location":{
                  "x":290,
                  "y":652},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f031dd9ae071438fa5871a39c97f3edb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"36px",
            "fontWeight":"500",
            "location":{
              "x":290,
              "y":758},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4483e5b6f8c74099adc7b9178865b1e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"36px",
                "fontWeight":"500",
                "location":{
                  "x":290,
                  "y":758},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ad2ede713dd46b6a03a05e3a108cd71",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"36px",
            "fontWeight":"500",
            "location":{
              "x":290,
              "y":853},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"139dd5a9d90a45b3813224ff2b2a4c6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"36px",
                "fontWeight":"500",
                "location":{
                  "x":290,
                  "y":853},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"79e0dc0c968747c49403f0da620e5a61",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":230},
            "size":{
              "width":73,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"908535bc499d4e2fb313e0aa27023299",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":230},
                "size":{
                  "width":73,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b55ed64ff4554a4c88d39077ac233729",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":336},
            "size":{
              "width":73,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"591b39c100de438d8de6db2da11308d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":336},
                "size":{
                  "width":73,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53417d860f134f36a6241a4a48c3e00b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":444},
            "size":{
              "width":73,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1641d35e90354359adfe93c31da62a52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":444},
                "size":{
                  "width":73,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64f221f5de984013b269bf2c18bfd40c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":552},
            "size":{
              "width":73,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9eb6f01e462b4adcb7e60ba074c4e300",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":552},
                "size":{
                  "width":73,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d2bceafc473049ac92ca7ebdd420e525",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":658},
            "size":{
              "width":73,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7550ddf0a0824fb4af955826eea652fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":658},
                "size":{
                  "width":73,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1e8e74dd5514fb5a2ff39322e3c5740",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":764},
            "size":{
              "width":73,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4071399cd52c4045a249a166c3bc2e08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":764},
                "size":{
                  "width":73,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"19ecb4957ed64419b742663913a3eae7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":858},
            "size":{
              "width":49,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b168283f5d594fb294636f9d86de89ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":858},
                "size":{
                  "width":49,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac612515e84a41b186082808c6829dd5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"36px",
            "fontWeight":"500",
            "horizontalAlignment":"center",
            "location":{
              "x":282,
              "y":132},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c1dce9c7215468bbcb5cc3be08015e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"36px",
                "fontWeight":"500",
                "horizontalAlignment":"center",
                "location":{
                  "x":282,
                  "y":132},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "ff0a939e4e0a4ce595f7e417a82c033c":{
      "scriptId":"u0"},
    "d9cbed364508472dac4ddb669b8215d8":{
      "scriptId":"u1"},
    "8363aca48b6244b1b79d3880d8f7a07d":{
      "scriptId":"u2"},
    "ef4c60b69bf9496a98d1cb5c22379b1e":{
      "scriptId":"u3"},
    "b76ef2be61864d2d89eb79860719ca31":{
      "scriptId":"u4"},
    "2150bafaa42c498591c82a960082d585":{
      "scriptId":"u5"},
    "cfaa4c3822e54dc9a60bac156e825064":{
      "scriptId":"u6"},
    "f7332a62e81a461b8e280969bdef4264":{
      "scriptId":"u7"},
    "87cd99629495451793b1593981b4ba5f":{
      "scriptId":"u8"},
    "4251ce24c5704ccd846656d470354b42":{
      "scriptId":"u9"},
    "52ed3fa727b443838dc0768e23b5e2af":{
      "scriptId":"u10"},
    "95a796276c5c44aab0e9da0b2a8af82a":{
      "scriptId":"u11"},
    "91fd1ecca1bc4b96849ca7702238932e":{
      "scriptId":"u12"},
    "5c635b91ac944610b46b26f139437516":{
      "scriptId":"u13"},
    "79b0e04586344797b037e04b4c20acf3":{
      "scriptId":"u14"},
    "5d835e53f7d7432b92afe533e2d50510":{
      "scriptId":"u15"},
    "6662e51fb63b44b6ab1415c2a7ecca2c":{
      "scriptId":"u16"},
    "aad10f9c30874e23b80439f32f34a9ea":{
      "scriptId":"u17"},
    "21b360d443624e6c8efbd4de00a33a9e":{
      "scriptId":"u18"},
    "67114063f9e3450a993bea0c5b60a03a":{
      "scriptId":"u19"},
    "fba39add9c5d4ca18bcdb40733971189":{
      "scriptId":"u20"},
    "954d10818f504e8ca5b462f7fc656f26":{
      "scriptId":"u21"},
    "8ee47c81783d4d6fb45193a4ca6e417c":{
      "scriptId":"u22"},
    "830dc40defc54f95b71576e45f5847aa":{
      "scriptId":"u23"},
    "6ad0f75f11294d6da41c283a262affcd":{
      "scriptId":"u24"},
    "64b693768db94deb82cd2589a26a65b5":{
      "scriptId":"u25"},
    "dc4be858109049d9b5078fc88045b197":{
      "scriptId":"u26"},
    "56df17a7ab34418b9b1578296736b6e6":{
      "scriptId":"u27"},
    "4d082df11013479fb995a2e997e5df22":{
      "scriptId":"u28"},
    "45c451b88a5f4094981851174dde63ed":{
      "scriptId":"u29"},
    "675a2260e2d5440bbe8b968fe264d3dc":{
      "scriptId":"u30"},
    "65169b8184dc431da1ad0cabf8656e71":{
      "scriptId":"u31"},
    "c2819be228154848ab3a95a576ab7455":{
      "scriptId":"u32"},
    "a2187116bb534ff48696671f106fb52d":{
      "scriptId":"u33"},
    "b2af9014497c45289f4ec4dd12901cd2":{
      "scriptId":"u34"},
    "091053b1e96b4e4f840dce58d8191364":{
      "scriptId":"u35"},
    "ea124eecbe1540e9b23a1f6acaeffb63":{
      "scriptId":"u36"},
    "9ba3c7dd71f74cb6a56813b8c5109159":{
      "scriptId":"u37"},
    "eee197652cf14f3c93f50a971ae3bacc":{
      "scriptId":"u38"},
    "267d2615eb0a4bb090f0867016e5de36":{
      "scriptId":"u39"},
    "0559526bd578464cba4cef39acbc6a2e":{
      "scriptId":"u40"},
    "ff64c26d30d6430d9d92fd7dd73585dc":{
      "scriptId":"u41"},
    "776d3f7fad594e429f8afea97bbc2617":{
      "scriptId":"u42"},
    "b872b0c5a127465f8607f023bdaf1a40":{
      "scriptId":"u43"},
    "6a179d9c135f43de9275703ba0f43d9b":{
      "scriptId":"u44"},
    "1086c6b7505a4b448a1f7fc3fc3f2d0a":{
      "scriptId":"u45"},
    "8d9930a537b94ed6ad1319f558b28613":{
      "scriptId":"u46"},
    "d3ca4832dbcb483fbd900e8f28e48fb4":{
      "scriptId":"u47"},
    "eb34f61ba8ea4c14a8f27a3414862533":{
      "scriptId":"u48"},
    "2221d90841264221ad3489801839058c":{
      "scriptId":"u49"},
    "099baf26065347e390b79500e15502cc":{
      "scriptId":"u50"},
    "9fb6c2704da24f1f89acd8dcd5d03346":{
      "scriptId":"u51"},
    "9642539f66754f9b9ead3303500223be":{
      "scriptId":"u52"},
    "e5fa0b1925764a3fb8b0478b79f231a9":{
      "scriptId":"u53"},
    "08be4805643a40f7a76fca11d1814383":{
      "scriptId":"u54"},
    "eeb62fe925be408981bd7075e7eda899":{
      "scriptId":"u55"},
    "1510bfb21ae64096b5a8d4572ab4637e":{
      "scriptId":"u56"},
    "cee806785a9b40e6b0d9c85b389449b2":{
      "scriptId":"u57"},
    "f031dd9ae071438fa5871a39c97f3edb":{
      "scriptId":"u58"},
    "4483e5b6f8c74099adc7b9178865b1e1":{
      "scriptId":"u59"},
    "6ad2ede713dd46b6a03a05e3a108cd71":{
      "scriptId":"u60"},
    "139dd5a9d90a45b3813224ff2b2a4c6f":{
      "scriptId":"u61"},
    "79e0dc0c968747c49403f0da620e5a61":{
      "scriptId":"u62"},
    "908535bc499d4e2fb313e0aa27023299":{
      "scriptId":"u63"},
    "b55ed64ff4554a4c88d39077ac233729":{
      "scriptId":"u64"},
    "591b39c100de438d8de6db2da11308d6":{
      "scriptId":"u65"},
    "53417d860f134f36a6241a4a48c3e00b":{
      "scriptId":"u66"},
    "1641d35e90354359adfe93c31da62a52":{
      "scriptId":"u67"},
    "64f221f5de984013b269bf2c18bfd40c":{
      "scriptId":"u68"},
    "9eb6f01e462b4adcb7e60ba074c4e300":{
      "scriptId":"u69"},
    "d2bceafc473049ac92ca7ebdd420e525":{
      "scriptId":"u70"},
    "7550ddf0a0824fb4af955826eea652fa":{
      "scriptId":"u71"},
    "c1e8e74dd5514fb5a2ff39322e3c5740":{
      "scriptId":"u72"},
    "4071399cd52c4045a249a166c3bc2e08":{
      "scriptId":"u73"},
    "19ecb4957ed64419b742663913a3eae7":{
      "scriptId":"u74"},
    "b168283f5d594fb294636f9d86de89ea":{
      "scriptId":"u75"},
    "ac612515e84a41b186082808c6829dd5":{
      "scriptId":"u76"},
    "1c1dce9c7215468bbcb5cc3be08015e2":{
      "scriptId":"u77"}}});