$axure.loadCurrentPage({
  "url":"校园社交.html",
  "generationDate":new Date(1495872721862.89),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"text_keyword"],
  "page":{
    "packageId":"f7ac144114f245eba849d4b1d2ba0059",
    "type":"Axure:Page",
    "name":"校园社交",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fc840b45645c485a9982d985bcb37f30",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":10},
            "size":{
              "width":530,
              "height":960}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b942aed6f04f479c87d3b4c604cb440e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":10},
                "size":{
                  "width":530,
                  "height":960}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/校园社交/u0.png"}},
{
          "id":"7e413ee92d2e48fd984c1db5c3b9ed5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":76},
            "size":{
              "width":480,
              "height":800}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"778b191ee4b64f358a096a62649cafa3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":76},
                "size":{
                  "width":480,
                  "height":800}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/附近/u0.png"}},
{
          "id":"56c6e68297264feb9ff140309809f25e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":790},
            "size":{
              "width":480,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12c84a2f40c24b1e876ae31634d5c069",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":790},
                "size":{
                  "width":480,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/校园社交/u4.png"}},
{
          "id":"5241f413552245ec888975c1942205b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":165},
            "size":{
              "width":480,
              "height":216}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5253b438ea4b494089c8a4f0580d0824",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":165},
                "size":{
                  "width":480,
                  "height":216}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/校园社交/u6.png"}},
{
          "id":"0407c0e4d4f94767a09946fd4e98dbc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":165},
            "size":{
              "width":230,
              "height":108}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6847c2e298f7450091c606f506923880",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":165},
                "size":{
                  "width":230,
                  "height":108}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/校园社交/u8.png"}},
{
          "id":"3d75a77da33d4df5a30a5567fb46c251",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":165},
            "size":{
              "width":250,
              "height":108}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d0f54c0adf24a6498a10b90bce19994",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":165},
                "size":{
                  "width":250,
                  "height":108}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/校园社交/u10.png"}},
{
          "id":"78a8040d925e4f7a99a5d0fae4933414",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":273},
            "size":{
              "width":230,
              "height":108}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca29e996d27f4942ac14a6f17efa94f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":273},
                "size":{
                  "width":230,
                  "height":108}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/校园社交/u8.png"}},
{
          "id":"ef551736d9204b81ace2178c8fc1f0ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":273},
            "size":{
              "width":250,
              "height":108}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e5b483cdd5f473ab1f77a2cd0e48c29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":273},
                "size":{
                  "width":250,
                  "height":108}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/校园社交/u10.png"}},
{
          "id":"440bd9d03e324e968059e1953bd43a8a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":277,
              "y":403},
            "size":{
              "width":76,
              "height":70},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cbbf2de74b145398603d0988b68ce1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":277,
                  "y":403},
                "size":{
                  "width":76,
                  "height":70},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/校园社交/u16.png"}},
{
          "id":"182521f9a0f6432cb6bd51703c3051ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":365,
              "y":403},
            "size":{
              "width":30,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58b72591111d4b6895400fde23a2649f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":365,
                  "y":403},
                "size":{
                  "width":30,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"17e9830081d14e6084aeb87f2a54580b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":365,
              "y":450},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40042b04795e4ea2b501297f30355e1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":365,
                  "y":450},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35c8320e123341dd9a03c7f8f8f40854",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":298,
              "y":520},
            "size":{
              "width":394,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e85391d437a049f5824af40a1676208c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":298,
                  "y":520},
                "size":{
                  "width":394,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a864fe241f1d4d01879485aaacfd9286",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":296,
              "y":554},
            "size":{
              "width":396,
              "height":185}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85ac42e250a24183abe1cc2e6c4d6b00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":296,
                  "y":554},
                "size":{
                  "width":396,
                  "height":185}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/校园社交/u24.png"}},
{
          "id":"f952fa9e8cef42b7994b63b25a572b51",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"36px",
            "fontWeight":"500",
            "location":{
              "x":568,
              "y":742},
            "size":{
              "width":35,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53c6e9b56052469b8a8ab8a32a3a18b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"36px",
                "fontWeight":"500",
                "location":{
                  "x":568,
                  "y":742},
                "size":{
                  "width":35,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f04bae8404344bb4b796004de93ff707",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"36px",
            "fontWeight":"500",
            "location":{
              "x":622,
              "y":741},
            "size":{
              "width":38,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae19ebf7b9784a51bac75d9490faf2d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"36px",
                "fontWeight":"500",
                "location":{
                  "x":622,
                  "y":741},
                "size":{
                  "width":38,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ac762e88a3540e4a2a836b3c887bcd8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":277,
              "y":798},
            "size":{
              "width":76,
              "height":70},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eec4f77e6f184c6ca4a7d258bfd9dbb9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":277,
                  "y":798},
                "size":{
                  "width":76,
                  "height":70},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/校园社交/u16.png"}},
{
          "id":"53afa04ce51b4f399892f8603db0f8da",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":365,
              "y":798},
            "size":{
              "width":30,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e48d738ec3a473aa5149432d952a0a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":365,
                  "y":798},
                "size":{
                  "width":30,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aace9161ca8d4f3a89efbd24cd72b1a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":365,
              "y":845},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e14327c82eb14c128a4673749927920e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":365,
                  "y":845},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"760f3e2c971949acad293b73dbb00ff0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":76},
            "size":{
              "width":480,
              "height":89}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89324ef9b41c4dd6893e7a604c72b15d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":76},
                "size":{
                  "width":480,
                  "height":89}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/校园社交/u36.png"}},
{
          "id":"465d67d66a42462b88c09b3870e0b493",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":102},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c27915489fed44dc93468681471a87ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":102},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26ae1b09427f4671a27c6ac0fe91a218",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"36px",
            "fontWeight":"500",
            "horizontalAlignment":"center",
            "location":{
              "x":277,
              "y":97},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7afa2999da214e6aa3ee4411909425c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"36px",
                "fontWeight":"500",
                "horizontalAlignment":"center",
                "location":{
                  "x":277,
                  "y":97},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1da62fe5142d48c59c952e14e3971e2d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":20},
            "size":{
              "width":530,
              "height":960}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f4b341dea0b4d9faedac2b33869b869",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":238,
                  "y":20},
                "size":{
                  "width":530,
                  "height":960}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/校园社交/u0.png"}},
{
          "id":"182f2dcceab64ce9810d44fd19aaf87f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":86},
            "size":{
              "width":480,
              "height":800}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"977dac108b74408cae5c08bd33af5eaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":86},
                "size":{
                  "width":480,
                  "height":800}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/附近/u0.png"}},
{
          "id":"a1cc432413454122986b2a6175d54522",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":800},
            "size":{
              "width":480,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aaa4bd02d8814e28820683684326b454",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":800},
                "size":{
                  "width":480,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/校园社交/u4.png"}},
{
          "id":"7bf4b68e1de84a85b214b0354cc6e7ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":175},
            "size":{
              "width":480,
              "height":216}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43554775deff43a9b08fb138b78971d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":175},
                "size":{
                  "width":480,
                  "height":216}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/校园社交/u6.png"}},
{
          "id":"e022e626863d4ffa88ebba646d4efc9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":175},
            "size":{
              "width":230,
              "height":108}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c348938619ec4befb022916aacb9c478",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":175},
                "size":{
                  "width":230,
                  "height":108}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/校园社交/u8.png"}},
{
          "id":"60ea23e8314c46c3bfcb993fa200b266",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":175},
            "size":{
              "width":250,
              "height":108}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c721d7d74ee94160896eccc4d74645aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":175},
                "size":{
                  "width":250,
                  "height":108}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/校园社交/u10.png"}},
{
          "id":"016bf1ac96da43fc80aebb4bb15400df",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":283},
            "size":{
              "width":230,
              "height":108}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce48a3cfa4d642bb8be72dbb1202445d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":283},
                "size":{
                  "width":230,
                  "height":108}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/校园社交/u8.png"}},
{
          "id":"faf7456a556f458cbcd7969797c64554",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":283},
            "size":{
              "width":250,
              "height":108}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bd256ca6e1140cbb7706b0c8a2efc46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":283},
                "size":{
                  "width":250,
                  "height":108}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/校园社交/u10.png"}},
{
          "id":"5a65fd9b79a64a0093f4e8436cce9918",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":287,
              "y":413},
            "size":{
              "width":76,
              "height":70},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"656cf7b7246a4ac99f9b68098a6df4ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":287,
                  "y":413},
                "size":{
                  "width":76,
                  "height":70},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/校园社交/u16.png"}},
{
          "id":"a6a18c127e5c45fc840f217ce387485b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":375,
              "y":413},
            "size":{
              "width":30,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8d060f445f848b4810285272bb8aa0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":375,
                  "y":413},
                "size":{
                  "width":30,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"09663ce2770c449b9413cdb48a2e516a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":375,
              "y":460},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6bbbdffdaa04efc92f8af6264d20a30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":375,
                  "y":460},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61e9a32a45314b42b8080bebed8acf4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":530},
            "size":{
              "width":394,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e6536a2e565471a83d56e9ea6f29811",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":308,
                  "y":530},
                "size":{
                  "width":394,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7100fd8e8241410eb2a8de26d74d951b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":306,
              "y":564},
            "size":{
              "width":396,
              "height":185}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac9cc609b18945de9127e8a41e1ab8bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":306,
                  "y":564},
                "size":{
                  "width":396,
                  "height":185}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/校园社交/u24.png"}},
{
          "id":"7395584e57bc4b3e8cbc04f1067d795a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"36px",
            "fontWeight":"500",
            "location":{
              "x":578,
              "y":752},
            "size":{
              "width":35,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f7ccd1643d342e088625d25f38712b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"36px",
                "fontWeight":"500",
                "location":{
                  "x":578,
                  "y":752},
                "size":{
                  "width":35,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec292460fb304e01a17f306fc0ae8786",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"36px",
            "fontWeight":"500",
            "location":{
              "x":632,
              "y":751},
            "size":{
              "width":38,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a3ce3c4473e4f97a564671c9bb3c027",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"36px",
                "fontWeight":"500",
                "location":{
                  "x":632,
                  "y":751},
                "size":{
                  "width":38,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd7632a165d940219be99a1fee824f05",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":287,
              "y":808},
            "size":{
              "width":76,
              "height":70},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe5e43868df5422a9361bf3b4d0f5297",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":287,
                  "y":808},
                "size":{
                  "width":76,
                  "height":70},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/校园社交/u16.png"}},
{
          "id":"577700e02de84dd88fc03bf936fb0176",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":375,
              "y":808},
            "size":{
              "width":30,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ae2d3ddc72b4edb872fe75c1940c26c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":375,
                  "y":808},
                "size":{
                  "width":30,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7bb52956e8b145f682b7d3f91e97e924",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":375,
              "y":855},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"456078d28b10405fafc222fa1c69bf04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":375,
                  "y":855},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aad2964ed7c14a69ac11843b93037779",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":86},
            "size":{
              "width":480,
              "height":89}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcc09e6e41ac426185edba82b55a61b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":86},
                "size":{
                  "width":480,
                  "height":89}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/校园社交/u36.png"}},
{
          "id":"2d02f4eb75a547bea14c6e677833a4ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":112},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"731c92a293a24d26bffd5ef80bbae22c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":112},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27f281a31af345acb1f23b8670b4636a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"36px",
            "fontWeight":"500",
            "horizontalAlignment":"center",
            "location":{
              "x":287,
              "y":107},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e6970a274c8474ea2907a569bf5f1e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"36px",
                "fontWeight":"500",
                "horizontalAlignment":"center",
                "location":{
                  "x":287,
                  "y":107},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "fc840b45645c485a9982d985bcb37f30":{
      "scriptId":"u0"},
    "b942aed6f04f479c87d3b4c604cb440e":{
      "scriptId":"u1"},
    "7e413ee92d2e48fd984c1db5c3b9ed5f":{
      "scriptId":"u2"},
    "778b191ee4b64f358a096a62649cafa3":{
      "scriptId":"u3"},
    "56c6e68297264feb9ff140309809f25e":{
      "scriptId":"u4"},
    "12c84a2f40c24b1e876ae31634d5c069":{
      "scriptId":"u5"},
    "5241f413552245ec888975c1942205b9":{
      "scriptId":"u6"},
    "5253b438ea4b494089c8a4f0580d0824":{
      "scriptId":"u7"},
    "0407c0e4d4f94767a09946fd4e98dbc8":{
      "scriptId":"u8"},
    "6847c2e298f7450091c606f506923880":{
      "scriptId":"u9"},
    "3d75a77da33d4df5a30a5567fb46c251":{
      "scriptId":"u10"},
    "5d0f54c0adf24a6498a10b90bce19994":{
      "scriptId":"u11"},
    "78a8040d925e4f7a99a5d0fae4933414":{
      "scriptId":"u12"},
    "ca29e996d27f4942ac14a6f17efa94f9":{
      "scriptId":"u13"},
    "ef551736d9204b81ace2178c8fc1f0ec":{
      "scriptId":"u14"},
    "4e5b483cdd5f473ab1f77a2cd0e48c29":{
      "scriptId":"u15"},
    "440bd9d03e324e968059e1953bd43a8a":{
      "scriptId":"u16"},
    "4cbbf2de74b145398603d0988b68ce1b":{
      "scriptId":"u17"},
    "182521f9a0f6432cb6bd51703c3051ef":{
      "scriptId":"u18"},
    "58b72591111d4b6895400fde23a2649f":{
      "scriptId":"u19"},
    "17e9830081d14e6084aeb87f2a54580b":{
      "scriptId":"u20"},
    "40042b04795e4ea2b501297f30355e1e":{
      "scriptId":"u21"},
    "35c8320e123341dd9a03c7f8f8f40854":{
      "scriptId":"u22"},
    "e85391d437a049f5824af40a1676208c":{
      "scriptId":"u23"},
    "a864fe241f1d4d01879485aaacfd9286":{
      "scriptId":"u24"},
    "85ac42e250a24183abe1cc2e6c4d6b00":{
      "scriptId":"u25"},
    "f952fa9e8cef42b7994b63b25a572b51":{
      "scriptId":"u26"},
    "53c6e9b56052469b8a8ab8a32a3a18b4":{
      "scriptId":"u27"},
    "f04bae8404344bb4b796004de93ff707":{
      "scriptId":"u28"},
    "ae19ebf7b9784a51bac75d9490faf2d5":{
      "scriptId":"u29"},
    "3ac762e88a3540e4a2a836b3c887bcd8":{
      "scriptId":"u30"},
    "eec4f77e6f184c6ca4a7d258bfd9dbb9":{
      "scriptId":"u31"},
    "53afa04ce51b4f399892f8603db0f8da":{
      "scriptId":"u32"},
    "0e48d738ec3a473aa5149432d952a0a7":{
      "scriptId":"u33"},
    "aace9161ca8d4f3a89efbd24cd72b1a1":{
      "scriptId":"u34"},
    "e14327c82eb14c128a4673749927920e":{
      "scriptId":"u35"},
    "760f3e2c971949acad293b73dbb00ff0":{
      "scriptId":"u36"},
    "89324ef9b41c4dd6893e7a604c72b15d":{
      "scriptId":"u37"},
    "465d67d66a42462b88c09b3870e0b493":{
      "scriptId":"u38"},
    "c27915489fed44dc93468681471a87ff":{
      "scriptId":"u39"},
    "26ae1b09427f4671a27c6ac0fe91a218":{
      "scriptId":"u40"},
    "7afa2999da214e6aa3ee4411909425c7":{
      "scriptId":"u41"},
    "1da62fe5142d48c59c952e14e3971e2d":{
      "scriptId":"u42"},
    "6f4b341dea0b4d9faedac2b33869b869":{
      "scriptId":"u43"},
    "182f2dcceab64ce9810d44fd19aaf87f":{
      "scriptId":"u44"},
    "977dac108b74408cae5c08bd33af5eaf":{
      "scriptId":"u45"},
    "a1cc432413454122986b2a6175d54522":{
      "scriptId":"u46"},
    "aaa4bd02d8814e28820683684326b454":{
      "scriptId":"u47"},
    "7bf4b68e1de84a85b214b0354cc6e7ba":{
      "scriptId":"u48"},
    "43554775deff43a9b08fb138b78971d6":{
      "scriptId":"u49"},
    "e022e626863d4ffa88ebba646d4efc9b":{
      "scriptId":"u50"},
    "c348938619ec4befb022916aacb9c478":{
      "scriptId":"u51"},
    "60ea23e8314c46c3bfcb993fa200b266":{
      "scriptId":"u52"},
    "c721d7d74ee94160896eccc4d74645aa":{
      "scriptId":"u53"},
    "016bf1ac96da43fc80aebb4bb15400df":{
      "scriptId":"u54"},
    "ce48a3cfa4d642bb8be72dbb1202445d":{
      "scriptId":"u55"},
    "faf7456a556f458cbcd7969797c64554":{
      "scriptId":"u56"},
    "5bd256ca6e1140cbb7706b0c8a2efc46":{
      "scriptId":"u57"},
    "5a65fd9b79a64a0093f4e8436cce9918":{
      "scriptId":"u58"},
    "656cf7b7246a4ac99f9b68098a6df4ea":{
      "scriptId":"u59"},
    "a6a18c127e5c45fc840f217ce387485b":{
      "scriptId":"u60"},
    "f8d060f445f848b4810285272bb8aa0e":{
      "scriptId":"u61"},
    "09663ce2770c449b9413cdb48a2e516a":{
      "scriptId":"u62"},
    "a6bbbdffdaa04efc92f8af6264d20a30":{
      "scriptId":"u63"},
    "61e9a32a45314b42b8080bebed8acf4d":{
      "scriptId":"u64"},
    "7e6536a2e565471a83d56e9ea6f29811":{
      "scriptId":"u65"},
    "7100fd8e8241410eb2a8de26d74d951b":{
      "scriptId":"u66"},
    "ac9cc609b18945de9127e8a41e1ab8bb":{
      "scriptId":"u67"},
    "7395584e57bc4b3e8cbc04f1067d795a":{
      "scriptId":"u68"},
    "5f7ccd1643d342e088625d25f38712b4":{
      "scriptId":"u69"},
    "ec292460fb304e01a17f306fc0ae8786":{
      "scriptId":"u70"},
    "4a3ce3c4473e4f97a564671c9bb3c027":{
      "scriptId":"u71"},
    "fd7632a165d940219be99a1fee824f05":{
      "scriptId":"u72"},
    "fe5e43868df5422a9361bf3b4d0f5297":{
      "scriptId":"u73"},
    "577700e02de84dd88fc03bf936fb0176":{
      "scriptId":"u74"},
    "9ae2d3ddc72b4edb872fe75c1940c26c":{
      "scriptId":"u75"},
    "7bb52956e8b145f682b7d3f91e97e924":{
      "scriptId":"u76"},
    "456078d28b10405fafc222fa1c69bf04":{
      "scriptId":"u77"},
    "aad2964ed7c14a69ac11843b93037779":{
      "scriptId":"u78"},
    "bcc09e6e41ac426185edba82b55a61b6":{
      "scriptId":"u79"},
    "2d02f4eb75a547bea14c6e677833a4ea":{
      "scriptId":"u80"},
    "731c92a293a24d26bffd5ef80bbae22c":{
      "scriptId":"u81"},
    "27f281a31af345acb1f23b8670b4636a":{
      "scriptId":"u82"},
    "7e6970a274c8474ea2907a569bf5f1e8":{
      "scriptId":"u83"}}});