$axure.loadCurrentPage({
  "url":"通知讲座.html",
  "generationDate":new Date(1495872723665.3),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"text_keyword"],
  "page":{
    "packageId":"06702001b12b4fbea62522bf837b4718",
    "type":"Axure:Page",
    "name":"通知讲座",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5df304494fa34aec8fbe45d975febb94",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":380,
              "height":800},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76d9c067c4e645e29aa40a536ca8f80a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":380,
                  "height":800},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u0.png"}},
{
          "id":"b7c55f2f1c1447ce9499ff55e5b948d1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":115},
            "size":{
              "width":322,
              "height":55},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3071ba7c5236423fb5675d94ed96444e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":31,
                  "y":115},
                "size":{
                  "width":322,
                  "height":55},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u2.png"}},
{
          "id":"ce7d9816beb94c52a9938535b54ee36d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":117},
            "size":{
              "width":320,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab9a22dd679c4949b56a97e5a607d791",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":117},
                "size":{
                  "width":320,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u18.png"}},
{
          "id":"a956cc0ef9b845e48105d3a3522604be",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"21px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":148,
              "y":137},
            "size":{
              "width":84,
              "height":26},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7bff3fffe8b4bc59412a1c8e3b1bbdc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"21px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":148,
                  "y":137},
                "size":{
                  "width":84,
                  "height":26},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d64872a2e9284db19ca748406c1fc1e6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":138},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"151e3614af3443b8875bac739177d5c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":138},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Back in Current Window",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/自助打印/u8.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "5df304494fa34aec8fbe45d975febb94":{
      "scriptId":"u0"},
    "76d9c067c4e645e29aa40a536ca8f80a":{
      "scriptId":"u1"},
    "b7c55f2f1c1447ce9499ff55e5b948d1":{
      "scriptId":"u2"},
    "3071ba7c5236423fb5675d94ed96444e":{
      "scriptId":"u3"},
    "ce7d9816beb94c52a9938535b54ee36d":{
      "scriptId":"u4"},
    "ab9a22dd679c4949b56a97e5a607d791":{
      "scriptId":"u5"},
    "a956cc0ef9b845e48105d3a3522604be":{
      "scriptId":"u6"},
    "d7bff3fffe8b4bc59412a1c8e3b1bbdc":{
      "scriptId":"u7"},
    "d64872a2e9284db19ca748406c1fc1e6":{
      "scriptId":"u8"},
    "151e3614af3443b8875bac739177d5c6":{
      "scriptId":"u9"}}});