$axure.loadCurrentPage({
  "url":"用户信息.html",
  "generationDate":new Date(1495872723735.51),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"text_keyword"],
  "page":{
    "packageId":"f653b7f0eedd40d592280db450a64880",
    "type":"Axure:Page",
    "name":"用户信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8273ab0b41d840dcb8336199db2a1b9a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":380,
              "height":800},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7f8ae8f34604a01ab0d0ea55ba0811a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":380,
                  "height":800},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u0.png"}},
{
          "id":"bbfd11f8673b4eb9ac083caf13a86058",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":115},
            "size":{
              "width":322,
              "height":55},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"726dc1838d4c45b4bfeff5601b565fbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":31,
                  "y":115},
                "size":{
                  "width":322,
                  "height":55},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u2.png"}},
{
          "id":"81ebf4d17ae4448da1a5b46652644144",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"21px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":150,
              "y":137},
            "size":{
              "width":84,
              "height":26},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14de8a9303924b7bb0e78aef8a6c5100",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"21px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":150,
                  "y":137},
                "size":{
                  "width":84,
                  "height":26},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"46f397755d5543c0b5ad973602f2a386",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":117},
            "size":{
              "width":320,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01d012a426014d5ea6ed0e5ce298b67b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":117},
                "size":{
                  "width":320,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u18.png"}},
{
          "id":"69367083ccbb481e98a2f039c7dac0ac",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":138},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfc47c9a99874c21bc4ea6d3ae4a4e2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":138},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Back in Current Window",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/自助打印/u8.png"}},
{
          "id":"619131f5c825445a9e66e3a67477042e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":190},
            "size":{
              "width":320,
              "height":280},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e2eea997431459a9692b80cf48b3611",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":190},
                "size":{
                  "width":320,
                  "height":280},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户信息/u10.png"}},
{
          "id":"fa11b0f8bee841548ce5de93c9f70541",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":262},
            "size":{
              "width":309,
              "height":1},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5150edf1b3d24da58c6be4a11bd43ff8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":262},
                "size":{
                  "width":309,
                  "height":1},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u36.png"}},
{
          "id":"95b25a55cf394e94b7fe00a77f3d9ed6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":310},
            "size":{
              "width":309,
              "height":1},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fddb079caaa4fd9910f9100339fb3e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":310},
                "size":{
                  "width":309,
                  "height":1},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u36.png"}},
{
          "id":"2fde39ebca0646639bc8add593b25474",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":350},
            "size":{
              "width":309,
              "height":1},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81a527d1d023479eb5cfa6b5551ef622",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":350},
                "size":{
                  "width":309,
                  "height":1},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u36.png"}},
{
          "id":"b0812b75edf7400693ff36e83df7c9e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":391},
            "size":{
              "width":309,
              "height":1},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76d4a9447c9740898469c63f5adaa375",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":391},
                "size":{
                  "width":309,
                  "height":1},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u36.png"}},
{
          "id":"81bc01e4bd7a47cbaa858ce0f257ed9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":430},
            "size":{
              "width":309,
              "height":1},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"591e73f9fef541b18e4d7dece497da20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":430},
                "size":{
                  "width":309,
                  "height":1},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u36.png"}},
{
          "id":"50491347145c46efb0bdf28a21dc019c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":49,
              "y":217},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3033775fea546cbb6a76a94edb4e415",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":49,
                  "y":217},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e9b2651ed91848a7bbb3d90e14df837e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":258,
              "y":196},
            "size":{
              "width":58,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4d8146cba3741dfb20b75613966e378",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":258,
                  "y":196},
                "size":{
                  "width":58,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u22.png"}},
{
          "id":"2fbe647a3fe245189ba09e67f9e99b93",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":319,
              "y":214},
            "size":{
              "width":28,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54aabb6e3f0e48fe94dcfdcb716558d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":319,
                  "y":214},
                "size":{
                  "width":28,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u30.png"}},
{
          "id":"5e6ec2ae26c24d569ed822d3106e1320",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":49,
              "y":276},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"478e3053ca814a1693585f13a238a9d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":49,
                  "y":276},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f38d183db2fa469d8c3626087993f436",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":258,
              "y":276},
            "size":{
              "width":62,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e3e8ac4e09549d7aa41019012895b37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":258,
                  "y":276},
                "size":{
                  "width":62,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"441000906c9d46c097685ea385397c0e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":322,
              "y":276},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7b55c270eac4240a3c7047c14f25f3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":322,
                  "y":276},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u34.png"}},
{
          "id":"665cf0f7b43f4673a1d52537da2f89ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":49,
              "y":321},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"562ac35d45344b7bbb10428b4fea463d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":49,
                  "y":321},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29ea3fed715a413b864240c225f5581c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":258,
              "y":321},
            "size":{
              "width":62,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd4be56469644910bd13ea61863bca91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":258,
                  "y":321},
                "size":{
                  "width":62,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0039d68113394a5db3ec783e4a8fa145",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":49,
              "y":361},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b50b5cfe243d4f6cac050e578971b565",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":49,
                  "y":361},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b7ac0cebbc6426382229456698b120b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":294,
              "y":361},
            "size":{
              "width":22,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcc9b73759ce41bd8ac521c96fd33dba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":294,
                  "y":361},
                "size":{
                  "width":22,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"abe8599951dc4dc29437ee6e0958fed5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":322,
              "y":361},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1452152240c34760a1e57795ca47442b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":322,
                  "y":361},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u34.png"}},
{
          "id":"232256ad0c6e462a9881c94debf4c3d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":49,
              "y":402},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"451c77422eae4472b6c875ad8ff47887",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":49,
                  "y":402},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"557d8f3ec24c475abb59771d530a272f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":49,
              "y":441},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0fa5059e90846a49ed075c77c3bc561",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":49,
                  "y":441},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e832ccbdbdb84507921181fb831e9fba",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":193,
              "y":401},
            "size":{
              "width":122,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd0f4596de334a41ac0afc989014482f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":193,
                  "y":401},
                "size":{
                  "width":122,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"370d110db5624857a04b05af52f973fd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":322,
              "y":400},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"524814684a8245beab81a150a093be08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":322,
                  "y":400},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u34.png"}},
{
          "id":"3cc3ffeacef84f979ff2e7d547544c19",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":265,
              "y":440},
            "size":{
              "width":54,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0de5dfd5da64e9db064898d7bcd1c9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":265,
                  "y":440},
                "size":{
                  "width":54,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"90d807f2908c4f849f3c965f8f083a58",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":322,
              "y":440},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6dcf1c2fe99d4cab9a867eaae6093428",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":322,
                  "y":440},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u34.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "8273ab0b41d840dcb8336199db2a1b9a":{
      "scriptId":"u0"},
    "a7f8ae8f34604a01ab0d0ea55ba0811a":{
      "scriptId":"u1"},
    "bbfd11f8673b4eb9ac083caf13a86058":{
      "scriptId":"u2"},
    "726dc1838d4c45b4bfeff5601b565fbe":{
      "scriptId":"u3"},
    "81ebf4d17ae4448da1a5b46652644144":{
      "scriptId":"u4"},
    "14de8a9303924b7bb0e78aef8a6c5100":{
      "scriptId":"u5"},
    "46f397755d5543c0b5ad973602f2a386":{
      "scriptId":"u6"},
    "01d012a426014d5ea6ed0e5ce298b67b":{
      "scriptId":"u7"},
    "69367083ccbb481e98a2f039c7dac0ac":{
      "scriptId":"u8"},
    "dfc47c9a99874c21bc4ea6d3ae4a4e2a":{
      "scriptId":"u9"},
    "619131f5c825445a9e66e3a67477042e":{
      "scriptId":"u10"},
    "4e2eea997431459a9692b80cf48b3611":{
      "scriptId":"u11"},
    "fa11b0f8bee841548ce5de93c9f70541":{
      "scriptId":"u12"},
    "5150edf1b3d24da58c6be4a11bd43ff8":{
      "scriptId":"u13"},
    "95b25a55cf394e94b7fe00a77f3d9ed6":{
      "scriptId":"u14"},
    "4fddb079caaa4fd9910f9100339fb3e5":{
      "scriptId":"u15"},
    "2fde39ebca0646639bc8add593b25474":{
      "scriptId":"u16"},
    "81a527d1d023479eb5cfa6b5551ef622":{
      "scriptId":"u17"},
    "b0812b75edf7400693ff36e83df7c9e4":{
      "scriptId":"u18"},
    "76d4a9447c9740898469c63f5adaa375":{
      "scriptId":"u19"},
    "81bc01e4bd7a47cbaa858ce0f257ed9b":{
      "scriptId":"u20"},
    "591e73f9fef541b18e4d7dece497da20":{
      "scriptId":"u21"},
    "50491347145c46efb0bdf28a21dc019c":{
      "scriptId":"u22"},
    "e3033775fea546cbb6a76a94edb4e415":{
      "scriptId":"u23"},
    "e9b2651ed91848a7bbb3d90e14df837e":{
      "scriptId":"u24"},
    "d4d8146cba3741dfb20b75613966e378":{
      "scriptId":"u25"},
    "2fbe647a3fe245189ba09e67f9e99b93":{
      "scriptId":"u26"},
    "54aabb6e3f0e48fe94dcfdcb716558d7":{
      "scriptId":"u27"},
    "5e6ec2ae26c24d569ed822d3106e1320":{
      "scriptId":"u28"},
    "478e3053ca814a1693585f13a238a9d8":{
      "scriptId":"u29"},
    "f38d183db2fa469d8c3626087993f436":{
      "scriptId":"u30"},
    "8e3e8ac4e09549d7aa41019012895b37":{
      "scriptId":"u31"},
    "441000906c9d46c097685ea385397c0e":{
      "scriptId":"u32"},
    "a7b55c270eac4240a3c7047c14f25f3d":{
      "scriptId":"u33"},
    "665cf0f7b43f4673a1d52537da2f89ca":{
      "scriptId":"u34"},
    "562ac35d45344b7bbb10428b4fea463d":{
      "scriptId":"u35"},
    "29ea3fed715a413b864240c225f5581c":{
      "scriptId":"u36"},
    "dd4be56469644910bd13ea61863bca91":{
      "scriptId":"u37"},
    "0039d68113394a5db3ec783e4a8fa145":{
      "scriptId":"u38"},
    "b50b5cfe243d4f6cac050e578971b565":{
      "scriptId":"u39"},
    "4b7ac0cebbc6426382229456698b120b":{
      "scriptId":"u40"},
    "fcc9b73759ce41bd8ac521c96fd33dba":{
      "scriptId":"u41"},
    "abe8599951dc4dc29437ee6e0958fed5":{
      "scriptId":"u42"},
    "1452152240c34760a1e57795ca47442b":{
      "scriptId":"u43"},
    "232256ad0c6e462a9881c94debf4c3d1":{
      "scriptId":"u44"},
    "451c77422eae4472b6c875ad8ff47887":{
      "scriptId":"u45"},
    "557d8f3ec24c475abb59771d530a272f":{
      "scriptId":"u46"},
    "d0fa5059e90846a49ed075c77c3bc561":{
      "scriptId":"u47"},
    "e832ccbdbdb84507921181fb831e9fba":{
      "scriptId":"u48"},
    "cd0f4596de334a41ac0afc989014482f":{
      "scriptId":"u49"},
    "370d110db5624857a04b05af52f973fd":{
      "scriptId":"u50"},
    "524814684a8245beab81a150a093be08":{
      "scriptId":"u51"},
    "3cc3ffeacef84f979ff2e7d547544c19":{
      "scriptId":"u52"},
    "e0de5dfd5da64e9db064898d7bcd1c9c":{
      "scriptId":"u53"},
    "90d807f2908c4f849f3c965f8f083a58":{
      "scriptId":"u54"},
    "6dcf1c2fe99d4cab9a867eaae6093428":{
      "scriptId":"u55"}}});