$axure.loadCurrentPage({
  "url":"办事指南.html",
  "generationDate":new Date(1495872723274.96),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"text_keyword"],
  "page":{
    "packageId":"9b788a8b14a94418ad9435c3c17c4958",
    "type":"Axure:Page",
    "name":"办事指南",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f3eb1197053041f08d948eb7f3e1008b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":380,
              "height":800},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aff21134fa8540dcb76d2fce7088b08a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":380,
                  "height":800},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u0.png"}},
{
          "id":"00d4deafbb6a40e7974261f5163db16a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":115},
            "size":{
              "width":322,
              "height":55},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f93138d4af8a442193d235586bda6600",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":31,
                  "y":115},
                "size":{
                  "width":322,
                  "height":55},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u2.png"}},
{
          "id":"b7528192734b4412923b36a129a29efb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":117},
            "size":{
              "width":320,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3ac0f565d6d4c09b1598fe1dc36be6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":117},
                "size":{
                  "width":320,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u18.png"}},
{
          "id":"8385ac7a4cb443ff885bc209f731cef5",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"21px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":148,
              "y":137},
            "size":{
              "width":84,
              "height":26},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3461e9d5ed3f4b07968361e794d56e0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"21px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":148,
                  "y":137},
                "size":{
                  "width":84,
                  "height":26},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e1932b70e6e64541a7fbdee615fdec7e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":138},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92ae956fca36431489bc8ef2a637afca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":138},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Back in Current Window",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/自助打印/u8.png"}},
{
          "id":"d24ad79d6cb74f579b8456dd4d24d57b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":62,
              "y":182},
            "size":{
              "width":273,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8beb632657e4468b5450512a2dbd5da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":62,
                  "y":182},
                "size":{
                  "width":273,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/办事指南/u10.png"}},
{
          "id":"823a9857450f46da8584ddc43de0d5c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":222},
            "size":{
              "width":27,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf7e4a7212ff431b8894b670d87ce811",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":222},
                "size":{
                  "width":27,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aad33a01f68f4adabcbfc612f08d9e33",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":222},
            "size":{
              "width":27,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02b06f9a833c4945a9b443b7f4d221f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":148,
                  "y":222},
                "size":{
                  "width":27,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b8787d8734e4c4e87d5a556cab92d2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":225,
              "y":222},
            "size":{
              "width":27,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"475be6b7ebb74ef8826365957c0a43f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":225,
                  "y":222},
                "size":{
                  "width":27,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce46cfa5a4214a04932cd90657d19057",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":222},
            "size":{
              "width":39,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c81ac18e48d4026bd7abbc8d6db9dc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":222},
                "size":{
                  "width":39,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eeefe6782685423f9d9246bdf18d029d",
          "label":"学生项",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":248},
            "size":{
              "width":320,
              "height":432}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"5e16201fe87543c68b9920c18f0b233e",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d3195e760c7344148e936b1911b181b5",
                  "label":"",
                  "parentDynamicPanel":"eeefe6782685423f9d9246bdf18d029d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":80,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7d8530834c57419cb35d14de82ee2bb7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeefe6782685423f9d9246bdf18d029d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":80,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/办事指南/u21.png"}},
{
                  "id":"849e75eb070d42ff9650e07ea941823f",
                  "label":"",
                  "parentDynamicPanel":"eeefe6782685423f9d9246bdf18d029d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":80},
                    "size":{
                      "width":80,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"63a2e20820e3493db0b2d6b60efb6b3c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeefe6782685423f9d9246bdf18d029d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":80},
                        "size":{
                          "width":80,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/办事指南/u21.png"}},
{
                  "id":"5832b734b6a8426faa946cb3f1a78127",
                  "label":"",
                  "parentDynamicPanel":"eeefe6782685423f9d9246bdf18d029d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":120,
                      "y":80},
                    "size":{
                      "width":80,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6464b825d28c40d08ad76baf8626339e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeefe6782685423f9d9246bdf18d029d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":120,
                          "y":80},
                        "size":{
                          "width":80,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/办事指南/u21.png"}},
{
                  "id":"788691720a0248c3928cb99b05fd2488",
                  "label":"",
                  "parentDynamicPanel":"eeefe6782685423f9d9246bdf18d029d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":120,
                      "y":20},
                    "size":{
                      "width":80,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fb215b0cff044c2dad3661982bd02e79",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeefe6782685423f9d9246bdf18d029d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":120,
                          "y":20},
                        "size":{
                          "width":80,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/办事指南/u21.png"}},
{
                  "id":"4cd4cd2a5d8441f4b971e8a68a1135e2",
                  "label":"",
                  "parentDynamicPanel":"eeefe6782685423f9d9246bdf18d029d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":220,
                      "y":20},
                    "size":{
                      "width":80,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5d0a1e15162e45a492ad6e3a577fda2e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeefe6782685423f9d9246bdf18d029d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":220,
                          "y":20},
                        "size":{
                          "width":80,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/办事指南/u21.png"}},
{
                  "id":"5820c6636e3240bf8515eeb8e0fdbaef",
                  "label":"",
                  "parentDynamicPanel":"eeefe6782685423f9d9246bdf18d029d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":220,
                      "y":80},
                    "size":{
                      "width":80,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"61f5f5d2bc954285ae200b8a0b380ea7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeefe6782685423f9d9246bdf18d029d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":220,
                          "y":80},
                        "size":{
                          "width":80,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/办事指南/u21.png"}},
{
                  "id":"665d01ec16d6406daef4f9bcd75e88f4",
                  "label":"",
                  "parentDynamicPanel":"eeefe6782685423f9d9246bdf18d029d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":140},
                    "size":{
                      "width":80,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7ab9c6b7703e45c3831bba3feb38b664",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeefe6782685423f9d9246bdf18d029d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":140},
                        "size":{
                          "width":80,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/办事指南/u21.png"}},
{
                  "id":"641815a54f6f42e7b430dddc95db2b73",
                  "label":"",
                  "parentDynamicPanel":"eeefe6782685423f9d9246bdf18d029d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":120,
                      "y":140},
                    "size":{
                      "width":80,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"62e9899f923241c39698773d31ad954c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeefe6782685423f9d9246bdf18d029d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":120,
                          "y":140},
                        "size":{
                          "width":80,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/办事指南/u21.png"}},
{
                  "id":"b549fa1ed67e4f1793d14d9111911b27",
                  "label":"",
                  "parentDynamicPanel":"eeefe6782685423f9d9246bdf18d029d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":220,
                      "y":140},
                    "size":{
                      "width":80,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cd9a290b61a54b17b3d9412c079c9d2f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeefe6782685423f9d9246bdf18d029d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":220,
                          "y":140},
                        "size":{
                          "width":80,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/办事指南/u21.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "f3eb1197053041f08d948eb7f3e1008b":{
      "scriptId":"u0"},
    "aff21134fa8540dcb76d2fce7088b08a":{
      "scriptId":"u1"},
    "00d4deafbb6a40e7974261f5163db16a":{
      "scriptId":"u2"},
    "f93138d4af8a442193d235586bda6600":{
      "scriptId":"u3"},
    "b7528192734b4412923b36a129a29efb":{
      "scriptId":"u4"},
    "f3ac0f565d6d4c09b1598fe1dc36be6c":{
      "scriptId":"u5"},
    "8385ac7a4cb443ff885bc209f731cef5":{
      "scriptId":"u6"},
    "3461e9d5ed3f4b07968361e794d56e0e":{
      "scriptId":"u7"},
    "e1932b70e6e64541a7fbdee615fdec7e":{
      "scriptId":"u8"},
    "92ae956fca36431489bc8ef2a637afca":{
      "scriptId":"u9"},
    "d24ad79d6cb74f579b8456dd4d24d57b":{
      "scriptId":"u10"},
    "a8beb632657e4468b5450512a2dbd5da":{
      "scriptId":"u11"},
    "823a9857450f46da8584ddc43de0d5c2":{
      "scriptId":"u12"},
    "cf7e4a7212ff431b8894b670d87ce811":{
      "scriptId":"u13"},
    "aad33a01f68f4adabcbfc612f08d9e33":{
      "scriptId":"u14"},
    "02b06f9a833c4945a9b443b7f4d221f2":{
      "scriptId":"u15"},
    "0b8787d8734e4c4e87d5a556cab92d2c":{
      "scriptId":"u16"},
    "475be6b7ebb74ef8826365957c0a43f9":{
      "scriptId":"u17"},
    "ce46cfa5a4214a04932cd90657d19057":{
      "scriptId":"u18"},
    "5c81ac18e48d4026bd7abbc8d6db9dc6":{
      "scriptId":"u19"},
    "eeefe6782685423f9d9246bdf18d029d":{
      "scriptId":"u20"},
    "d3195e760c7344148e936b1911b181b5":{
      "scriptId":"u21"},
    "7d8530834c57419cb35d14de82ee2bb7":{
      "scriptId":"u22"},
    "849e75eb070d42ff9650e07ea941823f":{
      "scriptId":"u23"},
    "63a2e20820e3493db0b2d6b60efb6b3c":{
      "scriptId":"u24"},
    "5832b734b6a8426faa946cb3f1a78127":{
      "scriptId":"u25"},
    "6464b825d28c40d08ad76baf8626339e":{
      "scriptId":"u26"},
    "788691720a0248c3928cb99b05fd2488":{
      "scriptId":"u27"},
    "fb215b0cff044c2dad3661982bd02e79":{
      "scriptId":"u28"},
    "4cd4cd2a5d8441f4b971e8a68a1135e2":{
      "scriptId":"u29"},
    "5d0a1e15162e45a492ad6e3a577fda2e":{
      "scriptId":"u30"},
    "5820c6636e3240bf8515eeb8e0fdbaef":{
      "scriptId":"u31"},
    "61f5f5d2bc954285ae200b8a0b380ea7":{
      "scriptId":"u32"},
    "665d01ec16d6406daef4f9bcd75e88f4":{
      "scriptId":"u33"},
    "7ab9c6b7703e45c3831bba3feb38b664":{
      "scriptId":"u34"},
    "641815a54f6f42e7b430dddc95db2b73":{
      "scriptId":"u35"},
    "62e9899f923241c39698773d31ad954c":{
      "scriptId":"u36"},
    "b549fa1ed67e4f1793d14d9111911b27":{
      "scriptId":"u37"},
    "cd9a290b61a54b17b3d9412c079c9d2f":{
      "scriptId":"u38"}}});