$axure.loadCurrentPage({
  "url":"搜索结果-欢乐谷.html",
  "generationDate":new Date(1495872721000.2),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"text_keyword"],
  "page":{
    "packageId":"1a518ed589744c17acd14ea5ac220e79",
    "type":"Axure:Page",
    "name":"搜索结果-欢乐谷",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"Case 1",
            "isNewIfGroup":false,
            "actions":[]}]}},
    "diagram":{
      "objects":[{
          "id":"bfb7d64ce5444b0799618d15e5e29092",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":50,
              "y":40},
            "size":{
              "width":480,
              "height":800}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"088c33bd110249c2bc018e00d4101536",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":50,
                  "y":40},
                "size":{
                  "width":480,
                  "height":800}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/附近/u0.png"}},
{
          "id":"8d1e3fc1104b49d19bb62ef41d68e7df",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":40},
            "size":{
              "width":480,
              "height":690}},
          "adaptiveStyles":{
}},
{
          "id":"017d516e373949d581021f0e7c8dc3d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":82,
              "y":53},
            "size":{
              "width":432,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"200dee8233794212b1662052c4bb89c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":82,
                  "y":53},
                "size":{
                  "width":432,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索结果-欢乐谷/u3.png"}},
{
          "id":"e7356dbaa5e64c0b9e65dfb0bb086071",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":93,
              "y":57},
            "size":{
              "width":41,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b1d94351e41479b8910c2723c6fa905",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":93,
                  "y":57},
                "size":{
                  "width":41,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 搜索 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"搜索.html",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"setFunction",
                      "description":"Set value of text_keyword equal to &quot;&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"text_keyword"},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/附近/u3.png"}},
{
          "id":"e2e260554ac84d419e811f5c388b2c3c",
          "label":"search_content",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":144,
              "y":68},
            "size":{
              "width":61,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a51d7e49bb80468f86b6388c5ec8573d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":144,
                  "y":68},
                "size":{
                  "width":61,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"91d7d498cb3642788753a956c80e6f1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":658,
              "y":67},
            "size":{
              "width":661,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7e30afb22df4e73b9f79cdbbb535235",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":658,
                  "y":67},
                "size":{
                  "width":661,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ae0c03c0a16406a8ba4698fca8fa6d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":50,
              "y":724},
            "size":{
              "width":480,
              "height":116}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7385aad3fd194c84acff05381f601af8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":50,
                  "y":724},
                "size":{
                  "width":480,
                  "height":116}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索结果-欢乐谷/u11.png"}},
{
          "id":"9483f173fe6d4386b5a5fceefe75e286",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":67,
              "y":741},
            "size":{
              "width":101,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3710285b074c403298ad54bd60c82383",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":67,
                  "y":741},
                "size":{
                  "width":101,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"033012362c1f40f9a54c9c3367c028ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":70,
              "y":803},
            "size":{
              "width":156,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca585686b1434b1cb8e333da73edd041",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":70,
                  "y":803},
                "size":{
                  "width":156,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98474e3d94b94a8081e4e08d87220b85",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":691},
            "size":{
              "width":57,
              "height":59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f82a8d5d1a9c42758f2a0ee7b5bb5b6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":691},
                "size":{
                  "width":57,
                  "height":59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索结果-欢乐谷/u17.png"}},
{
          "id":"2ef11c72e2ed4c26a8c561c851cae1a9",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":411,
              "y":780},
            "size":{
              "width":105,
              "height":38}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 导航 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"导航.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"6399e8b083964989bb3d67c02c65a1a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":70,
              "y":777},
            "size":{
              "width":247,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28763462c071410fb781f909a44ea7f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":70,
                  "y":777},
                "size":{
                  "width":247,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "bfb7d64ce5444b0799618d15e5e29092":{
      "scriptId":"u0"},
    "088c33bd110249c2bc018e00d4101536":{
      "scriptId":"u1"},
    "8d1e3fc1104b49d19bb62ef41d68e7df":{
      "scriptId":"u2"},
    "017d516e373949d581021f0e7c8dc3d5":{
      "scriptId":"u3"},
    "200dee8233794212b1662052c4bb89c8":{
      "scriptId":"u4"},
    "e7356dbaa5e64c0b9e65dfb0bb086071":{
      "scriptId":"u5"},
    "9b1d94351e41479b8910c2723c6fa905":{
      "scriptId":"u6"},
    "e2e260554ac84d419e811f5c388b2c3c":{
      "scriptId":"u7"},
    "a51d7e49bb80468f86b6388c5ec8573d":{
      "scriptId":"u8"},
    "91d7d498cb3642788753a956c80e6f1a":{
      "scriptId":"u9"},
    "c7e30afb22df4e73b9f79cdbbb535235":{
      "scriptId":"u10"},
    "7ae0c03c0a16406a8ba4698fca8fa6d1":{
      "scriptId":"u11"},
    "7385aad3fd194c84acff05381f601af8":{
      "scriptId":"u12"},
    "9483f173fe6d4386b5a5fceefe75e286":{
      "scriptId":"u13"},
    "3710285b074c403298ad54bd60c82383":{
      "scriptId":"u14"},
    "033012362c1f40f9a54c9c3367c028ff":{
      "scriptId":"u15"},
    "ca585686b1434b1cb8e333da73edd041":{
      "scriptId":"u16"},
    "98474e3d94b94a8081e4e08d87220b85":{
      "scriptId":"u17"},
    "f82a8d5d1a9c42758f2a0ee7b5bb5b6a":{
      "scriptId":"u18"},
    "2ef11c72e2ed4c26a8c561c851cae1a9":{
      "scriptId":"u19"},
    "6399e8b083964989bb3d67c02c65a1a3":{
      "scriptId":"u20"},
    "28763462c071410fb781f909a44ea7f7":{
      "scriptId":"u21"}}});