$axure.loadCurrentPage({
  "url":"自助打印.html",
  "generationDate":new Date(1495872723217.81),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"text_keyword"],
  "page":{
    "packageId":"504cc196cd964cb0a09892c51c4b317d",
    "type":"Axure:Page",
    "name":"自助打印",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0044672d1abb40ca89a5489c8633d31a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":380,
              "height":800},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34843bb36aa54f5fab0901d6d39cd84f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":380,
                  "height":800},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u0.png"}},
{
          "id":"28ad20cf8b7841c192906702d193ae12",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":115},
            "size":{
              "width":322,
              "height":55},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f0a49d72893451fa96d0c9d9c7fe40a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":31,
                  "y":115},
                "size":{
                  "width":322,
                  "height":55},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u2.png"}},
{
          "id":"9b846619ea14445c9c280ecfe6b8963b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":117},
            "size":{
              "width":320,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c31bb6af77eb447e827b641d0bea3478",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":117},
                "size":{
                  "width":320,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u18.png"}},
{
          "id":"aa3e2eb2aef64a41994dd1fbf3fb411e",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"21px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":148,
              "y":137},
            "size":{
              "width":84,
              "height":26},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34ab2d83ecbf4756bb3a23f95c7c3e17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"21px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":148,
                  "y":137},
                "size":{
                  "width":84,
                  "height":26},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4fadf5c0cf774de4801976531346e7b9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":138},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0868a2a83bb942e8aa72c1d8a189a89e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":138},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Back in Current Window",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/自助打印/u8.png"}},
{
          "id":"80e9aa28b43c4a5aa00de7bc013df91a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":240},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4325e0746d50426ba465a49bc456629f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":240},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自助打印/u10.png"}},
{
          "id":"b1737cf3afdd49ffa58583e61ccf95ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":310},
            "size":{
              "width":39,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89b00e5f73dd48818145a174c36c8e77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":310},
                "size":{
                  "width":39,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9bbcb0267ade41e98238b6f1fab0a13b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":162,
              "y":240},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"347dc9548ec043189516b77e73e28411",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":162,
                  "y":240},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自助打印/u10.png"}},
{
          "id":"93c38f065bfb48278cf7c0f6bba3fe95",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":172,
              "y":310},
            "size":{
              "width":39,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccc5e289918e4e4c85651b93eb548457",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":172,
                  "y":310},
                "size":{
                  "width":39,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28b87f53924d4925a6b769c2c5e16931",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":240},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e31c7faeb544881bcd313dfc4f40165",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":240},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自助打印/u10.png"}},
{
          "id":"6f69beb14a6f403884257d70deca96cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":264,
              "y":310},
            "size":{
              "width":52,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7796ed9bba8c486491229fc920d350e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":264,
                  "y":310},
                "size":{
                  "width":52,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c375cbe644754dcf89740ed71aac2505",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":382},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6735536cdbb74705850a4b60dae57b8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":382},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自助打印/u10.png"}},
{
          "id":"702702a4892b42f6a0396e96f97cac39",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":64,
              "y":452},
            "size":{
              "width":52,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"887051993f2a47d3adcb3f53c772839c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":64,
                  "y":452},
                "size":{
                  "width":52,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a6e1172c78a4d67822bc23fc05a0195",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":162,
              "y":382},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d3c5096a00e45778d7e422334e79953",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":162,
                  "y":382},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自助打印/u10.png"}},
{
          "id":"8607fad3c4724dd6ae550c4d96a21f7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":178,
              "y":452},
            "size":{
              "width":27,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da90e9854699471d8eed806a97eae93f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":178,
                  "y":452},
                "size":{
                  "width":27,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "0044672d1abb40ca89a5489c8633d31a":{
      "scriptId":"u0"},
    "34843bb36aa54f5fab0901d6d39cd84f":{
      "scriptId":"u1"},
    "28ad20cf8b7841c192906702d193ae12":{
      "scriptId":"u2"},
    "9f0a49d72893451fa96d0c9d9c7fe40a":{
      "scriptId":"u3"},
    "9b846619ea14445c9c280ecfe6b8963b":{
      "scriptId":"u4"},
    "c31bb6af77eb447e827b641d0bea3478":{
      "scriptId":"u5"},
    "aa3e2eb2aef64a41994dd1fbf3fb411e":{
      "scriptId":"u6"},
    "34ab2d83ecbf4756bb3a23f95c7c3e17":{
      "scriptId":"u7"},
    "4fadf5c0cf774de4801976531346e7b9":{
      "scriptId":"u8"},
    "0868a2a83bb942e8aa72c1d8a189a89e":{
      "scriptId":"u9"},
    "80e9aa28b43c4a5aa00de7bc013df91a":{
      "scriptId":"u10"},
    "4325e0746d50426ba465a49bc456629f":{
      "scriptId":"u11"},
    "b1737cf3afdd49ffa58583e61ccf95ba":{
      "scriptId":"u12"},
    "89b00e5f73dd48818145a174c36c8e77":{
      "scriptId":"u13"},
    "9bbcb0267ade41e98238b6f1fab0a13b":{
      "scriptId":"u14"},
    "347dc9548ec043189516b77e73e28411":{
      "scriptId":"u15"},
    "93c38f065bfb48278cf7c0f6bba3fe95":{
      "scriptId":"u16"},
    "ccc5e289918e4e4c85651b93eb548457":{
      "scriptId":"u17"},
    "28b87f53924d4925a6b769c2c5e16931":{
      "scriptId":"u18"},
    "5e31c7faeb544881bcd313dfc4f40165":{
      "scriptId":"u19"},
    "6f69beb14a6f403884257d70deca96cd":{
      "scriptId":"u20"},
    "7796ed9bba8c486491229fc920d350e1":{
      "scriptId":"u21"},
    "c375cbe644754dcf89740ed71aac2505":{
      "scriptId":"u22"},
    "6735536cdbb74705850a4b60dae57b8f":{
      "scriptId":"u23"},
    "702702a4892b42f6a0396e96f97cac39":{
      "scriptId":"u24"},
    "887051993f2a47d3adcb3f53c772839c":{
      "scriptId":"u25"},
    "5a6e1172c78a4d67822bc23fc05a0195":{
      "scriptId":"u26"},
    "9d3c5096a00e45778d7e422334e79953":{
      "scriptId":"u27"},
    "8607fad3c4724dd6ae550c4d96a21f7a":{
      "scriptId":"u28"},
    "da90e9854699471d8eed806a97eae93f":{
      "scriptId":"u29"}}});