$axure.loadCurrentPage({
  "url":"智能推送.html",
  "generationDate":new Date(1495872724357.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"text_keyword"],
  "page":{
    "packageId":"e6b3f7b4956f4679b5d064a5ec7bf908",
    "type":"Axure:Page",
    "name":"智能推送",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"298e9ada6cbf4ce4ac304ab7ce87b7b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":20},
            "size":{
              "width":760,
              "height":440}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e120966d513b4493bfcedc80f976e685",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":20},
                "size":{
                  "width":760,
                  "height":440}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/后台/u0.png"}},
{
          "id":"34c657d9530d45aa9a314b189ef96aa5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF363636},
            "location":{
              "x":210,
              "y":80},
            "size":{
              "width":210,
              "height":380}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18bd8b83309d4c62b9730e7b8606c017",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF363636},
                "location":{
                  "x":210,
                  "y":80},
                "size":{
                  "width":210,
                  "height":380}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/后台/u2.png"}},
{
          "id":"f4c8fd281dc14a4b897a2a278a1176b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":264,
              "y":121},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d700aa29bc4e47edbb71d82347e7be11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":264,
                  "y":121},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/后台/u8.png"}},
{
          "id":"94638e7987a94d94aae4106e42a9fb3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":264,
              "y":181},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8209ab11154c4afb99d136c5c7ef9a94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":264,
                  "y":181},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/后台/u8.png"}},
{
          "id":"72c4ecde882b495c8aa9a3fb64e18865",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":264,
              "y":241},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7eb9b6a0543b44c2afe5cfbde65d6351",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":264,
                  "y":241},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/后台/u8.png"}},
{
          "id":"1ad57a51b5fa4f67aa60bd9346f8cdab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "location":{
              "x":264,
              "y":301},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"842f20b98c2f43ce8fc3161eef3f0547",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":264,
                  "y":301},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/后台/u6.png"}},
{
          "id":"a57ceb12decd4410a9c5853f10a71efa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":420,
              "y":80},
            "size":{
              "width":550,
              "height":380},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71753aadff434c1ca9bea0af46ed5bb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":420,
                  "y":80},
                "size":{
                  "width":550,
                  "height":380},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u12.png"}},
{
          "id":"a3d59c9316ed4b72ac551ad204897e77",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":430,
              "y":92},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7eacc763f58045d4aa1b20ddd2ab6cc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":430,
                  "y":92},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4598ef20bb7b4e37ad34f0a6ea20f8bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":121},
            "size":{
              "width":90,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5449131c6adf49819d08de467462b7bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":121},
                "size":{
                  "width":90,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u24.png"}},
{
          "id":"8e5e2fac8a2e4df1b4f12672c53bb6dc",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":530,
              "y":121},
            "size":{
              "width":320,
              "height":39}},
          "adaptiveStyles":{
}},
{
          "id":"63f9df58c4474b97b5ede7569ffa7b08",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":860,
              "y":126},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"107390c7cfbf40fb96dcc1d1e78a0081",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":860,
                  "y":126},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/后台/u8.png"}},
{
          "id":"780dce68b2a844aca148bb03d7eff54c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":176},
            "size":{
              "width":90,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6224a1e963f44ac99599a08304e4fe29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":176},
                "size":{
                  "width":90,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u24.png"}},
{
          "id":"845a5e286255440ea291cf914563dd62",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":530,
              "y":186},
            "size":{
              "width":81,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed6cfa80c769435880156b2bc96aef6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":530,
                  "y":186},
                "size":{
                  "width":81,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a2ecac9295924802ad495be69b6ab1c7",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":621,
              "y":186},
            "size":{
              "width":219,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"c8490f7bff834f9fbb3bb2c3ab392af4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":860,
              "y":182},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfa33a1c023e4fd5bd761e93288872c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":860,
                  "y":182},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/后台/u8.png"}},
{
          "id":"c4c6b8cb1e124c86be567df0d9f4d116",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":530,
              "y":228},
            "size":{
              "width":81,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9395078dee26491bb32133ec09dd4a22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":530,
                  "y":228},
                "size":{
                  "width":81,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a850404e5c7d4c66926db3b872c8aa4c",
          "label":"",
          "type":"listBox",
          "styleType":"listBox",
          "visible":true,
          "style":{
            "location":{
              "x":621,
              "y":231},
            "size":{
              "width":219,
              "height":139}},
          "adaptiveStyles":{
}},
{
          "id":"e1f08c94c3bb47d8924d1c38d64bb7ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":380},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9ab2ad00de94f019fe933fa21fc6584",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":670,
                  "y":380},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/后台/u8.png"}},
{
          "id":"54541e54e1414db1844e2ed2e43e3b28",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"26px",
            "location":{
              "x":210,
              "y":20},
            "size":{
              "width":760,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"945883640f314b07892c8e370f2b7071",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"26px",
                "location":{
                  "x":210,
                  "y":20},
                "size":{
                  "width":760,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/后台/u4.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "298e9ada6cbf4ce4ac304ab7ce87b7b8":{
      "scriptId":"u0"},
    "e120966d513b4493bfcedc80f976e685":{
      "scriptId":"u1"},
    "34c657d9530d45aa9a314b189ef96aa5":{
      "scriptId":"u2"},
    "18bd8b83309d4c62b9730e7b8606c017":{
      "scriptId":"u3"},
    "f4c8fd281dc14a4b897a2a278a1176b1":{
      "scriptId":"u4"},
    "d700aa29bc4e47edbb71d82347e7be11":{
      "scriptId":"u5"},
    "94638e7987a94d94aae4106e42a9fb3e":{
      "scriptId":"u6"},
    "8209ab11154c4afb99d136c5c7ef9a94":{
      "scriptId":"u7"},
    "72c4ecde882b495c8aa9a3fb64e18865":{
      "scriptId":"u8"},
    "7eb9b6a0543b44c2afe5cfbde65d6351":{
      "scriptId":"u9"},
    "1ad57a51b5fa4f67aa60bd9346f8cdab":{
      "scriptId":"u10"},
    "842f20b98c2f43ce8fc3161eef3f0547":{
      "scriptId":"u11"},
    "a57ceb12decd4410a9c5853f10a71efa":{
      "scriptId":"u12"},
    "71753aadff434c1ca9bea0af46ed5bb0":{
      "scriptId":"u13"},
    "a3d59c9316ed4b72ac551ad204897e77":{
      "scriptId":"u14"},
    "7eacc763f58045d4aa1b20ddd2ab6cc0":{
      "scriptId":"u15"},
    "4598ef20bb7b4e37ad34f0a6ea20f8bb":{
      "scriptId":"u16"},
    "5449131c6adf49819d08de467462b7bf":{
      "scriptId":"u17"},
    "8e5e2fac8a2e4df1b4f12672c53bb6dc":{
      "scriptId":"u18"},
    "63f9df58c4474b97b5ede7569ffa7b08":{
      "scriptId":"u19"},
    "107390c7cfbf40fb96dcc1d1e78a0081":{
      "scriptId":"u20"},
    "780dce68b2a844aca148bb03d7eff54c":{
      "scriptId":"u21"},
    "6224a1e963f44ac99599a08304e4fe29":{
      "scriptId":"u22"},
    "845a5e286255440ea291cf914563dd62":{
      "scriptId":"u23"},
    "ed6cfa80c769435880156b2bc96aef6d":{
      "scriptId":"u24"},
    "a2ecac9295924802ad495be69b6ab1c7":{
      "scriptId":"u25"},
    "c8490f7bff834f9fbb3bb2c3ab392af4":{
      "scriptId":"u26"},
    "bfa33a1c023e4fd5bd761e93288872c6":{
      "scriptId":"u27"},
    "c4c6b8cb1e124c86be567df0d9f4d116":{
      "scriptId":"u28"},
    "9395078dee26491bb32133ec09dd4a22":{
      "scriptId":"u29"},
    "a850404e5c7d4c66926db3b872c8aa4c":{
      "scriptId":"u30"},
    "e1f08c94c3bb47d8924d1c38d64bb7ae":{
      "scriptId":"u31"},
    "a9ab2ad00de94f019fe933fa21fc6584":{
      "scriptId":"u32"},
    "54541e54e1414db1844e2ed2e43e3b28":{
      "scriptId":"u33"},
    "945883640f314b07892c8e370f2b7071":{
      "scriptId":"u34"}}});