$axure.loadCurrentPage({
  "url":"详细信息.html",
  "generationDate":new Date(1495872722260.86),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"text_keyword"],
  "page":{
    "packageId":"fbd80a1fc2284aa0a944d7db11142877",
    "type":"Axure:Page",
    "name":"详细信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2f54443004674c00ae7b0f84913626f0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":10},
            "size":{
              "width":530,
              "height":960}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"001a0269601e42738034940c684ad969",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":10},
                "size":{
                  "width":530,
                  "height":960}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/校园社交/u0.png"}},
{
          "id":"654ff1b2fe9c415c9c1d813b3ab361e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":89},
            "size":{
              "width":480,
              "height":800}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2698bf7ddd6244918451538debf6ebaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":89},
                "size":{
                  "width":480,
                  "height":800}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/附近/u0.png"}},
{
          "id":"4cc97f09b7b949909d605aa4f682fb82",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":89},
            "size":{
              "width":480,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30e576f18221460b87d19da6396d00f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":89},
                "size":{
                  "width":480,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找老乡/u4.png"}},
{
          "id":"624f27bab9be4921aff4ba254b134133",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":250,
              "y":154},
            "size":{
              "width":480,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7dd6466804064f0683e1492fc7018dad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":250,
                  "y":154},
                "size":{
                  "width":480,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找老乡/u4.png"}},
{
          "id":"5f0b542657c14d77b45b3e84ed414eec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":250,
              "y":219},
            "size":{
              "width":480,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d6c56ac315e40d687ced50f581039c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":250,
                  "y":219},
                "size":{
                  "width":480,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找老乡/u4.png"}},
{
          "id":"8f7448487b5440a4977dd9e5df3ee382",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":250,
              "y":284},
            "size":{
              "width":480,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"956e7817399041eb8393fc018ac73c56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":250,
                  "y":284},
                "size":{
                  "width":480,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找老乡/u4.png"}},
{
          "id":"dd75bd10b488452392625c79c0aa460f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":250,
              "y":348},
            "size":{
              "width":480,
              "height":195}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75518b720d6a42fb871afa365ff0b854",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":250,
                  "y":348},
                "size":{
                  "width":480,
                  "height":195}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详细信息/u12.png"}},
{
          "id":"540abe2c0fc24a1a89db3937fe31e813",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":250,
              "y":543},
            "size":{
              "width":480,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0efad3aa53f546d6a8aafb3b3570ac28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":250,
                  "y":543},
                "size":{
                  "width":480,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找老乡/u4.png"}},
{
          "id":"554f5077f21f4ba4be5b27b26708a0da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"36px",
            "fontWeight":"500",
            "horizontalAlignment":"center",
            "location":{
              "x":240,
              "y":101},
            "size":{
              "width":109,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"747008467e094eab9d81daca6cb1522c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"36px",
                "fontWeight":"500",
                "horizontalAlignment":"center",
                "location":{
                  "x":240,
                  "y":101},
                "size":{
                  "width":109,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "2f54443004674c00ae7b0f84913626f0":{
      "scriptId":"u0"},
    "001a0269601e42738034940c684ad969":{
      "scriptId":"u1"},
    "654ff1b2fe9c415c9c1d813b3ab361e0":{
      "scriptId":"u2"},
    "2698bf7ddd6244918451538debf6ebaf":{
      "scriptId":"u3"},
    "4cc97f09b7b949909d605aa4f682fb82":{
      "scriptId":"u4"},
    "30e576f18221460b87d19da6396d00f4":{
      "scriptId":"u5"},
    "624f27bab9be4921aff4ba254b134133":{
      "scriptId":"u6"},
    "7dd6466804064f0683e1492fc7018dad":{
      "scriptId":"u7"},
    "5f0b542657c14d77b45b3e84ed414eec":{
      "scriptId":"u8"},
    "7d6c56ac315e40d687ced50f581039c1":{
      "scriptId":"u9"},
    "8f7448487b5440a4977dd9e5df3ee382":{
      "scriptId":"u10"},
    "956e7817399041eb8393fc018ac73c56":{
      "scriptId":"u11"},
    "dd75bd10b488452392625c79c0aa460f":{
      "scriptId":"u12"},
    "75518b720d6a42fb871afa365ff0b854":{
      "scriptId":"u13"},
    "540abe2c0fc24a1a89db3937fe31e813":{
      "scriptId":"u14"},
    "0efad3aa53f546d6a8aafb3b3570ac28":{
      "scriptId":"u15"},
    "554f5077f21f4ba4be5b27b26708a0da":{
      "scriptId":"u16"},
    "747008467e094eab9d81daca6cb1522c":{
      "scriptId":"u17"}}});