$axure.loadCurrentPage({
  "url":"活动直播.html",
  "generationDate":new Date(1495872722091.41),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"text_keyword"],
  "page":{
    "packageId":"b8a5524293274a7796e584136451c1e6",
    "type":"Axure:Page",
    "name":"活动直播",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"714a7a59f5a841f4ae2f56ad26899e20",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":39},
            "size":{
              "width":530,
              "height":960}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82ca2badc0d444a5baf77e5f2a2c15e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":39},
                "size":{
                  "width":530,
                  "height":960}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/校园社交/u0.png"}},
{
          "id":"9885391a551b487d821e02991b5f6361",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":120},
            "size":{
              "width":480,
              "height":794}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"617ae2fcf55f426da95f698d5e3d7ba8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":120},
                "size":{
                  "width":480,
                  "height":794}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动直播/u2.png"}},
{
          "id":"8ed8146f68b943168f95769c1d8ee9ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":120},
            "size":{
              "width":480,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b22a0465308410daeb6edca6afbd7cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":120},
                "size":{
                  "width":480,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动直播/u4.png"}},
{
          "id":"54f3709fece74101855394bdb92eaf7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":189},
            "size":{
              "width":480,
              "height":107}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf2b8639b8c94c78adcf33d5d352e41a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":189},
                "size":{
                  "width":480,
                  "height":107}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动直播/u6.png"}},
{
          "id":"49a70042b4c340b693086833d044c285",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":423,
              "y":212},
            "size":{
              "width":30,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7016b257dce4712b25f9e49ab2aa43d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":423,
                  "y":212},
                "size":{
                  "width":30,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"595891cd9c4a48cfaba46bf27140d165",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":423,
              "y":236},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da7940decb4e4c3ca3e1cb8698f09a7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":423,
                  "y":236},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3b359a25017f4a23a48525fb6ffff0d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":296},
            "size":{
              "width":480,
              "height":107}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b17059f22f984b4d84bbd47bab097df6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":296},
                "size":{
                  "width":480,
                  "height":107}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动直播/u6.png"}},
{
          "id":"8eb7ff6c8caf4c62a75557f0564585ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":423,
              "y":316},
            "size":{
              "width":30,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acfe2e089cc94e698cbb798fcd1d21a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":423,
                  "y":316},
                "size":{
                  "width":30,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca13a747c662452c844194a86bd161d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":423,
              "y":343},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adc661e69f854df0a1be4c14fd18f4ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":423,
                  "y":343},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e44dd78d15d4413bb5d754c26981f99e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":403},
            "size":{
              "width":480,
              "height":107}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6f92d9166c646b4b640c0aaa737cc3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":403},
                "size":{
                  "width":480,
                  "height":107}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动直播/u6.png"}},
{
          "id":"43f5edbb24774c73b5d0677c9ed06ef2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":423,
              "y":424},
            "size":{
              "width":30,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6355e8595f6842e1949a883519de833a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":423,
                  "y":424},
                "size":{
                  "width":30,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c662be2e6fd4b39a5641dfb669cb307",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":423,
              "y":450},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0e739c3faf54a929227908b1e464355",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":423,
                  "y":450},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c5db60f463342c08020fb9f4e8be1e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":510},
            "size":{
              "width":480,
              "height":107}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8b54eeb63844a6886064a8f6350c08c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":510},
                "size":{
                  "width":480,
                  "height":107}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动直播/u6.png"}},
{
          "id":"4e8e68d7f0e441e3b6f99a8ddb91b76e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":423,
              "y":530},
            "size":{
              "width":30,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63e202f8996046fc86ac97bd28f30e0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":423,
                  "y":530},
                "size":{
                  "width":30,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a73238024d66461587639ca131548883",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":423,
              "y":558},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b5204a7cc1744e583e15969d98fe072",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":423,
                  "y":558},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9afa4ec539d546b58ff6d49a33dffd0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":618},
            "size":{
              "width":480,
              "height":107}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6dc5107a60f84dd2a0d5975be48997a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":618},
                "size":{
                  "width":480,
                  "height":107}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动直播/u6.png"}},
{
          "id":"96fa662a37fb4385baf28ad4e9bd2eb0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":423,
              "y":636},
            "size":{
              "width":30,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f4549d599274fe4b201a4c426152cf0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":423,
                  "y":636},
                "size":{
                  "width":30,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf0a78c4aafc4a18bcc0922abd360047",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":423,
              "y":665},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22ca10f23fd54120852c3a37eee6ac51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":423,
                  "y":665},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bdf236f8401b49feb3c3da25332a0c24",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":725},
            "size":{
              "width":480,
              "height":107}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56b6688aeddf4470a3a8aa4be89de7d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":725},
                "size":{
                  "width":480,
                  "height":107}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动直播/u6.png"}},
{
          "id":"679f2c7e064c4c2b8cc9761713ff92c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":423,
              "y":741},
            "size":{
              "width":30,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e4ec85c7fff46009a4d03e65b39d8c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":423,
                  "y":741},
                "size":{
                  "width":30,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"612659932e51459c811c5fed4d88aba7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":423,
              "y":772},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"052851394c1c45319f15e4c949199c56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":423,
                  "y":772},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c5f002b3abb4ccb9aab1af312bdbed8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":832},
            "size":{
              "width":480,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c03c5f7566184ce8aa60d13042bd4e77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":832},
                "size":{
                  "width":480,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动直播/u42.png"}},
{
          "id":"9aac5584ac254e768fde8bb1f303594f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":423,
              "y":849},
            "size":{
              "width":30,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b04d5a7360ab4b71acead68d7593b869",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":423,
                  "y":849},
                "size":{
                  "width":30,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4aae1ccc221d4baf82d74f1d5d9fa4fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":423,
              "y":879},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f11ec2af2fc419698e4ee2af882304b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":423,
                  "y":879},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b2d36d02fa1402fb6a1cd5c0290f3e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"36px",
            "fontWeight":"500",
            "location":{
              "x":290,
              "y":224},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"392e2108e73b4599a17482553d6b3000",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"36px",
                "fontWeight":"500",
                "location":{
                  "x":290,
                  "y":224},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6e289ce2ba348858f9a51551a176ff1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"36px",
            "fontWeight":"500",
            "location":{
              "x":290,
              "y":330},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1779fcfade943d7805d2e9e6274556d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"36px",
                "fontWeight":"500",
                "location":{
                  "x":290,
                  "y":330},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"efc05681be97484fbdd84e0144c13b96",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"36px",
            "fontWeight":"500",
            "location":{
              "x":290,
              "y":438},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25efdcc11453453f9689753f82a30491",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"36px",
                "fontWeight":"500",
                "location":{
                  "x":290,
                  "y":438},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f67a993b4eba48798018b0fc31832c0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"36px",
            "fontWeight":"500",
            "location":{
              "x":290,
              "y":546},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64bf02ba766c465a9d03f3b4ca57e18f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"36px",
                "fontWeight":"500",
                "location":{
                  "x":290,
                  "y":546},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"756bf30bab8d458fa0f37391c275b17d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"36px",
            "fontWeight":"500",
            "location":{
              "x":290,
              "y":652},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a5db37653c0469e95d91a0cabce95fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"36px",
                "fontWeight":"500",
                "location":{
                  "x":290,
                  "y":652},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1cdc55093bac4535abe5986cf9aebf72",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"36px",
            "fontWeight":"500",
            "location":{
              "x":290,
              "y":758},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71a1143e59354208a8d62179d8505ea8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"36px",
                "fontWeight":"500",
                "location":{
                  "x":290,
                  "y":758},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"708852a49e4945449073fb7e9eef3394",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"36px",
            "fontWeight":"500",
            "location":{
              "x":290,
              "y":853},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dba18889715c4d7588d4b66f9b37794d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"36px",
                "fontWeight":"500",
                "location":{
                  "x":290,
                  "y":853},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"842679129375418da848ed17300d2542",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":230},
            "size":{
              "width":73,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7371a21d54f64fd29a09e14a39e594ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":230},
                "size":{
                  "width":73,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3b63b651996419cafbf974cc549a77f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":336},
            "size":{
              "width":73,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8f3bbfb5c9b4d378e1a9853dca56ca2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":336},
                "size":{
                  "width":73,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d6f945d141148fa9167c0d843754cae",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":444},
            "size":{
              "width":73,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1af6d989c34b441990ad1d8f6a439fa8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":444},
                "size":{
                  "width":73,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78c0e0da7bc0449b99675783f93dea18",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":552},
            "size":{
              "width":73,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fa1dce778a44ff3851afe2b0c8d7d26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":552},
                "size":{
                  "width":73,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c40c039f487941c0ab095d0a6eb1babe",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":658},
            "size":{
              "width":73,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3884b224eec740509bebf34d85ddf38b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":658},
                "size":{
                  "width":73,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3107fa6c7eac4e889c33fb97c326246a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":764},
            "size":{
              "width":73,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f21634655c14552a7fd68d313416840",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":764},
                "size":{
                  "width":73,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"544b4573f3df4fcea2f2eba1a0925e94",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":858},
            "size":{
              "width":49,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e88461a97c6449bd88330fa043ccc0f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":858},
                "size":{
                  "width":49,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5ca2d4fff134a3dbefcdf02f961e74c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"36px",
            "fontWeight":"500",
            "horizontalAlignment":"center",
            "location":{
              "x":282,
              "y":132},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e7ff7fad7fa4ad5b1408f49d715ccbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"36px",
                "fontWeight":"500",
                "horizontalAlignment":"center",
                "location":{
                  "x":282,
                  "y":132},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "714a7a59f5a841f4ae2f56ad26899e20":{
      "scriptId":"u0"},
    "82ca2badc0d444a5baf77e5f2a2c15e8":{
      "scriptId":"u1"},
    "9885391a551b487d821e02991b5f6361":{
      "scriptId":"u2"},
    "617ae2fcf55f426da95f698d5e3d7ba8":{
      "scriptId":"u3"},
    "8ed8146f68b943168f95769c1d8ee9ab":{
      "scriptId":"u4"},
    "1b22a0465308410daeb6edca6afbd7cc":{
      "scriptId":"u5"},
    "54f3709fece74101855394bdb92eaf7c":{
      "scriptId":"u6"},
    "cf2b8639b8c94c78adcf33d5d352e41a":{
      "scriptId":"u7"},
    "49a70042b4c340b693086833d044c285":{
      "scriptId":"u8"},
    "e7016b257dce4712b25f9e49ab2aa43d":{
      "scriptId":"u9"},
    "595891cd9c4a48cfaba46bf27140d165":{
      "scriptId":"u10"},
    "da7940decb4e4c3ca3e1cb8698f09a7d":{
      "scriptId":"u11"},
    "3b359a25017f4a23a48525fb6ffff0d6":{
      "scriptId":"u12"},
    "b17059f22f984b4d84bbd47bab097df6":{
      "scriptId":"u13"},
    "8eb7ff6c8caf4c62a75557f0564585ef":{
      "scriptId":"u14"},
    "acfe2e089cc94e698cbb798fcd1d21a9":{
      "scriptId":"u15"},
    "ca13a747c662452c844194a86bd161d1":{
      "scriptId":"u16"},
    "adc661e69f854df0a1be4c14fd18f4ce":{
      "scriptId":"u17"},
    "e44dd78d15d4413bb5d754c26981f99e":{
      "scriptId":"u18"},
    "e6f92d9166c646b4b640c0aaa737cc3b":{
      "scriptId":"u19"},
    "43f5edbb24774c73b5d0677c9ed06ef2":{
      "scriptId":"u20"},
    "6355e8595f6842e1949a883519de833a":{
      "scriptId":"u21"},
    "9c662be2e6fd4b39a5641dfb669cb307":{
      "scriptId":"u22"},
    "c0e739c3faf54a929227908b1e464355":{
      "scriptId":"u23"},
    "8c5db60f463342c08020fb9f4e8be1e1":{
      "scriptId":"u24"},
    "a8b54eeb63844a6886064a8f6350c08c":{
      "scriptId":"u25"},
    "4e8e68d7f0e441e3b6f99a8ddb91b76e":{
      "scriptId":"u26"},
    "63e202f8996046fc86ac97bd28f30e0c":{
      "scriptId":"u27"},
    "a73238024d66461587639ca131548883":{
      "scriptId":"u28"},
    "7b5204a7cc1744e583e15969d98fe072":{
      "scriptId":"u29"},
    "9afa4ec539d546b58ff6d49a33dffd0c":{
      "scriptId":"u30"},
    "6dc5107a60f84dd2a0d5975be48997a0":{
      "scriptId":"u31"},
    "96fa662a37fb4385baf28ad4e9bd2eb0":{
      "scriptId":"u32"},
    "2f4549d599274fe4b201a4c426152cf0":{
      "scriptId":"u33"},
    "cf0a78c4aafc4a18bcc0922abd360047":{
      "scriptId":"u34"},
    "22ca10f23fd54120852c3a37eee6ac51":{
      "scriptId":"u35"},
    "bdf236f8401b49feb3c3da25332a0c24":{
      "scriptId":"u36"},
    "56b6688aeddf4470a3a8aa4be89de7d5":{
      "scriptId":"u37"},
    "679f2c7e064c4c2b8cc9761713ff92c2":{
      "scriptId":"u38"},
    "7e4ec85c7fff46009a4d03e65b39d8c4":{
      "scriptId":"u39"},
    "612659932e51459c811c5fed4d88aba7":{
      "scriptId":"u40"},
    "052851394c1c45319f15e4c949199c56":{
      "scriptId":"u41"},
    "8c5f002b3abb4ccb9aab1af312bdbed8":{
      "scriptId":"u42"},
    "c03c5f7566184ce8aa60d13042bd4e77":{
      "scriptId":"u43"},
    "9aac5584ac254e768fde8bb1f303594f":{
      "scriptId":"u44"},
    "b04d5a7360ab4b71acead68d7593b869":{
      "scriptId":"u45"},
    "4aae1ccc221d4baf82d74f1d5d9fa4fc":{
      "scriptId":"u46"},
    "6f11ec2af2fc419698e4ee2af882304b":{
      "scriptId":"u47"},
    "1b2d36d02fa1402fb6a1cd5c0290f3e8":{
      "scriptId":"u48"},
    "392e2108e73b4599a17482553d6b3000":{
      "scriptId":"u49"},
    "a6e289ce2ba348858f9a51551a176ff1":{
      "scriptId":"u50"},
    "a1779fcfade943d7805d2e9e6274556d":{
      "scriptId":"u51"},
    "efc05681be97484fbdd84e0144c13b96":{
      "scriptId":"u52"},
    "25efdcc11453453f9689753f82a30491":{
      "scriptId":"u53"},
    "f67a993b4eba48798018b0fc31832c0f":{
      "scriptId":"u54"},
    "64bf02ba766c465a9d03f3b4ca57e18f":{
      "scriptId":"u55"},
    "756bf30bab8d458fa0f37391c275b17d":{
      "scriptId":"u56"},
    "0a5db37653c0469e95d91a0cabce95fd":{
      "scriptId":"u57"},
    "1cdc55093bac4535abe5986cf9aebf72":{
      "scriptId":"u58"},
    "71a1143e59354208a8d62179d8505ea8":{
      "scriptId":"u59"},
    "708852a49e4945449073fb7e9eef3394":{
      "scriptId":"u60"},
    "dba18889715c4d7588d4b66f9b37794d":{
      "scriptId":"u61"},
    "842679129375418da848ed17300d2542":{
      "scriptId":"u62"},
    "7371a21d54f64fd29a09e14a39e594ec":{
      "scriptId":"u63"},
    "e3b63b651996419cafbf974cc549a77f":{
      "scriptId":"u64"},
    "b8f3bbfb5c9b4d378e1a9853dca56ca2":{
      "scriptId":"u65"},
    "1d6f945d141148fa9167c0d843754cae":{
      "scriptId":"u66"},
    "1af6d989c34b441990ad1d8f6a439fa8":{
      "scriptId":"u67"},
    "78c0e0da7bc0449b99675783f93dea18":{
      "scriptId":"u68"},
    "0fa1dce778a44ff3851afe2b0c8d7d26":{
      "scriptId":"u69"},
    "c40c039f487941c0ab095d0a6eb1babe":{
      "scriptId":"u70"},
    "3884b224eec740509bebf34d85ddf38b":{
      "scriptId":"u71"},
    "3107fa6c7eac4e889c33fb97c326246a":{
      "scriptId":"u72"},
    "0f21634655c14552a7fd68d313416840":{
      "scriptId":"u73"},
    "544b4573f3df4fcea2f2eba1a0925e94":{
      "scriptId":"u74"},
    "e88461a97c6449bd88330fa043ccc0f3":{
      "scriptId":"u75"},
    "e5ca2d4fff134a3dbefcdf02f961e74c":{
      "scriptId":"u76"},
    "1e7ff7fad7fa4ad5b1408f49d715ccbb":{
      "scriptId":"u77"}}});