$axure.loadCurrentPage({
  "url":"事务办理.html",
  "generationDate":new Date(1495872723145.88),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"text_keyword"],
  "page":{
    "packageId":"a0dbec2bf0f8472bbf396e09f41b419e",
    "type":"Axure:Page",
    "name":"事务办理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e0b0d7c815c94aea820b1f8588cb15ac",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":380,
              "height":800},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a78e15f53d84c6982cd8f30251b19e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":380,
                  "height":800},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u0.png"}},
{
          "id":"1a8f7244e8a944d186a728268647bbc3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":115},
            "size":{
              "width":322,
              "height":55},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15ce9aed9a2e43768f7d202920e8c97b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":31,
                  "y":115},
                "size":{
                  "width":322,
                  "height":55},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u2.png"}},
{
          "id":"7b4c2b98aa2444fcb1d1b1a3ab9120a2",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"21px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":145,
              "y":137},
            "size":{
              "width":96,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba2484fe2358409ca088a0b99b54ecf0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"21px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":145,
                  "y":137},
                "size":{
                  "width":96,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc15e6cc3ced4c70a39d6c44aeb44d85",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":147},
            "size":{
              "width":30,
              "height":6},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2abe92a18cc14c53b168aeff9d55fcba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":147},
                "size":{
                  "width":30,
                  "height":6},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u6.png"}},
{
          "id":"52f8beecb6f34c13bb2d9993c238361b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":640},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"545ec102c2144c50971af5dbb17fdeeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":640},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u8.png"}},
{
          "id":"2feb0430f94045439601f43c093df0f5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":648},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c67c756c7b074d309328cfa9772b4051",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":648},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u10.png"}},
{
          "id":"ba645c6cc1834144980191774d8fccda",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":648},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c07c616289004e6c825acf2ebe130dbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":648},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u12.png"}},
{
          "id":"6743d4b58d0349c9a8e5cb6a8581ac43",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":648},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1ebe0e53f2049c39b99b7a5a8177ee4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":648},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u14.png"}},
{
          "id":"f5df6fb3f72b4fd3bb65a04ca2e0e029",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":648},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"608f23bac9ff419ab3285d0c1704db80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":648},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u16.png"}},
{
          "id":"00e3901bae594b86aed45549a1b2a3de",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":117},
            "size":{
              "width":320,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bc152c9b01a46be9c160566238016c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":117},
                "size":{
                  "width":320,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u18.png"}},
{
          "id":"9ed0ee183971414883f620f1260f721f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":189},
            "size":{
              "width":320,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ba32912de934f0a8c3a74916b6c6b77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":189},
                "size":{
                  "width":320,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u20.png"}},
{
          "id":"ce18e36d92cc42c2b68bacc48e35dc12",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":200},
            "size":{
              "width":58,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fd2bd4c55184e6a94a35053e57fa05d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":200},
                "size":{
                  "width":58,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u22.png"}},
{
          "id":"40dc4070243f43a4a5506db1a19a81cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":116,
              "y":210},
            "size":{
              "width":54,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84e5bc360908408b858bf84c47fe0907",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":116,
                  "y":210},
                "size":{
                  "width":54,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"485cab97b56249e188347e2c848687d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":116,
              "y":233},
            "size":{
              "width":94,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7c1813c9e40469983377af4f2673f73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":116,
                  "y":233},
                "size":{
                  "width":94,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b60c86665af542a8a996706cf1f25124",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":290},
            "size":{
              "width":320,
              "height":230},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6cf1ff5904349b0a61c041355824df1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":290},
                "size":{
                  "width":320,
                  "height":230},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u28.png"}},
{
          "id":"d64d0555b01e4850b0bca9005af73193",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":214},
            "size":{
              "width":28,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e10e365104b4660be9c7311a3f07604",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":214},
                "size":{
                  "width":28,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/事务办理/u30.png"}},
{
          "id":"c2e797e7f00040fcb0c69a76dfc8e9a2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":690,
              "y":221},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53ac0ceb21b54a26b79cb2a1abe393b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":690,
                  "y":221},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u32.png"}},
{
          "id":"14bff00766e3449da776f18acd460b20",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":314,
              "y":297},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65752f233fac4c538580ebfab54b0496",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":314,
                  "y":297},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u34.png"}},
{
          "id":"b51557c316b54a778dee402ace5b1d2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":43,
              "y":325},
            "size":{
              "width":309,
              "height":1},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cf99d56951b4ec2beef9ea70900f4f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":43,
                  "y":325},
                "size":{
                  "width":309,
                  "height":1},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u36.png"}},
{
          "id":"c1a30e8a869144319362a7ed85ef408c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":362},
            "size":{
              "width":310,
              "height":1},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7391d8297bc4e4fa9f7924a9bf1cbd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":362},
                "size":{
                  "width":310,
                  "height":1},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u38.png"}},
{
          "id":"59bc8e583da742e7ac6e24f1e54a99d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":43,
              "y":400},
            "size":{
              "width":309,
              "height":1},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"234f6330aecc4bb39348b7324520a1be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":43,
                  "y":400},
                "size":{
                  "width":309,
                  "height":1},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u36.png"}},
{
          "id":"27ebd5b0fcb54a0399a6665ff41598a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":43,
              "y":440},
            "size":{
              "width":309,
              "height":1},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e453e2bb6ba940f095ea9d7c52bb1ca8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":43,
                  "y":440},
                "size":{
                  "width":309,
                  "height":1},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u36.png"}},
{
          "id":"d8b69483b8014e91955cb5621015a443",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":43,
              "y":479},
            "size":{
              "width":309,
              "height":1},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"975e49975d764d6ea2e3b666cb6a9c5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":43,
                  "y":479},
                "size":{
                  "width":309,
                  "height":1},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u36.png"}},
{
          "id":"b2d0a79451264145ac7f14d651becebb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":87,
              "y":297},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be3a3fbd3957402fbc702ddc53305cdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":87,
                  "y":297},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9993cf2dd4be4bfaa148f3b864f22f99",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":87,
              "y":334},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14c6cf1602584ac0831217336ed448ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":87,
                  "y":334},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df07e63d2ea84a40a01a84e4cf8dfd9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":87,
              "y":372},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb1451390205408a98f830d1ddaf9191",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":87,
                  "y":372},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a4e79fc4190417498eb01e834e0a6a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":87,
              "y":411},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bddf7f225c9f4b2b9ecb37040227dd2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":87,
                  "y":411},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3251078de62943bab4e1947b61a1502f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":87,
              "y":451},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06a185c36ff64ee2a253dc3fc759a5f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":87,
                  "y":451},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b72ffaaa85be4ca6b9670ed1590a7be3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":87,
              "y":489},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db4b1b507aee4cd6a947ad79740bf010",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":87,
                  "y":489},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d10c5cfac76b441cbfc981d26a1903aa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":314,
              "y":334},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f034ee88a7824d60b1f261709bc00293",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":314,
                  "y":334},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u34.png"}},
{
          "id":"19544ceea2b745f5942f02c51b51e75b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":314,
              "y":371},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bae6aa981cf4d4b92b756ac0516bbe2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":314,
                  "y":371},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u34.png"}},
{
          "id":"868c606b676b41558c495079939b2402",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":314,
              "y":410},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6016d85dd2174b5f951378aa265231de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":314,
                  "y":410},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u34.png"}},
{
          "id":"ea84486d071a47dcb19a7c199790575e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":314,
              "y":449},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"959edc1bc7264655afcee84949521557",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":314,
                  "y":449},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u34.png"}},
{
          "id":"f2053ddd4dc64244b72b54d64535314b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":314,
              "y":488},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a261e76c5d284ab7a79cc5b04c311b42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":314,
                  "y":488},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/事务办理/u34.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "e0b0d7c815c94aea820b1f8588cb15ac":{
      "scriptId":"u0"},
    "7a78e15f53d84c6982cd8f30251b19e7":{
      "scriptId":"u1"},
    "1a8f7244e8a944d186a728268647bbc3":{
      "scriptId":"u2"},
    "15ce9aed9a2e43768f7d202920e8c97b":{
      "scriptId":"u3"},
    "7b4c2b98aa2444fcb1d1b1a3ab9120a2":{
      "scriptId":"u4"},
    "ba2484fe2358409ca088a0b99b54ecf0":{
      "scriptId":"u5"},
    "bc15e6cc3ced4c70a39d6c44aeb44d85":{
      "scriptId":"u6"},
    "2abe92a18cc14c53b168aeff9d55fcba":{
      "scriptId":"u7"},
    "52f8beecb6f34c13bb2d9993c238361b":{
      "scriptId":"u8"},
    "545ec102c2144c50971af5dbb17fdeeb":{
      "scriptId":"u9"},
    "2feb0430f94045439601f43c093df0f5":{
      "scriptId":"u10"},
    "c67c756c7b074d309328cfa9772b4051":{
      "scriptId":"u11"},
    "ba645c6cc1834144980191774d8fccda":{
      "scriptId":"u12"},
    "c07c616289004e6c825acf2ebe130dbd":{
      "scriptId":"u13"},
    "6743d4b58d0349c9a8e5cb6a8581ac43":{
      "scriptId":"u14"},
    "f1ebe0e53f2049c39b99b7a5a8177ee4":{
      "scriptId":"u15"},
    "f5df6fb3f72b4fd3bb65a04ca2e0e029":{
      "scriptId":"u16"},
    "608f23bac9ff419ab3285d0c1704db80":{
      "scriptId":"u17"},
    "00e3901bae594b86aed45549a1b2a3de":{
      "scriptId":"u18"},
    "8bc152c9b01a46be9c160566238016c2":{
      "scriptId":"u19"},
    "9ed0ee183971414883f620f1260f721f":{
      "scriptId":"u20"},
    "6ba32912de934f0a8c3a74916b6c6b77":{
      "scriptId":"u21"},
    "ce18e36d92cc42c2b68bacc48e35dc12":{
      "scriptId":"u22"},
    "1fd2bd4c55184e6a94a35053e57fa05d":{
      "scriptId":"u23"},
    "40dc4070243f43a4a5506db1a19a81cd":{
      "scriptId":"u24"},
    "84e5bc360908408b858bf84c47fe0907":{
      "scriptId":"u25"},
    "485cab97b56249e188347e2c848687d7":{
      "scriptId":"u26"},
    "b7c1813c9e40469983377af4f2673f73":{
      "scriptId":"u27"},
    "b60c86665af542a8a996706cf1f25124":{
      "scriptId":"u28"},
    "a6cf1ff5904349b0a61c041355824df1":{
      "scriptId":"u29"},
    "d64d0555b01e4850b0bca9005af73193":{
      "scriptId":"u30"},
    "9e10e365104b4660be9c7311a3f07604":{
      "scriptId":"u31"},
    "c2e797e7f00040fcb0c69a76dfc8e9a2":{
      "scriptId":"u32"},
    "53ac0ceb21b54a26b79cb2a1abe393b7":{
      "scriptId":"u33"},
    "14bff00766e3449da776f18acd460b20":{
      "scriptId":"u34"},
    "65752f233fac4c538580ebfab54b0496":{
      "scriptId":"u35"},
    "b51557c316b54a778dee402ace5b1d2c":{
      "scriptId":"u36"},
    "9cf99d56951b4ec2beef9ea70900f4f8":{
      "scriptId":"u37"},
    "c1a30e8a869144319362a7ed85ef408c":{
      "scriptId":"u38"},
    "b7391d8297bc4e4fa9f7924a9bf1cbd5":{
      "scriptId":"u39"},
    "59bc8e583da742e7ac6e24f1e54a99d9":{
      "scriptId":"u40"},
    "234f6330aecc4bb39348b7324520a1be":{
      "scriptId":"u41"},
    "27ebd5b0fcb54a0399a6665ff41598a9":{
      "scriptId":"u42"},
    "e453e2bb6ba940f095ea9d7c52bb1ca8":{
      "scriptId":"u43"},
    "d8b69483b8014e91955cb5621015a443":{
      "scriptId":"u44"},
    "975e49975d764d6ea2e3b666cb6a9c5f":{
      "scriptId":"u45"},
    "b2d0a79451264145ac7f14d651becebb":{
      "scriptId":"u46"},
    "be3a3fbd3957402fbc702ddc53305cdb":{
      "scriptId":"u47"},
    "9993cf2dd4be4bfaa148f3b864f22f99":{
      "scriptId":"u48"},
    "14c6cf1602584ac0831217336ed448ea":{
      "scriptId":"u49"},
    "df07e63d2ea84a40a01a84e4cf8dfd9a":{
      "scriptId":"u50"},
    "bb1451390205408a98f830d1ddaf9191":{
      "scriptId":"u51"},
    "3a4e79fc4190417498eb01e834e0a6a9":{
      "scriptId":"u52"},
    "bddf7f225c9f4b2b9ecb37040227dd2a":{
      "scriptId":"u53"},
    "3251078de62943bab4e1947b61a1502f":{
      "scriptId":"u54"},
    "06a185c36ff64ee2a253dc3fc759a5f5":{
      "scriptId":"u55"},
    "b72ffaaa85be4ca6b9670ed1590a7be3":{
      "scriptId":"u56"},
    "db4b1b507aee4cd6a947ad79740bf010":{
      "scriptId":"u57"},
    "d10c5cfac76b441cbfc981d26a1903aa":{
      "scriptId":"u58"},
    "f034ee88a7824d60b1f261709bc00293":{
      "scriptId":"u59"},
    "19544ceea2b745f5942f02c51b51e75b":{
      "scriptId":"u60"},
    "4bae6aa981cf4d4b92b756ac0516bbe2":{
      "scriptId":"u61"},
    "868c606b676b41558c495079939b2402":{
      "scriptId":"u62"},
    "6016d85dd2174b5f951378aa265231de":{
      "scriptId":"u63"},
    "ea84486d071a47dcb19a7c199790575e":{
      "scriptId":"u64"},
    "959edc1bc7264655afcee84949521557":{
      "scriptId":"u65"},
    "f2053ddd4dc64244b72b54d64535314b":{
      "scriptId":"u66"},
    "a261e76c5d284ab7a79cc5b04c311b42":{
      "scriptId":"u67"}}});