$axure.loadCurrentPage({
  "url":"附近看看.html",
  "generationDate":new Date(1495872722422.29),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"text_keyword"],
  "page":{
    "packageId":"9736f11ec2c44ce6b80494bad6aea6c0",
    "type":"Axure:Page",
    "name":"附近看看",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ad98b88449db414189e7c1370eb61d28",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":10},
            "size":{
              "width":530,
              "height":960}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3aae9a84f69f4e6a8f0301d98ce12017",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":10},
                "size":{
                  "width":530,
                  "height":960}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/校园社交/u0.png"}},
{
          "id":"8444edacc58e49258554585822aa78b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":251,
              "y":92},
            "size":{
              "width":480,
              "height":800}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6e7865c8c2e4233a0f68357eb2e2c87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":251,
                  "y":92},
                "size":{
                  "width":480,
                  "height":800}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/附近/u0.png"}},
{
          "id":"09e2f49bd0734f0c9f1c8ee6d2e891ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":251,
              "y":92},
            "size":{
              "width":480,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd7e0fcd46c943338b7c5813f3f5275d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":251,
                  "y":92},
                "size":{
                  "width":480,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找老乡/u4.png"}},
{
          "id":"ac2db82dda6f4f338de1781c2b7da0d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":251,
              "y":161},
            "size":{
              "width":480,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1089f4ddde0343de94305888f336164a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":251,
                  "y":161},
                "size":{
                  "width":480,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/附近看看/u6.png"}},
{
          "id":"043d712cd8b74adfaae58f6e3b76f932",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":251,
              "y":243},
            "size":{
              "width":480,
              "height":108}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"826091201790464ba02ecfede8bcda77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":251,
                  "y":243},
                "size":{
                  "width":480,
                  "height":108}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/附近看看/u8.png"}},
{
          "id":"7a46b70aa62c4e07a79e98df32978254",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":265},
            "size":{
              "width":58,
              "height":65},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a480b31810a54fe7a62e2b8abb525d63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":265},
                "size":{
                  "width":58,
                  "height":65},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/附近看看/u10.png"}},
{
          "id":"e0823ff729ce4e139e3bf391bffef685",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":347,
              "y":256},
            "size":{
              "width":30,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"758023c2a330479c8dd91de1c4698dd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":347,
                  "y":256},
                "size":{
                  "width":30,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb6bc6c938e14379b270bb94699d2d1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":347,
              "y":304},
            "size":{
              "width":36,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ddc9ee2d21b438484457d161fbcafa4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":347,
                  "y":304},
                "size":{
                  "width":36,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3eeaa896a17d490eb6c516b83bf44775",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":595,
              "y":243},
            "size":{
              "width":134,
              "height":108}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a96bbf2fafe34fee941f1e3dc4ddef38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":595,
                  "y":243},
                "size":{
                  "width":134,
                  "height":108}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/附近看看/u16.png"}},
{
          "id":"503e12fe725842b18aa1ecaaa0b30644",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":251,
              "y":416},
            "size":{
              "width":480,
              "height":108}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67be3de619f543cca32d725a9648a2d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":251,
                  "y":416},
                "size":{
                  "width":480,
                  "height":108}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/附近看看/u8.png"}},
{
          "id":"32dc82f95af249e98b2105937c699a49",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":444},
            "size":{
              "width":58,
              "height":65},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e44fcd085574183a175846990ff4fea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":444},
                "size":{
                  "width":58,
                  "height":65},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/附近看看/u10.png"}},
{
          "id":"8bac14d52d1247bc98f8df1f82c433c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":347,
              "y":436},
            "size":{
              "width":30,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7a96ad5a09944c0af6d12848d5cfeff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":347,
                  "y":436},
                "size":{
                  "width":30,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9cfb26f767cc466ca9671eb286c446f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":347,
              "y":483},
            "size":{
              "width":36,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"487b1ca2520042cbb7754e4d6cb3757a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":347,
                  "y":483},
                "size":{
                  "width":36,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"348700404edb4378bdb6c14abb236f69",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":435,
              "y":460},
            "size":{
              "width":129,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d656b7a6f9943eb834260820d0cbc2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":435,
                  "y":460},
                "size":{
                  "width":129,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba1d7e6794a441be874d8d01c257f500",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":251,
              "y":524},
            "size":{
              "width":480,
              "height":108}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"508c7cdcb51d47179b7c41f66e43bde9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":251,
                  "y":524},
                "size":{
                  "width":480,
                  "height":108}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/附近看看/u8.png"}},
{
          "id":"b6f1b1c00d10410aaea5d197942b08ca",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":553},
            "size":{
              "width":58,
              "height":65},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac73d0df84ff4624961113167a546873",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":553},
                "size":{
                  "width":58,
                  "height":65},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/附近看看/u10.png"}},
{
          "id":"30e9e2a1dbb046a0980cd927db4d7d70",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":347,
              "y":544},
            "size":{
              "width":30,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6688eca3e1fb4511a73a88f9f7966cd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":347,
                  "y":544},
                "size":{
                  "width":30,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9bedc2f5f814475b8c3d0b9de2aa6f0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":347,
              "y":591},
            "size":{
              "width":36,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f2b90c2ca064e599e857731eabc4647",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":347,
                  "y":591},
                "size":{
                  "width":36,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fa54d3edc3094475a65293437692002d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":435,
              "y":568},
            "size":{
              "width":129,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83afd5c8c1a848d2b0e61ff71aca0334",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":435,
                  "y":568},
                "size":{
                  "width":129,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f57f8d331f8b4544bb40a4c8a94b7d68",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":251,
              "y":633},
            "size":{
              "width":480,
              "height":108}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4057339330f7496da833fda602a87ad0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":251,
                  "y":633},
                "size":{
                  "width":480,
                  "height":108}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/附近看看/u8.png"}},
{
          "id":"454b22f3471240d1b47b0cfe02792e81",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":661},
            "size":{
              "width":58,
              "height":65},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c44294cf25594883a082f9a1c34f3bb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":661},
                "size":{
                  "width":58,
                  "height":65},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/附近看看/u10.png"}},
{
          "id":"5b4b0a90c24e499bb347daa78241a503",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":347,
              "y":652},
            "size":{
              "width":30,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c304f6300f7f435a97b230b6e1af3012",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":347,
                  "y":652},
                "size":{
                  "width":30,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"416d13503b5f4fe2900e8d46b4adbd8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":347,
              "y":700},
            "size":{
              "width":36,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9dbf489de18d44e1922d87421d2052c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":347,
                  "y":700},
                "size":{
                  "width":36,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df80eb68caec4cf69b560bc34ab0585b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":435,
              "y":676},
            "size":{
              "width":129,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f02a70f8bfe34707894825e7835bd110",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":435,
                  "y":676},
                "size":{
                  "width":129,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0e4fef219c043f584628aa39d4b3a7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":251,
              "y":741},
            "size":{
              "width":480,
              "height":108}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3886aaae2bab46d49e1e46faff327f70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":251,
                  "y":741},
                "size":{
                  "width":480,
                  "height":108}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/附近看看/u8.png"}},
{
          "id":"9b133b4b97a64fd2b3fefa29b20b40e9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":769},
            "size":{
              "width":58,
              "height":65},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7eeeeddab2a541efa2cd54bd46028d68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":769},
                "size":{
                  "width":58,
                  "height":65},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/附近看看/u10.png"}},
{
          "id":"7645a96e5ef648e09e86f940c366f0fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":347,
              "y":760},
            "size":{
              "width":30,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21914e088dbf485f9b246099e677fb7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":347,
                  "y":760},
                "size":{
                  "width":30,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fdc8040697634e52b883e833850b6fe7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":347,
              "y":808},
            "size":{
              "width":36,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb7075b6aeba40ffa6f9eb55f27060a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":347,
                  "y":808},
                "size":{
                  "width":36,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9154a259671b475e9d87c5bfddf2d0c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":435,
              "y":784},
            "size":{
              "width":129,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8170b048f6f54e24811b3bba3ae8e5fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":435,
                  "y":784},
                "size":{
                  "width":129,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"713ca1a111c24555a5b44f4729daec0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"36px",
            "fontWeight":"500",
            "horizontalAlignment":"center",
            "location":{
              "x":239,
              "y":104},
            "size":{
              "width":109,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ce0d280ab5d4cdba7c5a818ac9cd92a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"36px",
                "fontWeight":"500",
                "horizontalAlignment":"center",
                "location":{
                  "x":239,
                  "y":104},
                "size":{
                  "width":109,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"90682d8932ad4b14b02e3e7a7916b6c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"36px",
            "fontWeight":"500",
            "location":{
              "x":643,
              "y":277},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92e293fd065c4d83bfccf4d341a79689",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"36px",
                "fontWeight":"500",
                "location":{
                  "x":643,
                  "y":277},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "ad98b88449db414189e7c1370eb61d28":{
      "scriptId":"u0"},
    "3aae9a84f69f4e6a8f0301d98ce12017":{
      "scriptId":"u1"},
    "8444edacc58e49258554585822aa78b7":{
      "scriptId":"u2"},
    "f6e7865c8c2e4233a0f68357eb2e2c87":{
      "scriptId":"u3"},
    "09e2f49bd0734f0c9f1c8ee6d2e891ab":{
      "scriptId":"u4"},
    "cd7e0fcd46c943338b7c5813f3f5275d":{
      "scriptId":"u5"},
    "ac2db82dda6f4f338de1781c2b7da0d0":{
      "scriptId":"u6"},
    "1089f4ddde0343de94305888f336164a":{
      "scriptId":"u7"},
    "043d712cd8b74adfaae58f6e3b76f932":{
      "scriptId":"u8"},
    "826091201790464ba02ecfede8bcda77":{
      "scriptId":"u9"},
    "7a46b70aa62c4e07a79e98df32978254":{
      "scriptId":"u10"},
    "a480b31810a54fe7a62e2b8abb525d63":{
      "scriptId":"u11"},
    "e0823ff729ce4e139e3bf391bffef685":{
      "scriptId":"u12"},
    "758023c2a330479c8dd91de1c4698dd3":{
      "scriptId":"u13"},
    "fb6bc6c938e14379b270bb94699d2d1c":{
      "scriptId":"u14"},
    "2ddc9ee2d21b438484457d161fbcafa4":{
      "scriptId":"u15"},
    "3eeaa896a17d490eb6c516b83bf44775":{
      "scriptId":"u16"},
    "a96bbf2fafe34fee941f1e3dc4ddef38":{
      "scriptId":"u17"},
    "503e12fe725842b18aa1ecaaa0b30644":{
      "scriptId":"u18"},
    "67be3de619f543cca32d725a9648a2d9":{
      "scriptId":"u19"},
    "32dc82f95af249e98b2105937c699a49":{
      "scriptId":"u20"},
    "6e44fcd085574183a175846990ff4fea":{
      "scriptId":"u21"},
    "8bac14d52d1247bc98f8df1f82c433c8":{
      "scriptId":"u22"},
    "f7a96ad5a09944c0af6d12848d5cfeff":{
      "scriptId":"u23"},
    "9cfb26f767cc466ca9671eb286c446f8":{
      "scriptId":"u24"},
    "487b1ca2520042cbb7754e4d6cb3757a":{
      "scriptId":"u25"},
    "348700404edb4378bdb6c14abb236f69":{
      "scriptId":"u26"},
    "3d656b7a6f9943eb834260820d0cbc2a":{
      "scriptId":"u27"},
    "ba1d7e6794a441be874d8d01c257f500":{
      "scriptId":"u28"},
    "508c7cdcb51d47179b7c41f66e43bde9":{
      "scriptId":"u29"},
    "b6f1b1c00d10410aaea5d197942b08ca":{
      "scriptId":"u30"},
    "ac73d0df84ff4624961113167a546873":{
      "scriptId":"u31"},
    "30e9e2a1dbb046a0980cd927db4d7d70":{
      "scriptId":"u32"},
    "6688eca3e1fb4511a73a88f9f7966cd5":{
      "scriptId":"u33"},
    "9bedc2f5f814475b8c3d0b9de2aa6f0a":{
      "scriptId":"u34"},
    "8f2b90c2ca064e599e857731eabc4647":{
      "scriptId":"u35"},
    "fa54d3edc3094475a65293437692002d":{
      "scriptId":"u36"},
    "83afd5c8c1a848d2b0e61ff71aca0334":{
      "scriptId":"u37"},
    "f57f8d331f8b4544bb40a4c8a94b7d68":{
      "scriptId":"u38"},
    "4057339330f7496da833fda602a87ad0":{
      "scriptId":"u39"},
    "454b22f3471240d1b47b0cfe02792e81":{
      "scriptId":"u40"},
    "c44294cf25594883a082f9a1c34f3bb1":{
      "scriptId":"u41"},
    "5b4b0a90c24e499bb347daa78241a503":{
      "scriptId":"u42"},
    "c304f6300f7f435a97b230b6e1af3012":{
      "scriptId":"u43"},
    "416d13503b5f4fe2900e8d46b4adbd8a":{
      "scriptId":"u44"},
    "9dbf489de18d44e1922d87421d2052c3":{
      "scriptId":"u45"},
    "df80eb68caec4cf69b560bc34ab0585b":{
      "scriptId":"u46"},
    "f02a70f8bfe34707894825e7835bd110":{
      "scriptId":"u47"},
    "c0e4fef219c043f584628aa39d4b3a7c":{
      "scriptId":"u48"},
    "3886aaae2bab46d49e1e46faff327f70":{
      "scriptId":"u49"},
    "9b133b4b97a64fd2b3fefa29b20b40e9":{
      "scriptId":"u50"},
    "7eeeeddab2a541efa2cd54bd46028d68":{
      "scriptId":"u51"},
    "7645a96e5ef648e09e86f940c366f0fc":{
      "scriptId":"u52"},
    "21914e088dbf485f9b246099e677fb7a":{
      "scriptId":"u53"},
    "fdc8040697634e52b883e833850b6fe7":{
      "scriptId":"u54"},
    "bb7075b6aeba40ffa6f9eb55f27060a3":{
      "scriptId":"u55"},
    "9154a259671b475e9d87c5bfddf2d0c8":{
      "scriptId":"u56"},
    "8170b048f6f54e24811b3bba3ae8e5fc":{
      "scriptId":"u57"},
    "713ca1a111c24555a5b44f4729daec0f":{
      "scriptId":"u58"},
    "3ce0d280ab5d4cdba7c5a818ac9cd92a":{
      "scriptId":"u59"},
    "90682d8932ad4b14b02e3e7a7916b6c1":{
      "scriptId":"u60"},
    "92e293fd065c4d83bfccf4d341a79689":{
      "scriptId":"u61"}}});