$axure.loadCurrentPage({
  "url":"发布信息.html",
  "generationDate":new Date(1495872722323.03),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"text_keyword"],
  "page":{
    "packageId":"ad0a74ec57e143ed939d340f96db612f",
    "type":"Axure:Page",
    "name":"发布信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b4f28d336b394b3aa25f1495483d9cab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":10},
            "size":{
              "width":530,
              "height":960}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e60910831b924963bf77efbd75dffa43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":10},
                "size":{
                  "width":530,
                  "height":960}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/校园社交/u0.png"}},
{
          "id":"dc297ad50002470094e45386604cd416",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":89},
            "size":{
              "width":480,
              "height":800}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d3fd33c6e2841c8bfbb5187916c19aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":89},
                "size":{
                  "width":480,
                  "height":800}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/附近/u0.png"}},
{
          "id":"e37cc18c9dcb4f97ac86a6c8341391ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":89},
            "size":{
              "width":480,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4198a78d25842748172212e081a1d7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":89},
                "size":{
                  "width":480,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找老乡/u4.png"}},
{
          "id":"4684351f0cbb49dc8768664775506d3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":250,
              "y":154},
            "size":{
              "width":480,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7c255a198df4ceb8bb1ad1abceaa4a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":250,
                  "y":154},
                "size":{
                  "width":480,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找老乡/u4.png"}},
{
          "id":"c05833ebe17541d7806d03f4f485a64e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":250,
              "y":219},
            "size":{
              "width":480,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce16ac65df5641c88eebf47b9de1f699",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":250,
                  "y":219},
                "size":{
                  "width":480,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找老乡/u4.png"}},
{
          "id":"aba3a4a628ee421db4a4acb7c1f893bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":250,
              "y":284},
            "size":{
              "width":480,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5df196a14204168a70d411e9e275434",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":250,
                  "y":284},
                "size":{
                  "width":480,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找老乡/u4.png"}},
{
          "id":"9a08512b6f3245f4ba16658c2eb3141b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":250,
              "y":348},
            "size":{
              "width":480,
              "height":195}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a7cece5c036461caf047a1c12cf113d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":250,
                  "y":348},
                "size":{
                  "width":480,
                  "height":195}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详细信息/u12.png"}},
{
          "id":"8ab7e0b498894f08954c77f9b0c17bd7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":250,
              "y":543},
            "size":{
              "width":480,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5eeed2670c74e1bb998bcf719d861e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":250,
                  "y":543},
                "size":{
                  "width":480,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找老乡/u4.png"}},
{
          "id":"329098c6f4a541f4aa7c259bfed1a1c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"36px",
            "fontWeight":"500",
            "horizontalAlignment":"center",
            "location":{
              "x":240,
              "y":101},
            "size":{
              "width":109,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8f76a7126af43baad4cfad24ace4de6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"36px",
                "fontWeight":"500",
                "horizontalAlignment":"center",
                "location":{
                  "x":240,
                  "y":101},
                "size":{
                  "width":109,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "b4f28d336b394b3aa25f1495483d9cab":{
      "scriptId":"u0"},
    "e60910831b924963bf77efbd75dffa43":{
      "scriptId":"u1"},
    "dc297ad50002470094e45386604cd416":{
      "scriptId":"u2"},
    "6d3fd33c6e2841c8bfbb5187916c19aa":{
      "scriptId":"u3"},
    "e37cc18c9dcb4f97ac86a6c8341391ca":{
      "scriptId":"u4"},
    "e4198a78d25842748172212e081a1d7f":{
      "scriptId":"u5"},
    "4684351f0cbb49dc8768664775506d3e":{
      "scriptId":"u6"},
    "b7c255a198df4ceb8bb1ad1abceaa4a9":{
      "scriptId":"u7"},
    "c05833ebe17541d7806d03f4f485a64e":{
      "scriptId":"u8"},
    "ce16ac65df5641c88eebf47b9de1f699":{
      "scriptId":"u9"},
    "aba3a4a628ee421db4a4acb7c1f893bb":{
      "scriptId":"u10"},
    "f5df196a14204168a70d411e9e275434":{
      "scriptId":"u11"},
    "9a08512b6f3245f4ba16658c2eb3141b":{
      "scriptId":"u12"},
    "2a7cece5c036461caf047a1c12cf113d":{
      "scriptId":"u13"},
    "8ab7e0b498894f08954c77f9b0c17bd7":{
      "scriptId":"u14"},
    "b5eeed2670c74e1bb998bcf719d861e1":{
      "scriptId":"u15"},
    "329098c6f4a541f4aa7c259bfed1a1c6":{
      "scriptId":"u16"},
    "d8f76a7126af43baad4cfad24ace4de6":{
      "scriptId":"u17"}}});