$axure.loadCurrentPage({
  "url":"导航模块.html",
  "generationDate":new Date(1495872720454.11),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"text_keyword"],
  "page":{
    "packageId":"c359e16dd0e5463199b9882aa46655f5",
    "type":"Axure:Page",
    "name":"导航模块",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onScroll":{
        "description":"OnScroll",
        "cases":[{
            "description":"Case 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"fadeWidget",
                "description":"Show/Hide Widget",
                "objectsToFades":[]}]}]}},
    "diagram":{
      "objects":[{
          "id":"7ffb81e411db487884e10e3825357222",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":120,
              "y":42},
            "size":{
              "width":480,
              "height":788}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abeed07deb05424782b4fced4a05437a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":120,
                  "y":42},
                "size":{
                  "width":480,
                  "height":788}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航模块/u0.png"}},
{
          "id":"dbc185effba64580bbe87c26ff210a1a",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":42},
            "size":{
              "width":480,
              "height":728}},
          "adaptiveStyles":{
}},
{
          "id":"cf2f3ad75e064b468cbd73f45b7e7978",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "stateStyles":{
              "hint":{
                "fontStyle":"italic"}},
            "location":{
              "x":162,
              "y":50},
            "size":{
              "width":308,
              "height":50}},
          "adaptiveStyles":{
},
          "submitButton":{
            "path":[],
            "id":"4a4072d8397449fea9b3c637786c5c5c"},
          "interactionMap":{
            "onFocus":{
              "description":"OnFocus",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 搜索 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"搜索.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "placeholderText":"              搜索"},
{
          "id":"0317e776f12949ff8bc9bba376e70fce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":120,
              "y":765},
            "size":{
              "width":160,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ef8f2d7bd2d426c8f0102a633afdfa5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":120,
                  "y":765},
                "size":{
                  "width":160,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 附近 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"附近.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/导航模块/u4.png"}},
{
          "id":"df418c3df4a64f3ea6863b125479f2b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":280,
              "y":765},
            "size":{
              "width":160,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21c9d79636ac4c9497099e11b0902c2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":280,
                  "y":765},
                "size":{
                  "width":160,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 路线 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"路线.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/导航模块/u6.png"}},
{
          "id":"c0915af2dbcd4923883b11b4af3e00c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":440,
              "y":765},
            "size":{
              "width":160,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bac9203b47574a1e8a05a47adf3cc103",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":440,
                  "y":765},
                "size":{
                  "width":160,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 景点 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"景点.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/导航模块/u8.png"}},
{
          "id":"4a4072d8397449fea9b3c637786c5c5c",
          "label":"搜索按钮",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":162,
              "y":58},
            "size":{
              "width":38,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60f7c27674bc40a8b14d6a12eea5d844",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":162,
                  "y":58},
                "size":{
                  "width":38,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航模块/搜索按钮_u10.png"}},
{
          "id":"3b6619fcf7e745eba6783f7aa88d7331",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":106},
            "size":{
              "width":39,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3d50b48bb3f4276b624f49019486672",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":106},
                "size":{
                  "width":39,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航模块/u12.png"}},
{
          "id":"6d47c32755f7471fa89a107f6c6a0fa6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":144,
              "y":778},
            "size":{
              "width":39,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"131ef371bbb44f2e823b4a784170a52c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":144,
                  "y":778},
                "size":{
                  "width":39,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航模块/u14.png"}},
{
          "id":"4f446095c7ab4014bde6c9d0065c09da",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":303,
              "y":778},
            "size":{
              "width":39,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e54f9e272e245b3a15544970d0b38b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":303,
                  "y":778},
                "size":{
                  "width":39,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航模块/u16.png"}},
{
          "id":"e83f4c83377b42d2b7482b5fd6547a8e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":778},
            "size":{
              "width":50,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76f9a6b516984113867cceaee348cb2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":778},
                "size":{
                  "width":50,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航模块/u18.png"}},
{
          "id":"afa1c8589c41437db2968a608b88f7fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":750,
              "y":75},
            "size":{
              "width":841,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"387df20d2f06476da6fa46ca479279e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":750,
                  "y":75},
                "size":{
                  "width":841,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e30eac4982ac47759606bf060709d98f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":544,
              "y":145},
            "size":{
              "width":52,
              "height":89}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e098281bd1ad4f008391d1c2ce1d345f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":544,
                  "y":145},
                "size":{
                  "width":52,
                  "height":89}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd342753bde644669cccffed65ef6fcd",
          "label":"侧边栏菜单",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":120,
              "y":42},
            "size":{
              "width":350,
              "height":788},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"819abbea3fdd4682b70840a94af7ae5e",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"dc8d2b98bff544538bac299ab51b1f1b",
                  "label":"",
                  "parentDynamicPanel":"dd342753bde644669cccffed65ef6fcd",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF00CCFF},
                    "size":{
                      "width":330,
                      "height":788}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eabc97d91b9b41538e2a15735a34f011",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd342753bde644669cccffed65ef6fcd",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF00CCFF},
                        "size":{
                          "width":330,
                          "height":788}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/导航模块/u25.png"}},
{
                  "id":"927f62d90d5c416eafbab77b5d74098f",
                  "label":"",
                  "parentDynamicPanel":"dd342753bde644669cccffed65ef6fcd",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":31,
                      "y":71},
                    "size":{
                      "width":96,
                      "height":94}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"64f91a7159df46509caa63e3ca0e21af",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd342753bde644669cccffed65ef6fcd",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":31,
                          "y":71},
                        "size":{
                          "width":96,
                          "height":94}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/导航模块/u27.png"}},
{
                  "id":"a6a4748521dd453d86d279674d6daac4",
                  "label":"",
                  "parentDynamicPanel":"dd342753bde644669cccffed65ef6fcd",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":37,
                      "y":188},
                    "size":{
                      "width":98,
                      "height":31}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f45ed45fb18d49138fafa65d8cbef34c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd342753bde644669cccffed65ef6fcd",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":37,
                          "y":188},
                        "size":{
                          "width":98,
                          "height":31}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open 登录 in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"登录.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"900b33a46ddf4be3aace41984fea4ac2",
                  "label":"",
                  "parentDynamicPanel":"dd342753bde644669cccffed65ef6fcd",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":224},
                    "size":{
                      "width":330,
                      "height":564}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5f2ae32ee74c47d58aa2593e011a9977",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd342753bde644669cccffed65ef6fcd",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":224},
                        "size":{
                          "width":330,
                          "height":564}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/导航模块/u31.png"}},
{
                  "id":"e99fbeb893b541f194c4a004a4e48cce",
                  "label":"校园社交",
                  "parentDynamicPanel":"dd342753bde644669cccffed65ef6fcd",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":22,
                      "y":260},
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open 校园社交 in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"校园社交.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"fa156075061b489c8c252063d1f8c94e",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"2c2eb0a2093d4bd2baf25a90b24224ff",
                          "label":"",
                          "parentDynamicPanel":"e99fbeb893b541f194c4a004a4e48cce",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":50,
                              "height":50}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"9e2573abb5e34cf2abf9f922d7e44916",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"e99fbeb893b541f194c4a004a4e48cce",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":50,
                                  "height":50}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/导航模块/u34.png"}},
{
                          "id":"3d0e0562f6df4ff998ce892ac8d85d13",
                          "label":"",
                          "parentDynamicPanel":"e99fbeb893b541f194c4a004a4e48cce",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"20px",
                            "location":{
                              "x":81,
                              "y":15},
                            "size":{
                              "width":81,
                              "height":15}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"f2d1746dab614c6d9403a5a4938f37e5",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"e99fbeb893b541f194c4a004a4e48cce",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"20px",
                                "location":{
                                  "x":81,
                                  "y":15},
                                "size":{
                                  "width":81,
                                  "height":15}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}}]}]},
{
                  "id":"38fdbc2ed77d4ae2be199d181b0910fd",
                  "label":"生活服务",
                  "parentDynamicPanel":"dd342753bde644669cccffed65ef6fcd",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":22,
                      "y":349},
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Link in Current Window",
                              "target":{
                                "targetType":"page",
                                "includeVariables":true},
                              "linkType":"current"},
{
                              "action":"linkWindow",
                              "description":"Open 生活服务 in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"生活服务.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"ee7ffc3593894148ad836db779b3fb8d",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"ee525e628c824eb6b8f386f5689cfca2",
                          "label":"",
                          "parentDynamicPanel":"38fdbc2ed77d4ae2be199d181b0910fd",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":50,
                              "height":50}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"144f72cf75ed4c5a89550573fe99bd83",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"38fdbc2ed77d4ae2be199d181b0910fd",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":50,
                                  "height":50}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/导航模块/u39.png"}},
{
                          "id":"60881be1876a41d488d15353f17d0d0a",
                          "label":"",
                          "parentDynamicPanel":"38fdbc2ed77d4ae2be199d181b0910fd",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"20px",
                            "location":{
                              "x":81,
                              "y":15},
                            "size":{
                              "width":81,
                              "height":15}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"f3cf34a8e716463989d945d9a7b78fd0",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"38fdbc2ed77d4ae2be199d181b0910fd",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"20px",
                                "location":{
                                  "x":81,
                                  "y":15},
                                "size":{
                                  "width":81,
                                  "height":15}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}}]}]},
{
                  "id":"db3773d4b1ad410caecd6d002f14433e",
                  "label":"事务办理",
                  "parentDynamicPanel":"dd342753bde644669cccffed65ef6fcd",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":22,
                      "y":439},
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open 事务办理 in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"事务办理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"5f4af8b174ac4ee9811788790eb332e4",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"44da8600552d48e89fc466bd593abec2",
                          "label":"",
                          "parentDynamicPanel":"db3773d4b1ad410caecd6d002f14433e",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":50,
                              "height":50}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"a5b1d2f619324a4ca1dd56f0994de0c7",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"db3773d4b1ad410caecd6d002f14433e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":50,
                                  "height":50}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/导航模块/u44.png"}},
{
                          "id":"6204127d2d184d7aaf7e2af638fb056e",
                          "label":"",
                          "parentDynamicPanel":"db3773d4b1ad410caecd6d002f14433e",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"20px",
                            "location":{
                              "x":81,
                              "y":14},
                            "size":{
                              "width":81,
                              "height":15}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"b54d27fd51f54be29e9876299afc88f0",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"db3773d4b1ad410caecd6d002f14433e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"20px",
                                "location":{
                                  "x":81,
                                  "y":14},
                                "size":{
                                  "width":81,
                                  "height":15}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}}]}]},
{
                  "id":"f333de5804ad49f1ba2168a1788d8d4d",
                  "label":"设置",
                  "parentDynamicPanel":"dd342753bde644669cccffed65ef6fcd",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":22,
                      "y":530},
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open 设置 in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"设置.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"48bf32ac4eb4425e98f2ce9d96dc19c2",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"0368c47510214fd5b17548aebd28b2cd",
                          "label":"",
                          "parentDynamicPanel":"f333de5804ad49f1ba2168a1788d8d4d",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":50,
                              "height":50}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"d745ee0448604e19aeb74b0d5ca55183",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"f333de5804ad49f1ba2168a1788d8d4d",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":50,
                                  "height":50}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/导航模块/u49.png"}},
{
                          "id":"424091b452e24928b8850486bf54c6fe",
                          "label":"",
                          "parentDynamicPanel":"f333de5804ad49f1ba2168a1788d8d4d",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"20px",
                            "location":{
                              "x":81,
                              "y":14},
                            "size":{
                              "width":41,
                              "height":23}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"0bae15c17a694a3fb60a7e132dd51cff",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"f333de5804ad49f1ba2168a1788d8d4d",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"20px",
                                "location":{
                                  "x":81,
                                  "y":14},
                                "size":{
                                  "width":41,
                                  "height":23}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}}]}]}]}]},
{
          "id":"1c91cd3fd3dc415a8dc75e5a90939af3",
          "label":"打开侧边栏",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":123,
              "y":55},
            "size":{
              "width":35,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c03ab9207f642d487159429f6983b99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":123,
                  "y":55},
                "size":{
                  "width":35,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle 侧边栏菜单",
                      "objectsToFades":[{
                          "objectPath":["dd342753bde644669cccffed65ef6fcd"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/导航模块/打开侧边栏_u53.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "7ffb81e411db487884e10e3825357222":{
      "scriptId":"u0"},
    "abeed07deb05424782b4fced4a05437a":{
      "scriptId":"u1"},
    "dbc185effba64580bbe87c26ff210a1a":{
      "scriptId":"u2"},
    "cf2f3ad75e064b468cbd73f45b7e7978":{
      "scriptId":"u3"},
    "0317e776f12949ff8bc9bba376e70fce":{
      "scriptId":"u4"},
    "8ef8f2d7bd2d426c8f0102a633afdfa5":{
      "scriptId":"u5"},
    "df418c3df4a64f3ea6863b125479f2b1":{
      "scriptId":"u6"},
    "21c9d79636ac4c9497099e11b0902c2b":{
      "scriptId":"u7"},
    "c0915af2dbcd4923883b11b4af3e00c8":{
      "scriptId":"u8"},
    "bac9203b47574a1e8a05a47adf3cc103":{
      "scriptId":"u9"},
    "4a4072d8397449fea9b3c637786c5c5c":{
      "scriptId":"u10"},
    "60f7c27674bc40a8b14d6a12eea5d844":{
      "scriptId":"u11"},
    "3b6619fcf7e745eba6783f7aa88d7331":{
      "scriptId":"u12"},
    "d3d50b48bb3f4276b624f49019486672":{
      "scriptId":"u13"},
    "6d47c32755f7471fa89a107f6c6a0fa6":{
      "scriptId":"u14"},
    "131ef371bbb44f2e823b4a784170a52c":{
      "scriptId":"u15"},
    "4f446095c7ab4014bde6c9d0065c09da":{
      "scriptId":"u16"},
    "6e54f9e272e245b3a15544970d0b38b5":{
      "scriptId":"u17"},
    "e83f4c83377b42d2b7482b5fd6547a8e":{
      "scriptId":"u18"},
    "76f9a6b516984113867cceaee348cb2e":{
      "scriptId":"u19"},
    "afa1c8589c41437db2968a608b88f7fb":{
      "scriptId":"u20"},
    "387df20d2f06476da6fa46ca479279e6":{
      "scriptId":"u21"},
    "e30eac4982ac47759606bf060709d98f":{
      "scriptId":"u22"},
    "e098281bd1ad4f008391d1c2ce1d345f":{
      "scriptId":"u23"},
    "dd342753bde644669cccffed65ef6fcd":{
      "scriptId":"u24"},
    "dc8d2b98bff544538bac299ab51b1f1b":{
      "scriptId":"u25"},
    "eabc97d91b9b41538e2a15735a34f011":{
      "scriptId":"u26"},
    "927f62d90d5c416eafbab77b5d74098f":{
      "scriptId":"u27"},
    "64f91a7159df46509caa63e3ca0e21af":{
      "scriptId":"u28"},
    "a6a4748521dd453d86d279674d6daac4":{
      "scriptId":"u29"},
    "f45ed45fb18d49138fafa65d8cbef34c":{
      "scriptId":"u30"},
    "900b33a46ddf4be3aace41984fea4ac2":{
      "scriptId":"u31"},
    "5f2ae32ee74c47d58aa2593e011a9977":{
      "scriptId":"u32"},
    "e99fbeb893b541f194c4a004a4e48cce":{
      "scriptId":"u33"},
    "2c2eb0a2093d4bd2baf25a90b24224ff":{
      "scriptId":"u34"},
    "9e2573abb5e34cf2abf9f922d7e44916":{
      "scriptId":"u35"},
    "3d0e0562f6df4ff998ce892ac8d85d13":{
      "scriptId":"u36"},
    "f2d1746dab614c6d9403a5a4938f37e5":{
      "scriptId":"u37"},
    "38fdbc2ed77d4ae2be199d181b0910fd":{
      "scriptId":"u38"},
    "ee525e628c824eb6b8f386f5689cfca2":{
      "scriptId":"u39"},
    "144f72cf75ed4c5a89550573fe99bd83":{
      "scriptId":"u40"},
    "60881be1876a41d488d15353f17d0d0a":{
      "scriptId":"u41"},
    "f3cf34a8e716463989d945d9a7b78fd0":{
      "scriptId":"u42"},
    "db3773d4b1ad410caecd6d002f14433e":{
      "scriptId":"u43"},
    "44da8600552d48e89fc466bd593abec2":{
      "scriptId":"u44"},
    "a5b1d2f619324a4ca1dd56f0994de0c7":{
      "scriptId":"u45"},
    "6204127d2d184d7aaf7e2af638fb056e":{
      "scriptId":"u46"},
    "b54d27fd51f54be29e9876299afc88f0":{
      "scriptId":"u47"},
    "f333de5804ad49f1ba2168a1788d8d4d":{
      "scriptId":"u48"},
    "0368c47510214fd5b17548aebd28b2cd":{
      "scriptId":"u49"},
    "d745ee0448604e19aeb74b0d5ca55183":{
      "scriptId":"u50"},
    "424091b452e24928b8850486bf54c6fe":{
      "scriptId":"u51"},
    "0bae15c17a694a3fb60a7e132dd51cff":{
      "scriptId":"u52"},
    "1c91cd3fd3dc415a8dc75e5a90939af3":{
      "scriptId":"u53"},
    "5c03ab9207f642d487159429f6983b99":{
      "scriptId":"u54"}}});