$axure.loadCurrentPage({
  "url":"发布.html",
  "generationDate":new Date(1495872722478.44),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"text_keyword"],
  "page":{
    "packageId":"245994354b724d2393ae82d63efa4825",
    "type":"Axure:Page",
    "name":"发布",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"68b9fd51db6e4c90b6e38197c7df94e6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":10},
            "size":{
              "width":530,
              "height":960}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eaa8bad54d444624b226177a8083320c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":10},
                "size":{
                  "width":530,
                  "height":960}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/校园社交/u0.png"}},
{
          "id":"d010a0166f694a6fa38b2ad46925b589",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":92},
            "size":{
              "width":480,
              "height":800}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7015ce084dfb4a169af0cd65be746123",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":92},
                "size":{
                  "width":480,
                  "height":800}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/附近/u0.png"}},
{
          "id":"2a63a3c1555248849a5e4ed377eaeeae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":92},
            "size":{
              "width":480,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d6e87594c9d4c899e4feed26e1c8fcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":92},
                "size":{
                  "width":480,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/找老乡/u4.png"}},
{
          "id":"7e5c02fc8374400e95ddd9e4585f031f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":256,
              "y":161},
            "size":{
              "width":455,
              "height":169}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0e68e21bacc49c38bd9667a725c371b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":256,
                  "y":161},
                "size":{
                  "width":455,
                  "height":169}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布/u6.png"}},
{
          "id":"f48530c01ff7485983505464ffda887f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":503},
            "size":{
              "width":480,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/发布/u8_line.png"}},
{
          "id":"1a58a880504b4409894d5a5b6fefa234",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":394,
              "y":589},
            "size":{
              "width":192,
              "height":54}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"b7842f16fc684aa2b475f9d554e80b53",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"36px",
            "fontWeight":"500",
            "horizontalAlignment":"center",
            "location":{
              "x":239,
              "y":104},
            "size":{
              "width":109,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d411b6d52d149b5a93af31119078383",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"36px",
                "fontWeight":"500",
                "horizontalAlignment":"center",
                "location":{
                  "x":239,
                  "y":104},
                "size":{
                  "width":109,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2eec782e477a4215ac5729c8dd340319",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"36px",
            "fontWeight":"500",
            "location":{
              "x":470,
              "y":420},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e70ae6493af547c2a4529801799c7cbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"36px",
                "fontWeight":"500",
                "location":{
                  "x":470,
                  "y":420},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c9bd03e4babd48aaa160df2cec1343e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"176px",
            "fontWeight":"500",
            "location":{
              "x":256,
              "y":300},
            "size":{
              "width":186,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27e1cb4447e2474aa262ba25f57ddb58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"176px",
                "fontWeight":"500",
                "location":{
                  "x":256,
                  "y":300},
                "size":{
                  "width":186,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "68b9fd51db6e4c90b6e38197c7df94e6":{
      "scriptId":"u0"},
    "eaa8bad54d444624b226177a8083320c":{
      "scriptId":"u1"},
    "d010a0166f694a6fa38b2ad46925b589":{
      "scriptId":"u2"},
    "7015ce084dfb4a169af0cd65be746123":{
      "scriptId":"u3"},
    "2a63a3c1555248849a5e4ed377eaeeae":{
      "scriptId":"u4"},
    "0d6e87594c9d4c899e4feed26e1c8fcb":{
      "scriptId":"u5"},
    "7e5c02fc8374400e95ddd9e4585f031f":{
      "scriptId":"u6"},
    "e0e68e21bacc49c38bd9667a725c371b":{
      "scriptId":"u7"},
    "f48530c01ff7485983505464ffda887f":{
      "scriptId":"u8"},
    "1a58a880504b4409894d5a5b6fefa234":{
      "scriptId":"u9"},
    "b7842f16fc684aa2b475f9d554e80b53":{
      "scriptId":"u10"},
    "0d411b6d52d149b5a93af31119078383":{
      "scriptId":"u11"},
    "2eec782e477a4215ac5729c8dd340319":{
      "scriptId":"u12"},
    "e70ae6493af547c2a4529801799c7cbd":{
      "scriptId":"u13"},
    "c9bd03e4babd48aaa160df2cec1343e2":{
      "scriptId":"u14"},
    "27e1cb4447e2474aa262ba25f57ddb58":{
      "scriptId":"u15"}}});