$axure.loadCurrentPage({
  "url":"景点详情-东门.html",
  "generationDate":new Date(1495872721369.16),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"text_keyword"],
  "page":{
    "packageId":"5d2ce122d61945148686a80dc8c36812",
    "type":"Axure:Page",
    "name":"景点详情-东门",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"Case 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"setPanelState",
                "description":"Set (Dynamic Panel) to Next slide left out 500ms slide right in 500ms wrap repeat every 3000 ms",
                "panelsToStates":[{
                    "panelPath":["46a48fe751da40fbb438df25b642d2f0"],
                    "stateInfo":{
                      "setStateType":"next",
                      "stateNumber":1,
                      "stateValue":{
                        "exprType":"stringLiteral",
                        "value":"1",
                        "stos":[]},
                      "loop":true,
                      "showWhenSet":false,
                      "repeat":3000,
                      "options":{
                        "animateOut":{
                          "easing":"slideLeft",
                          "duration":500},
                        "animateIn":{
                          "easing":"slideRight",
                          "duration":500},
                        "compress":false}}}]}]}]}},
    "diagram":{
      "objects":[{
          "id":"1daa94b611d6477d939338220b5c1067",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":70,
              "y":40},
            "size":{
              "width":480,
              "height":800}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8b4d13269d2467abc4178ff235354d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":70,
                  "y":40},
                "size":{
                  "width":480,
                  "height":800}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/附近/u0.png"}},
{
          "id":"46a48fe751da40fbb438df25b642d2f0",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":40},
            "size":{
              "width":480,
              "height":210}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"bdb991545c3b4fd7abd3ce5dae7a57c9",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1180b72a6de948e2aa6e07662891e9dd",
                  "label":"",
                  "parentDynamicPanel":"46a48fe751da40fbb438df25b642d2f0",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":480,
                      "height":210}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8c470c1a0f33497dbe2e271bd34f7c3c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"46a48fe751da40fbb438df25b642d2f0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":480,
                          "height":210}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/景点详情-东门/u3.png"}}]},
{
              "id":"03e2bf512fb64ba8836cc6bf489a1cf2",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"36b1827ad9464e97a86ca4ceaab85a4c",
                  "label":"",
                  "parentDynamicPanel":"46a48fe751da40fbb438df25b642d2f0",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":480,
                      "height":210}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"35763e1c4f524be9b7f6533a86b67496",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"46a48fe751da40fbb438df25b642d2f0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":480,
                          "height":210}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/景点详情-东门/u5.png"}}]},
{
              "id":"d7cd72b814114184901fbf8b3e1ca75f",
              "label":"State3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"eb120999627840d5ba9fcdd63d8e438a",
                  "label":"",
                  "parentDynamicPanel":"46a48fe751da40fbb438df25b642d2f0",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":480,
                      "height":210}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"82ac7b17c76547849bc8463bc6ca3645",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"46a48fe751da40fbb438df25b642d2f0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":480,
                          "height":210}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/景点详情-东门/u7.png"}}]}]},
{
          "id":"3772488c79ac40c0992d92832f1e4979",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":78,
              "y":47},
            "size":{
              "width":38,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99eab947d1f24ce78798ad44b99febaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":78,
                  "y":47},
                "size":{
                  "width":38,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 景点 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"景点.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/景点详情-东门/u9.png"}},
{
          "id":"c9bda387372d4bf7a251a3ac24562564",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"25px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":89,
              "y":206},
            "size":{
              "width":51,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b12b31dd6404516bc851bd6304bc2a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"25px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":89,
                  "y":206},
                "size":{
                  "width":51,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7fdbef7e04f14ffcb86ecb5253c35081",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":89,
              "y":260},
            "size":{
              "width":442,
              "height":93}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"905e060cd8cd435aa02829ebcbe03db8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":89,
                  "y":260},
                "size":{
                  "width":442,
                  "height":93}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1962abc468f4655b89288d4f41a7db3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":89,
              "y":549},
            "size":{
              "width":442,
              "height":93}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c5be53f09f94f21bd42c93b7bf6547a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":89,
                  "y":549},
                "size":{
                  "width":442,
                  "height":93}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e4ce85816bd4246992f8d2c3b335e64",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":454,
              "y":222},
            "size":{
              "width":58,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd061f8c13024ddaa0ac62ab9ba97f85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":454,
                  "y":222},
                "size":{
                  "width":58,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 导航 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"导航.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/搜索结果-欢乐谷/u17.png"}},
{
          "id":"cb38a1a025224d16b625f51b0dca591e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":650,
              "y":40},
            "size":{
              "width":300,
              "height":117}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"575aa5f4ca1a47629bcf0cdcda10e197",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":650,
                  "y":40},
                "size":{
                  "width":300,
                  "height":117}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2fcf5a05df274adc9e6a0e446d4a1b81",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":89,
              "y":377},
            "size":{
              "width":421,
              "height":161}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1c24b3fd01347b791965f20d08e1289",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":89,
                  "y":377},
                "size":{
                  "width":421,
                  "height":161}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/景点详情-东门/u21.png"}},
{
          "id":"51fc5f46a1f44916ba3cf68b466b4430",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":89,
              "y":660},
            "size":{
              "width":421,
              "height":161}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"039c1ff7534c4709950956455b96d551",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":89,
                  "y":660},
                "size":{
                  "width":421,
                  "height":161}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/景点详情-东门/u23.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "1daa94b611d6477d939338220b5c1067":{
      "scriptId":"u0"},
    "c8b4d13269d2467abc4178ff235354d6":{
      "scriptId":"u1"},
    "46a48fe751da40fbb438df25b642d2f0":{
      "scriptId":"u2"},
    "1180b72a6de948e2aa6e07662891e9dd":{
      "scriptId":"u3"},
    "8c470c1a0f33497dbe2e271bd34f7c3c":{
      "scriptId":"u4"},
    "36b1827ad9464e97a86ca4ceaab85a4c":{
      "scriptId":"u5"},
    "35763e1c4f524be9b7f6533a86b67496":{
      "scriptId":"u6"},
    "eb120999627840d5ba9fcdd63d8e438a":{
      "scriptId":"u7"},
    "82ac7b17c76547849bc8463bc6ca3645":{
      "scriptId":"u8"},
    "3772488c79ac40c0992d92832f1e4979":{
      "scriptId":"u9"},
    "99eab947d1f24ce78798ad44b99febaf":{
      "scriptId":"u10"},
    "c9bda387372d4bf7a251a3ac24562564":{
      "scriptId":"u11"},
    "5b12b31dd6404516bc851bd6304bc2a9":{
      "scriptId":"u12"},
    "7fdbef7e04f14ffcb86ecb5253c35081":{
      "scriptId":"u13"},
    "905e060cd8cd435aa02829ebcbe03db8":{
      "scriptId":"u14"},
    "c1962abc468f4655b89288d4f41a7db3":{
      "scriptId":"u15"},
    "6c5be53f09f94f21bd42c93b7bf6547a":{
      "scriptId":"u16"},
    "0e4ce85816bd4246992f8d2c3b335e64":{
      "scriptId":"u17"},
    "bd061f8c13024ddaa0ac62ab9ba97f85":{
      "scriptId":"u18"},
    "cb38a1a025224d16b625f51b0dca591e":{
      "scriptId":"u19"},
    "575aa5f4ca1a47629bcf0cdcda10e197":{
      "scriptId":"u20"},
    "2fcf5a05df274adc9e6a0e446d4a1b81":{
      "scriptId":"u21"},
    "b1c24b3fd01347b791965f20d08e1289":{
      "scriptId":"u22"},
    "51fc5f46a1f44916ba3cf68b466b4430":{
      "scriptId":"u23"},
    "039c1ff7534c4709950956455b96d551":{
      "scriptId":"u24"}}});