$axure.loadCurrentPage({
  "url":"新闻浏览.html",
  "generationDate":new Date(1495872720688.65),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"text_keyword"],
  "page":{
    "packageId":"de97b6c260dc43338b0761b51092eefe",
    "type":"Axure:Page",
    "name":"新闻浏览",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"635ff70d0f934a698d7ac944832634c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":20},
            "size":{
              "width":480,
              "height":800}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"358a5dfc64a34ea684d574ebe2196643",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":20},
                "size":{
                  "width":480,
                  "height":800}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/附近/u0.png"}},
{
          "id":"dd61f390901843788b61e24d051415c6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":41},
            "size":{
              "width":40,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"798fd87b68e94484a8f938197041d5cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":41},
                "size":{
                  "width":40,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 附近 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"附近.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/附近/u3.png"}},
{
          "id":"f0055883e5d24087b6422de03007a7dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":140,
              "y":41},
            "size":{
              "width":145,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ebe7243368c4b3c96fd32c6140c7cbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":140,
                  "y":41},
                "size":{
                  "width":145,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd7a2363f05642cf9a888e5a9de9c20b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":96},
            "size":{
              "width":480,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新闻浏览/u6_line.png"}},
{
          "id":"c86be7f0c745418a8b25feb04903cf23",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":85,
              "y":116},
            "size":{
              "width":460,
              "height":114}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"584165ceb53a4d84af2ed1dfb6337a9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":85,
                  "y":116},
                "size":{
                  "width":460,
                  "height":114}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f2acbb1c41a46ef9de3858333bc3b35",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":627,
              "y":130},
            "size":{
              "width":461,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fc8682f616a439bbf2e25741ba2e96f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":627,
                  "y":130},
                "size":{
                  "width":461,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e6a16469fee14bf5acb3e6d7dbd8ef30",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":83,
              "y":570},
            "size":{
              "width":460,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d705a5068794928846ff8f5a1e81adc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":83,
                  "y":570},
                "size":{
                  "width":460,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b1c18b5a346422882d1e2c2f933e203",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":85,
              "y":350},
            "size":{
              "width":445,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92a350ac7e1c4dcf95acfc7459aaba13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":85,
                  "y":350},
                "size":{
                  "width":445,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新闻浏览/u13.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "635ff70d0f934a698d7ac944832634c5":{
      "scriptId":"u0"},
    "358a5dfc64a34ea684d574ebe2196643":{
      "scriptId":"u1"},
    "dd61f390901843788b61e24d051415c6":{
      "scriptId":"u2"},
    "798fd87b68e94484a8f938197041d5cd":{
      "scriptId":"u3"},
    "f0055883e5d24087b6422de03007a7dc":{
      "scriptId":"u4"},
    "9ebe7243368c4b3c96fd32c6140c7cbe":{
      "scriptId":"u5"},
    "dd7a2363f05642cf9a888e5a9de9c20b":{
      "scriptId":"u6"},
    "c86be7f0c745418a8b25feb04903cf23":{
      "scriptId":"u7"},
    "584165ceb53a4d84af2ed1dfb6337a9d":{
      "scriptId":"u8"},
    "1f2acbb1c41a46ef9de3858333bc3b35":{
      "scriptId":"u9"},
    "0fc8682f616a439bbf2e25741ba2e96f":{
      "scriptId":"u10"},
    "e6a16469fee14bf5acb3e6d7dbd8ef30":{
      "scriptId":"u11"},
    "3d705a5068794928846ff8f5a1e81adc":{
      "scriptId":"u12"},
    "9b1c18b5a346422882d1e2c2f933e203":{
      "scriptId":"u13"},
    "92a350ac7e1c4dcf95acfc7459aaba13":{
      "scriptId":"u14"}}});