$axure.loadCurrentPage({
  "url":"用户管理.html",
  "generationDate":new Date(1495872724256.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"text_keyword"],
  "page":{
    "packageId":"93c32f9eb2b9478fae279549a3c4365e",
    "type":"Axure:Page",
    "name":"用户管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ff67cfa3550f4fae8f97c574aa70647f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":20},
            "size":{
              "width":760,
              "height":440}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96e762bad7f74d78aa25fcdfa29eb1f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":20},
                "size":{
                  "width":760,
                  "height":440}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/后台/u0.png"}},
{
          "id":"a44144f98d6b4b969a678e725d69e0c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF363636},
            "location":{
              "x":210,
              "y":80},
            "size":{
              "width":210,
              "height":380}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"372206bd3c784346ac9e9b111fd7c8f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF363636},
                "location":{
                  "x":210,
                  "y":80},
                "size":{
                  "width":210,
                  "height":380}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/后台/u2.png"}},
{
          "id":"379100902ef74de88bf139d005cb932d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":264,
              "y":121},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58f89fd3f4cd404fa6441fa7d794b9f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":264,
                  "y":121},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/后台/u8.png"}},
{
          "id":"04e6b1d85acb42ec884e06e2261cb2f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":264,
              "y":181},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37a9dd5fb55645be9528fbdb315c5f19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":264,
                  "y":181},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/后台/u8.png"}},
{
          "id":"15743cfa51eb4d91a4a9271dd4dbd822",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "location":{
              "x":264,
              "y":241},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce49fd90f61444dbb0077e27a1453388",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":264,
                  "y":241},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/后台/u6.png"}},
{
          "id":"950691f465ae4630926fddeb2ca00e23",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":264,
              "y":301},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e74786660bdb4dfe83592becc4d85aef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":264,
                  "y":301},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/后台/u8.png"}},
{
          "id":"1c168139ed9d4594a21983921a454865",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":420,
              "y":80},
            "size":{
              "width":550,
              "height":380},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffe765210b7c4812966e1907b98741a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":420,
                  "y":80},
                "size":{
                  "width":550,
                  "height":380},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u12.png"}},
{
          "id":"06dbdd7cd5b74602a47a1bc24366e398",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":121},
            "size":{
              "width":550,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68ea2bd88eaf48878f037fc2b5377a38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":121},
                "size":{
                  "width":550,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u14.png"}},
{
          "id":"4d320445d64e4636b04ad6144aa48540",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":430,
              "y":92},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77a2410b801d41d58b3804d0125d15c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":430,
                  "y":92},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fed2494191624419a94dbbd3d1baf5dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":121},
            "size":{
              "width":40,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"422a5aec26bd4defb6c0fd4e0512348a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":121},
                "size":{
                  "width":40,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u18.png"}},
{
          "id":"600e92ce7cc24dba8dfb0bd8eedb4ee0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":121},
            "size":{
              "width":60,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0af5eca54de4215ae81bbfca0a1e9b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":121},
                "size":{
                  "width":60,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u20.png"}},
{
          "id":"20c524675a5542d78e2ea9d577f9f330",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":121},
            "size":{
              "width":70,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"092f48833ac44031990384cc0afffe4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":121},
                "size":{
                  "width":70,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u22.png"}},
{
          "id":"549ed2781a824b20bbc3608c2330b0a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":121},
            "size":{
              "width":90,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31bf03e99b7c4c5c80a7aba2d6d4075f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":121},
                "size":{
                  "width":90,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u24.png"}},
{
          "id":"dbd8b3e12d094caf9b7307e62551974d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":675,
              "y":121},
            "size":{
              "width":45,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd5af7edca4b43b193a29573127ad3d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":675,
                  "y":121},
                "size":{
                  "width":45,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u26.png"}},
{
          "id":"7641350a1fea460cb7bcf9b015e91413",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":720,
              "y":121},
            "size":{
              "width":180,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8393c132af2c4dcd8c425a02897e6385",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":720,
                  "y":121},
                "size":{
                  "width":180,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u28.png"}},
{
          "id":"f28f5992f1ef4933b43253597ca32348",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":121},
            "size":{
              "width":70,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73c71b544c7c4350b7862dc0cb729913",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":121},
                "size":{
                  "width":70,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u22.png"}},
{
          "id":"6d0587eb7e0a48daafcd103f5ed71058",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":160},
            "size":{
              "width":550,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddea55e4caf242f6b2d0a2d0428c6cd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":160},
                "size":{
                  "width":550,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u14.png"}},
{
          "id":"154370796d1448bca9b602fcdb8318c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":160},
            "size":{
              "width":40,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6aec9e28086849d59c2c568e4e5eb5db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":160},
                "size":{
                  "width":40,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u18.png"}},
{
          "id":"6ce2a704a3864b03affc12bc2e0bced0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":160},
            "size":{
              "width":60,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46dbd910663a4706bb29e4ce11378208",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":160},
                "size":{
                  "width":60,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u20.png"}},
{
          "id":"3aeaaa79319d4a4b9d7303857f7ac2f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":160},
            "size":{
              "width":70,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94405587f85540d1853e80cf30aa13db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":160},
                "size":{
                  "width":70,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u22.png"}},
{
          "id":"6a661b1b0a5f4bc6969bb63b8e9fe9a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":160},
            "size":{
              "width":90,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2aee7660a9244d6ca24e77543b659e0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":160},
                "size":{
                  "width":90,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u24.png"}},
{
          "id":"343d2f6fd0e64e31ae4050a8434442cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":675,
              "y":160},
            "size":{
              "width":45,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1f104b47c7f4074b8fc26f86b647b78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":675,
                  "y":160},
                "size":{
                  "width":45,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u26.png"}},
{
          "id":"b648d9b659a4481d91f04fe66c963574",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":720,
              "y":160},
            "size":{
              "width":180,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dab2894c3aa64b4c9561cbae8418d92d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":720,
                  "y":160},
                "size":{
                  "width":180,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u28.png"}},
{
          "id":"15bb3c626f1140e982d3cd916b23b9e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":900,
              "y":160},
            "size":{
              "width":70,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e73a81a9eff43d291e72b136ee4197e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":900,
                  "y":160},
                "size":{
                  "width":70,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u22.png"}},
{
          "id":"7118647d2436499786033a35616482c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":199},
            "size":{
              "width":550,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ac06a4105684879ab7aba2e980bb19e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":199},
                "size":{
                  "width":550,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u14.png"}},
{
          "id":"9d5ea69effa04d5a93e1e508ad911ac6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":199},
            "size":{
              "width":40,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"487380edf79844489d8c0b36109755ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":199},
                "size":{
                  "width":40,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u18.png"}},
{
          "id":"f8cc554a1d354f92bbc17d1a1ddb414f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":199},
            "size":{
              "width":60,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adf3158a3f12489281af4a86e4803f7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":199},
                "size":{
                  "width":60,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u20.png"}},
{
          "id":"b4f7ad5d3a794afe82abaccc677590e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":199},
            "size":{
              "width":70,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e790cae0935457d91ecb3b38a667587",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":199},
                "size":{
                  "width":70,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u22.png"}},
{
          "id":"8e57834c4ae74bd0a0ab6fbc9cfc035d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":199},
            "size":{
              "width":90,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc6e75bd598a4eb6840a5fdf7c0bb42e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":199},
                "size":{
                  "width":90,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u24.png"}},
{
          "id":"ff8ab0e9ecb64b08a215f5e3ed17057d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":675,
              "y":199},
            "size":{
              "width":45,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d72764e55ceb49e58d1ba68459c1c892",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":675,
                  "y":199},
                "size":{
                  "width":45,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u26.png"}},
{
          "id":"b20ca5e77f124f1faf41dd814cee682c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":720,
              "y":199},
            "size":{
              "width":180,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9f7ced139334653ae713d7544ebe434",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":720,
                  "y":199},
                "size":{
                  "width":180,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u28.png"}},
{
          "id":"b24e410786f445f3b5f5fc4c3e1982c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":900,
              "y":199},
            "size":{
              "width":70,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ea2421653f449ceaa4bfe18c240a227",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":900,
                  "y":199},
                "size":{
                  "width":70,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u22.png"}},
{
          "id":"23c3d95713014ccebbb23fe22a87aa1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":238},
            "size":{
              "width":550,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c0c2eedf741468187032b3564d762bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":238},
                "size":{
                  "width":550,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u14.png"}},
{
          "id":"b9d8e91eb454478d9439b27f95ef0e13",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":238},
            "size":{
              "width":40,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53a0429cd0484dba937eac2aee29e08d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":238},
                "size":{
                  "width":40,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u18.png"}},
{
          "id":"767406e36004490a82d86bf516ccd237",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":238},
            "size":{
              "width":60,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb2778a2d0db42f8be59821f98524049",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":238},
                "size":{
                  "width":60,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u20.png"}},
{
          "id":"3780b2ef4e494e90bf2df1c0b9e1e21a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":238},
            "size":{
              "width":70,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e372ae2738984fba9023ca1d99f43f88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":238},
                "size":{
                  "width":70,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u22.png"}},
{
          "id":"d5a2dc67b5e447b0af1cf1a15eef5df3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":238},
            "size":{
              "width":90,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df781014871547539014ed20fd5e7492",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":238},
                "size":{
                  "width":90,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u24.png"}},
{
          "id":"3dd5ff7488824d578594f5d305823f33",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":675,
              "y":238},
            "size":{
              "width":45,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a6471cae6a6455782ccf3c187cbacf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":675,
                  "y":238},
                "size":{
                  "width":45,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u26.png"}},
{
          "id":"ba7c155314e6426e87408c64cca9a034",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":720,
              "y":238},
            "size":{
              "width":180,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55c35e67df8e4de39f684bf18b4f26df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":720,
                  "y":238},
                "size":{
                  "width":180,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u28.png"}},
{
          "id":"8cff15b3da1e4ad392031592b23782f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":900,
              "y":238},
            "size":{
              "width":70,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2cbc10a7d37842a48205f34ec8fdbd12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":900,
                  "y":238},
                "size":{
                  "width":70,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u22.png"}},
{
          "id":"a4ad7b2549784637a235db8e51011686",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":277},
            "size":{
              "width":550,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e9fb53e9e124a3aab0345684468356f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":277},
                "size":{
                  "width":550,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u14.png"}},
{
          "id":"b1af31c89e04430591ab6a4094f5e2b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":277},
            "size":{
              "width":40,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c32b57566f504915a763926dd9636992",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":277},
                "size":{
                  "width":40,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u18.png"}},
{
          "id":"c60764eda690401589497e9af284df02",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":277},
            "size":{
              "width":60,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd286fb50549466c998a375b23d6ad13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":277},
                "size":{
                  "width":60,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u20.png"}},
{
          "id":"c0746c711f464e3fa96351b6023b1006",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":277},
            "size":{
              "width":70,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdfe76bc011a4698973cc73423785af9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":277},
                "size":{
                  "width":70,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u22.png"}},
{
          "id":"89e682f1bf2748a3b6820188b60cabc9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":277},
            "size":{
              "width":90,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5339fe25b8d44103871a911b026104ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":277},
                "size":{
                  "width":90,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u24.png"}},
{
          "id":"d8100ce487ee46bda65cbd783152bda2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":675,
              "y":277},
            "size":{
              "width":45,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15643cf893e3473099ada226b9edd8e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":675,
                  "y":277},
                "size":{
                  "width":45,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u26.png"}},
{
          "id":"a4b7ffb5d59049e5b716a7f3cd40a2bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":720,
              "y":277},
            "size":{
              "width":180,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50e5a1ce08114934a14d37d52af78e34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":720,
                  "y":277},
                "size":{
                  "width":180,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u28.png"}},
{
          "id":"a8f423ba0e52446eab0f52b59444ea02",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":900,
              "y":277},
            "size":{
              "width":70,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6391b37fae9a4ce2b94d432a13358fc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":900,
                  "y":277},
                "size":{
                  "width":70,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u22.png"}},
{
          "id":"f9a13e5edb9340998d5aff445967c09f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":316},
            "size":{
              "width":550,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c588d3f444a4478af52a4db8486e7b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":316},
                "size":{
                  "width":550,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u14.png"}},
{
          "id":"2306a4924c7445328b3cc8a823e5cf5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":316},
            "size":{
              "width":40,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"951a3c93d1fc495bb9bc1be99e1131ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":316},
                "size":{
                  "width":40,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u18.png"}},
{
          "id":"9e223635b9064cc2981ab692409ce8d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":316},
            "size":{
              "width":60,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2371392f25294423803e1413f683a88c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":316},
                "size":{
                  "width":60,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u20.png"}},
{
          "id":"f7296810750746f0b3bdaa96d0f437be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":316},
            "size":{
              "width":70,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2c7f21931ba4b01b7496ba70d0c6d51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":316},
                "size":{
                  "width":70,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u22.png"}},
{
          "id":"5cd607e8300a4231b77cfef689ab2a88",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":316},
            "size":{
              "width":90,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"658839f8db664684808f6a7dc4d283c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":316},
                "size":{
                  "width":90,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u24.png"}},
{
          "id":"a5d1aaf4586a4147b5bf6f146c54669a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":675,
              "y":316},
            "size":{
              "width":45,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9d86764e4b944cf94d95de23b154d92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":675,
                  "y":316},
                "size":{
                  "width":45,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u26.png"}},
{
          "id":"66c4ad0445ab40b1a28d4cbcbcf88a40",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":720,
              "y":316},
            "size":{
              "width":180,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c48fabe30edf4186b8f13b59d74bb9a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":720,
                  "y":316},
                "size":{
                  "width":180,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u28.png"}},
{
          "id":"a962fd0ca52743958b3c708f95b8ede4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":900,
              "y":316},
            "size":{
              "width":70,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27b9bbc19d0a44d3a6b6c5f8d18a8a56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":900,
                  "y":316},
                "size":{
                  "width":70,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u22.png"}},
{
          "id":"2338f9f69c784ecc9aff55dc755828ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":355},
            "size":{
              "width":550,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6c028db6377431c964eece81512ddc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":355},
                "size":{
                  "width":550,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u14.png"}},
{
          "id":"23ba2ec3173d424b82c9d8e09c1da796",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":355},
            "size":{
              "width":40,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45e6e0ae7479466c987a9be3c855f126",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":355},
                "size":{
                  "width":40,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u18.png"}},
{
          "id":"59fcd52d87fe4377b429722ce7e717ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":355},
            "size":{
              "width":60,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f21bd5b226e54a9390f19056015535b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":355},
                "size":{
                  "width":60,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u20.png"}},
{
          "id":"f0cf4cbbf6544d60839646b7dce8cd09",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":355},
            "size":{
              "width":70,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09ffaa2bf3bd41c49b3c7f1e3c20794e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":355},
                "size":{
                  "width":70,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u22.png"}},
{
          "id":"9b8646d556034f2389b343550f767ec5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":355},
            "size":{
              "width":90,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d575df602c1f4358a42e33091f4b744f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":355},
                "size":{
                  "width":90,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u24.png"}},
{
          "id":"30bb6f0fde1247649b25e706dcdb2bc4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":675,
              "y":355},
            "size":{
              "width":45,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9caf8e154d1d40af9ca46ab3ec88db5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":675,
                  "y":355},
                "size":{
                  "width":45,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u26.png"}},
{
          "id":"9c826bd922b84b49abc09cfc6df81c3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":720,
              "y":355},
            "size":{
              "width":180,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0abebae0bfc24af2828ec565a479088f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":720,
                  "y":355},
                "size":{
                  "width":180,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u28.png"}},
{
          "id":"5c1433b144fb4baf9def7ca3b9e2562f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":900,
              "y":355},
            "size":{
              "width":70,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78eb380a269148e7abc170042c6f5457",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":900,
                  "y":355},
                "size":{
                  "width":70,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u22.png"}},
{
          "id":"518e00f5c0b44921b0f88865acc417b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":394},
            "size":{
              "width":550,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6916c639d7294eb8b5605c8f6eebd7c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":394},
                "size":{
                  "width":550,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u14.png"}},
{
          "id":"6c03b8ba71e74c069419598967fe730a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":394},
            "size":{
              "width":40,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09e86e2d7214458bb97f353cb2392092",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":394},
                "size":{
                  "width":40,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u18.png"}},
{
          "id":"e1ef9f09c7c8486e856e54a6fdd555b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":394},
            "size":{
              "width":60,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2923261dfd6e48f7bc7bbe5db62a8627",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":394},
                "size":{
                  "width":60,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u20.png"}},
{
          "id":"22277bbfc9904c55bb718e8ec97e149d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":394},
            "size":{
              "width":70,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f22c06ba40174a8a9508a7670935b614",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":394},
                "size":{
                  "width":70,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u22.png"}},
{
          "id":"0b8a6d1f00d7422485dcada5110a085a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":394},
            "size":{
              "width":90,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b937cda841b46f3b0cebe759076d877",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":394},
                "size":{
                  "width":90,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u24.png"}},
{
          "id":"40dfc30a58da4b5096c2fa5443432b7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":675,
              "y":394},
            "size":{
              "width":45,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29b5f0cd252548c0b209a7f2b5e4b7bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":675,
                  "y":394},
                "size":{
                  "width":45,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u26.png"}},
{
          "id":"7b738ad2f5c04c18b5426c324187c7b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":720,
              "y":394},
            "size":{
              "width":180,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6bea88719674f49b3926c68dc3c413d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":720,
                  "y":394},
                "size":{
                  "width":180,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u28.png"}},
{
          "id":"e99a822c32214942af56e63e2bca8053",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":900,
              "y":394},
            "size":{
              "width":70,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bda60f29a864c11914b41010101fbc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":900,
                  "y":394},
                "size":{
                  "width":70,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动管理/u22.png"}},
{
          "id":"d3144a47237f4a0ba8b347387181c155",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"26px",
            "location":{
              "x":210,
              "y":20},
            "size":{
              "width":760,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"331a403b066f451b9a4c43e804efb1ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"26px",
                "location":{
                  "x":210,
                  "y":20},
                "size":{
                  "width":760,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/后台/u4.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "ff67cfa3550f4fae8f97c574aa70647f":{
      "scriptId":"u0"},
    "96e762bad7f74d78aa25fcdfa29eb1f1":{
      "scriptId":"u1"},
    "a44144f98d6b4b969a678e725d69e0c4":{
      "scriptId":"u2"},
    "372206bd3c784346ac9e9b111fd7c8f3":{
      "scriptId":"u3"},
    "379100902ef74de88bf139d005cb932d":{
      "scriptId":"u4"},
    "58f89fd3f4cd404fa6441fa7d794b9f8":{
      "scriptId":"u5"},
    "04e6b1d85acb42ec884e06e2261cb2f2":{
      "scriptId":"u6"},
    "37a9dd5fb55645be9528fbdb315c5f19":{
      "scriptId":"u7"},
    "15743cfa51eb4d91a4a9271dd4dbd822":{
      "scriptId":"u8"},
    "ce49fd90f61444dbb0077e27a1453388":{
      "scriptId":"u9"},
    "950691f465ae4630926fddeb2ca00e23":{
      "scriptId":"u10"},
    "e74786660bdb4dfe83592becc4d85aef":{
      "scriptId":"u11"},
    "1c168139ed9d4594a21983921a454865":{
      "scriptId":"u12"},
    "ffe765210b7c4812966e1907b98741a7":{
      "scriptId":"u13"},
    "06dbdd7cd5b74602a47a1bc24366e398":{
      "scriptId":"u14"},
    "68ea2bd88eaf48878f037fc2b5377a38":{
      "scriptId":"u15"},
    "4d320445d64e4636b04ad6144aa48540":{
      "scriptId":"u16"},
    "77a2410b801d41d58b3804d0125d15c8":{
      "scriptId":"u17"},
    "fed2494191624419a94dbbd3d1baf5dc":{
      "scriptId":"u18"},
    "422a5aec26bd4defb6c0fd4e0512348a":{
      "scriptId":"u19"},
    "600e92ce7cc24dba8dfb0bd8eedb4ee0":{
      "scriptId":"u20"},
    "d0af5eca54de4215ae81bbfca0a1e9b0":{
      "scriptId":"u21"},
    "20c524675a5542d78e2ea9d577f9f330":{
      "scriptId":"u22"},
    "092f48833ac44031990384cc0afffe4a":{
      "scriptId":"u23"},
    "549ed2781a824b20bbc3608c2330b0a1":{
      "scriptId":"u24"},
    "31bf03e99b7c4c5c80a7aba2d6d4075f":{
      "scriptId":"u25"},
    "dbd8b3e12d094caf9b7307e62551974d":{
      "scriptId":"u26"},
    "cd5af7edca4b43b193a29573127ad3d6":{
      "scriptId":"u27"},
    "7641350a1fea460cb7bcf9b015e91413":{
      "scriptId":"u28"},
    "8393c132af2c4dcd8c425a02897e6385":{
      "scriptId":"u29"},
    "f28f5992f1ef4933b43253597ca32348":{
      "scriptId":"u30"},
    "73c71b544c7c4350b7862dc0cb729913":{
      "scriptId":"u31"},
    "6d0587eb7e0a48daafcd103f5ed71058":{
      "scriptId":"u32"},
    "ddea55e4caf242f6b2d0a2d0428c6cd9":{
      "scriptId":"u33"},
    "154370796d1448bca9b602fcdb8318c7":{
      "scriptId":"u34"},
    "6aec9e28086849d59c2c568e4e5eb5db":{
      "scriptId":"u35"},
    "6ce2a704a3864b03affc12bc2e0bced0":{
      "scriptId":"u36"},
    "46dbd910663a4706bb29e4ce11378208":{
      "scriptId":"u37"},
    "3aeaaa79319d4a4b9d7303857f7ac2f8":{
      "scriptId":"u38"},
    "94405587f85540d1853e80cf30aa13db":{
      "scriptId":"u39"},
    "6a661b1b0a5f4bc6969bb63b8e9fe9a3":{
      "scriptId":"u40"},
    "2aee7660a9244d6ca24e77543b659e0c":{
      "scriptId":"u41"},
    "343d2f6fd0e64e31ae4050a8434442cd":{
      "scriptId":"u42"},
    "c1f104b47c7f4074b8fc26f86b647b78":{
      "scriptId":"u43"},
    "b648d9b659a4481d91f04fe66c963574":{
      "scriptId":"u44"},
    "dab2894c3aa64b4c9561cbae8418d92d":{
      "scriptId":"u45"},
    "15bb3c626f1140e982d3cd916b23b9e0":{
      "scriptId":"u46"},
    "0e73a81a9eff43d291e72b136ee4197e":{
      "scriptId":"u47"},
    "7118647d2436499786033a35616482c9":{
      "scriptId":"u48"},
    "2ac06a4105684879ab7aba2e980bb19e":{
      "scriptId":"u49"},
    "9d5ea69effa04d5a93e1e508ad911ac6":{
      "scriptId":"u50"},
    "487380edf79844489d8c0b36109755ba":{
      "scriptId":"u51"},
    "f8cc554a1d354f92bbc17d1a1ddb414f":{
      "scriptId":"u52"},
    "adf3158a3f12489281af4a86e4803f7d":{
      "scriptId":"u53"},
    "b4f7ad5d3a794afe82abaccc677590e4":{
      "scriptId":"u54"},
    "8e790cae0935457d91ecb3b38a667587":{
      "scriptId":"u55"},
    "8e57834c4ae74bd0a0ab6fbc9cfc035d":{
      "scriptId":"u56"},
    "cc6e75bd598a4eb6840a5fdf7c0bb42e":{
      "scriptId":"u57"},
    "ff8ab0e9ecb64b08a215f5e3ed17057d":{
      "scriptId":"u58"},
    "d72764e55ceb49e58d1ba68459c1c892":{
      "scriptId":"u59"},
    "b20ca5e77f124f1faf41dd814cee682c":{
      "scriptId":"u60"},
    "a9f7ced139334653ae713d7544ebe434":{
      "scriptId":"u61"},
    "b24e410786f445f3b5f5fc4c3e1982c3":{
      "scriptId":"u62"},
    "1ea2421653f449ceaa4bfe18c240a227":{
      "scriptId":"u63"},
    "23c3d95713014ccebbb23fe22a87aa1e":{
      "scriptId":"u64"},
    "6c0c2eedf741468187032b3564d762bd":{
      "scriptId":"u65"},
    "b9d8e91eb454478d9439b27f95ef0e13":{
      "scriptId":"u66"},
    "53a0429cd0484dba937eac2aee29e08d":{
      "scriptId":"u67"},
    "767406e36004490a82d86bf516ccd237":{
      "scriptId":"u68"},
    "cb2778a2d0db42f8be59821f98524049":{
      "scriptId":"u69"},
    "3780b2ef4e494e90bf2df1c0b9e1e21a":{
      "scriptId":"u70"},
    "e372ae2738984fba9023ca1d99f43f88":{
      "scriptId":"u71"},
    "d5a2dc67b5e447b0af1cf1a15eef5df3":{
      "scriptId":"u72"},
    "df781014871547539014ed20fd5e7492":{
      "scriptId":"u73"},
    "3dd5ff7488824d578594f5d305823f33":{
      "scriptId":"u74"},
    "4a6471cae6a6455782ccf3c187cbacf8":{
      "scriptId":"u75"},
    "ba7c155314e6426e87408c64cca9a034":{
      "scriptId":"u76"},
    "55c35e67df8e4de39f684bf18b4f26df":{
      "scriptId":"u77"},
    "8cff15b3da1e4ad392031592b23782f5":{
      "scriptId":"u78"},
    "2cbc10a7d37842a48205f34ec8fdbd12":{
      "scriptId":"u79"},
    "a4ad7b2549784637a235db8e51011686":{
      "scriptId":"u80"},
    "1e9fb53e9e124a3aab0345684468356f":{
      "scriptId":"u81"},
    "b1af31c89e04430591ab6a4094f5e2b3":{
      "scriptId":"u82"},
    "c32b57566f504915a763926dd9636992":{
      "scriptId":"u83"},
    "c60764eda690401589497e9af284df02":{
      "scriptId":"u84"},
    "bd286fb50549466c998a375b23d6ad13":{
      "scriptId":"u85"},
    "c0746c711f464e3fa96351b6023b1006":{
      "scriptId":"u86"},
    "cdfe76bc011a4698973cc73423785af9":{
      "scriptId":"u87"},
    "89e682f1bf2748a3b6820188b60cabc9":{
      "scriptId":"u88"},
    "5339fe25b8d44103871a911b026104ad":{
      "scriptId":"u89"},
    "d8100ce487ee46bda65cbd783152bda2":{
      "scriptId":"u90"},
    "15643cf893e3473099ada226b9edd8e0":{
      "scriptId":"u91"},
    "a4b7ffb5d59049e5b716a7f3cd40a2bd":{
      "scriptId":"u92"},
    "50e5a1ce08114934a14d37d52af78e34":{
      "scriptId":"u93"},
    "a8f423ba0e52446eab0f52b59444ea02":{
      "scriptId":"u94"},
    "6391b37fae9a4ce2b94d432a13358fc5":{
      "scriptId":"u95"},
    "f9a13e5edb9340998d5aff445967c09f":{
      "scriptId":"u96"},
    "1c588d3f444a4478af52a4db8486e7b0":{
      "scriptId":"u97"},
    "2306a4924c7445328b3cc8a823e5cf5f":{
      "scriptId":"u98"},
    "951a3c93d1fc495bb9bc1be99e1131ac":{
      "scriptId":"u99"},
    "9e223635b9064cc2981ab692409ce8d9":{
      "scriptId":"u100"},
    "2371392f25294423803e1413f683a88c":{
      "scriptId":"u101"},
    "f7296810750746f0b3bdaa96d0f437be":{
      "scriptId":"u102"},
    "c2c7f21931ba4b01b7496ba70d0c6d51":{
      "scriptId":"u103"},
    "5cd607e8300a4231b77cfef689ab2a88":{
      "scriptId":"u104"},
    "658839f8db664684808f6a7dc4d283c0":{
      "scriptId":"u105"},
    "a5d1aaf4586a4147b5bf6f146c54669a":{
      "scriptId":"u106"},
    "b9d86764e4b944cf94d95de23b154d92":{
      "scriptId":"u107"},
    "66c4ad0445ab40b1a28d4cbcbcf88a40":{
      "scriptId":"u108"},
    "c48fabe30edf4186b8f13b59d74bb9a6":{
      "scriptId":"u109"},
    "a962fd0ca52743958b3c708f95b8ede4":{
      "scriptId":"u110"},
    "27b9bbc19d0a44d3a6b6c5f8d18a8a56":{
      "scriptId":"u111"},
    "2338f9f69c784ecc9aff55dc755828ec":{
      "scriptId":"u112"},
    "b6c028db6377431c964eece81512ddc0":{
      "scriptId":"u113"},
    "23ba2ec3173d424b82c9d8e09c1da796":{
      "scriptId":"u114"},
    "45e6e0ae7479466c987a9be3c855f126":{
      "scriptId":"u115"},
    "59fcd52d87fe4377b429722ce7e717ff":{
      "scriptId":"u116"},
    "f21bd5b226e54a9390f19056015535b7":{
      "scriptId":"u117"},
    "f0cf4cbbf6544d60839646b7dce8cd09":{
      "scriptId":"u118"},
    "09ffaa2bf3bd41c49b3c7f1e3c20794e":{
      "scriptId":"u119"},
    "9b8646d556034f2389b343550f767ec5":{
      "scriptId":"u120"},
    "d575df602c1f4358a42e33091f4b744f":{
      "scriptId":"u121"},
    "30bb6f0fde1247649b25e706dcdb2bc4":{
      "scriptId":"u122"},
    "9caf8e154d1d40af9ca46ab3ec88db5a":{
      "scriptId":"u123"},
    "9c826bd922b84b49abc09cfc6df81c3d":{
      "scriptId":"u124"},
    "0abebae0bfc24af2828ec565a479088f":{
      "scriptId":"u125"},
    "5c1433b144fb4baf9def7ca3b9e2562f":{
      "scriptId":"u126"},
    "78eb380a269148e7abc170042c6f5457":{
      "scriptId":"u127"},
    "518e00f5c0b44921b0f88865acc417b1":{
      "scriptId":"u128"},
    "6916c639d7294eb8b5605c8f6eebd7c9":{
      "scriptId":"u129"},
    "6c03b8ba71e74c069419598967fe730a":{
      "scriptId":"u130"},
    "09e86e2d7214458bb97f353cb2392092":{
      "scriptId":"u131"},
    "e1ef9f09c7c8486e856e54a6fdd555b5":{
      "scriptId":"u132"},
    "2923261dfd6e48f7bc7bbe5db62a8627":{
      "scriptId":"u133"},
    "22277bbfc9904c55bb718e8ec97e149d":{
      "scriptId":"u134"},
    "f22c06ba40174a8a9508a7670935b614":{
      "scriptId":"u135"},
    "0b8a6d1f00d7422485dcada5110a085a":{
      "scriptId":"u136"},
    "1b937cda841b46f3b0cebe759076d877":{
      "scriptId":"u137"},
    "40dfc30a58da4b5096c2fa5443432b7c":{
      "scriptId":"u138"},
    "29b5f0cd252548c0b209a7f2b5e4b7bd":{
      "scriptId":"u139"},
    "7b738ad2f5c04c18b5426c324187c7b0":{
      "scriptId":"u140"},
    "a6bea88719674f49b3926c68dc3c413d":{
      "scriptId":"u141"},
    "e99a822c32214942af56e63e2bca8053":{
      "scriptId":"u142"},
    "5bda60f29a864c11914b41010101fbc4":{
      "scriptId":"u143"},
    "d3144a47237f4a0ba8b347387181c155":{
      "scriptId":"u144"},
    "331a403b066f451b9a4c43e804efb1ae":{
      "scriptId":"u145"}}});