$axure.loadCurrentPage({
  "url":"首页.html",
  "generationDate":new Date(1495848946616.33),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"text_keyword"],
  "page":{
    "packageId":"c359e16dd0e5463199b9882aa46655f5",
    "type":"Axure:Page",
    "name":"首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7ffb81e411db487884e10e3825357222",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":120,
              "y":42},
            "size":{
              "width":480,
              "height":788}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abeed07deb05424782b4fced4a05437a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":120,
                  "y":42},
                "size":{
                  "width":480,
                  "height":788}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"dbc185effba64580bbe87c26ff210a1a",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":42},
            "size":{
              "width":480,
              "height":728}},
          "adaptiveStyles":{
}},
{
          "id":"cf2f3ad75e064b468cbd73f45b7e7978",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "stateStyles":{
              "hint":{
                "fontStyle":"italic"}},
            "location":{
              "x":126,
              "y":50},
            "size":{
              "width":344,
              "height":50}},
          "adaptiveStyles":{
},
          "submitButton":{
            "path":[],
            "id":"4a4072d8397449fea9b3c637786c5c5c"},
          "interactionMap":{
            "onFocus":{
              "description":"OnFocus",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 搜索 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"搜索.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "placeholderText":"         搜索"},
{
          "id":"0317e776f12949ff8bc9bba376e70fce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":120,
              "y":765},
            "size":{
              "width":160,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ef8f2d7bd2d426c8f0102a633afdfa5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":120,
                  "y":765},
                "size":{
                  "width":160,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 附近 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"附近.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"df418c3df4a64f3ea6863b125479f2b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":280,
              "y":765},
            "size":{
              "width":160,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21c9d79636ac4c9497099e11b0902c2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":280,
                  "y":765},
                "size":{
                  "width":160,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 路线 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"路线.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u6.png"}},
{
          "id":"c0915af2dbcd4923883b11b4af3e00c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":440,
              "y":765},
            "size":{
              "width":160,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bac9203b47574a1e8a05a47adf3cc103",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":440,
                  "y":765},
                "size":{
                  "width":160,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 景点 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"景点.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u8.png"}},
{
          "id":"4a4072d8397449fea9b3c637786c5c5c",
          "label":"搜索按钮",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":126,
              "y":58},
            "size":{
              "width":38,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60f7c27674bc40a8b14d6a12eea5d844",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":126,
                  "y":58},
                "size":{
                  "width":38,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/搜索按钮_u10.png"}},
{
          "id":"3b6619fcf7e745eba6783f7aa88d7331",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":106},
            "size":{
              "width":39,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3d50b48bb3f4276b624f49019486672",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":106},
                "size":{
                  "width":39,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u12.png"}},
{
          "id":"6d47c32755f7471fa89a107f6c6a0fa6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":144,
              "y":778},
            "size":{
              "width":39,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"131ef371bbb44f2e823b4a784170a52c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":144,
                  "y":778},
                "size":{
                  "width":39,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u14.png"}},
{
          "id":"4f446095c7ab4014bde6c9d0065c09da",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":303,
              "y":778},
            "size":{
              "width":39,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e54f9e272e245b3a15544970d0b38b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":303,
                  "y":778},
                "size":{
                  "width":39,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u16.png"}},
{
          "id":"e83f4c83377b42d2b7482b5fd6547a8e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":778},
            "size":{
              "width":50,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76f9a6b516984113867cceaee348cb2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":778},
                "size":{
                  "width":50,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u18.png"}},
{
          "id":"afa1c8589c41437db2968a608b88f7fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":750,
              "y":75},
            "size":{
              "width":841,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"387df20d2f06476da6fa46ca479279e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":750,
                  "y":75},
                "size":{
                  "width":841,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e30eac4982ac47759606bf060709d98f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":544,
              "y":145},
            "size":{
              "width":52,
              "height":89}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e098281bd1ad4f008391d1c2ce1d345f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":544,
                  "y":145},
                "size":{
                  "width":52,
                  "height":89}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "7ffb81e411db487884e10e3825357222":{
      "scriptId":"u0"},
    "abeed07deb05424782b4fced4a05437a":{
      "scriptId":"u1"},
    "dbc185effba64580bbe87c26ff210a1a":{
      "scriptId":"u2"},
    "cf2f3ad75e064b468cbd73f45b7e7978":{
      "scriptId":"u3"},
    "0317e776f12949ff8bc9bba376e70fce":{
      "scriptId":"u4"},
    "8ef8f2d7bd2d426c8f0102a633afdfa5":{
      "scriptId":"u5"},
    "df418c3df4a64f3ea6863b125479f2b1":{
      "scriptId":"u6"},
    "21c9d79636ac4c9497099e11b0902c2b":{
      "scriptId":"u7"},
    "c0915af2dbcd4923883b11b4af3e00c8":{
      "scriptId":"u8"},
    "bac9203b47574a1e8a05a47adf3cc103":{
      "scriptId":"u9"},
    "4a4072d8397449fea9b3c637786c5c5c":{
      "scriptId":"u10"},
    "60f7c27674bc40a8b14d6a12eea5d844":{
      "scriptId":"u11"},
    "3b6619fcf7e745eba6783f7aa88d7331":{
      "scriptId":"u12"},
    "d3d50b48bb3f4276b624f49019486672":{
      "scriptId":"u13"},
    "6d47c32755f7471fa89a107f6c6a0fa6":{
      "scriptId":"u14"},
    "131ef371bbb44f2e823b4a784170a52c":{
      "scriptId":"u15"},
    "4f446095c7ab4014bde6c9d0065c09da":{
      "scriptId":"u16"},
    "6e54f9e272e245b3a15544970d0b38b5":{
      "scriptId":"u17"},
    "e83f4c83377b42d2b7482b5fd6547a8e":{
      "scriptId":"u18"},
    "76f9a6b516984113867cceaee348cb2e":{
      "scriptId":"u19"},
    "afa1c8589c41437db2968a608b88f7fb":{
      "scriptId":"u20"},
    "387df20d2f06476da6fa46ca479279e6":{
      "scriptId":"u21"},
    "e30eac4982ac47759606bf060709d98f":{
      "scriptId":"u22"},
    "e098281bd1ad4f008391d1c2ce1d345f":{
      "scriptId":"u23"}}});