$axure.loadCurrentPage({
  "url":"搜索.html",
  "generationDate":new Date(1495872720940.03),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"text_keyword"],
  "page":{
    "packageId":"56dec632c7e6465a8d3a1f7b51e6e738",
    "type":"Axure:Page",
    "name":"搜索",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"Case 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"fadeWidget",
                "description":"Hide hint_window/(Shape),<br>hint_window/(Shape),<br>close_null_hint_btn",
                "objectsToFades":[{
                    "objectPath":["6aa8113eef4a4e9c8a711fe4aadc5f37",
"fe4a0d2580ee4fe79f75517a2113116e"],
                    "fadeInfo":{
                      "fadeType":"hide",
                      "options":{
                        "showType":"none"}}},
{
                    "objectPath":["6aa8113eef4a4e9c8a711fe4aadc5f37",
"fc351c4556bb4adfad171d264e1ee1b9"],
                    "fadeInfo":{
                      "fadeType":"hide",
                      "options":{
                        "showType":"none"}}},
{
                    "objectPath":["6579e6c7b9cf4fcdb3ea1eb5e07ebefa"],
                    "fadeInfo":{
                      "fadeType":"hide",
                      "options":{
                        "showType":"none"}}}]}]}]}},
    "diagram":{
      "objects":[{
          "id":"03d569d4259448fdb6f03be794c95e36",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":80,
              "y":50},
            "size":{
              "width":480,
              "height":800}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7d1d1af70294117b3614d8eb7db81a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":80,
                  "y":50},
                "size":{
                  "width":480,
                  "height":800}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/附近/u0.png"}},
{
          "id":"9e0c573ad7cb40198fcd43369f43347e",
          "label":"input_keyword",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "stateStyles":{
              "hint":{
                "fontStyle":"italic"}},
            "location":{
              "x":157,
              "y":59},
            "size":{
              "width":375,
              "height":51}},
          "adaptiveStyles":{
},
          "submitButton":{
            "path":[],
            "id":"5f48d31ad4454e7fa9ad7e86c66aecae"},
          "placeholderText":""},
{
          "id":"11cbd5643e4b47b888884e3887ac2f87",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":97,
              "y":67},
            "size":{
              "width":36,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93739182a6b64e0892cc47b1e56de17d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":97,
                  "y":67},
                "size":{
                  "width":36,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 导航模块 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"导航模块.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/附近/u3.png"}},
{
          "id":"5f48d31ad4454e7fa9ad7e86c66aecae",
          "label":"search_keyword_btn",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":483,
              "y":69},
            "size":{
              "width":36,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c09a0328efbc44c892e3f56b5fe62d7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":483,
                  "y":69},
                "size":{
                  "width":36,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1<br> (If True)",
                  "isNewIfGroup":true,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set value of text_keyword equal to text on input_keyword",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"text_keyword"},
{
                                "exprType":"fcall",
                                "functionName":"GetWidgetText",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["9e0c573ad7cb40198fcd43369f43347e"]}]}]}]}}]},
{
                  "description":"Case 2<br> (If text on input_keyword equals &quot;关键字&quot;)",
                  "isNewIfGroup":true,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["9e0c573ad7cb40198fcd43369f43347e"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"关键字",
                      "stos":[]}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show hint_window/(Shape),<br>hint_window/(Shape),<br>close_null_hint_btn",
                      "objectsToFades":[{
                          "objectPath":["6aa8113eef4a4e9c8a711fe4aadc5f37",
"fc351c4556bb4adfad171d264e1ee1b9"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["6aa8113eef4a4e9c8a711fe4aadc5f37",
"fe4a0d2580ee4fe79f75517a2113116e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["6579e6c7b9cf4fcdb3ea1eb5e07ebefa"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]},
{
                  "description":"Case 3<br> (Else If text on input_keyword equals &quot;青城山&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["9e0c573ad7cb40198fcd43369f43347e"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"青城山",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 搜索结果-青城山 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"搜索结果-青城山.html",
                        "includeVariables":true},
                      "linkType":"current"}]},
{
                  "description":"Case 4<br> (Else If text on input_keyword equals &quot;欢乐谷&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["9e0c573ad7cb40198fcd43369f43347e"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"欢乐谷",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 搜索结果-欢乐谷 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"搜索结果-欢乐谷.html",
                        "includeVariables":true},
                      "linkType":"current"}]},
{
                  "description":"Case 5<br> (Else If text on input_keyword does not equal &quot;关键字&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"!=",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["9e0c573ad7cb40198fcd43369f43347e"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"关键字",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 搜索结果-没有找到 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"搜索结果-没有找到.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/附近/near_search_btn_u5.png"}},
{
          "id":"d69749ee683049f9b6cb09b2aa3826fe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":108,
              "y":150},
            "size":{
              "width":71,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7440fd709b2d4e0c9f8552d47ea06cf4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":108,
                  "y":150},
                "size":{
                  "width":71,
                  "height":63}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 搜索结果-美食 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"搜索结果-美食.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/附近/u7.png"}},
{
          "id":"2819252a9c5444fa922473e7d65ddeeb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":118,
              "y":222},
            "size":{
              "width":41,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0eb3b977ba84ddebcae247a5ff397f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":118,
                  "y":222},
                "size":{
                  "width":41,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"04e461af5ec54d92ba9d198acd51f94b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":228,
              "y":137},
            "size":{
              "width":69,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af87680b44c04d7b8770bb15042b4b0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":228,
                  "y":137},
                "size":{
                  "width":69,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 搜索结果-酒店 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"搜索结果-酒店.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/附近/u11.png"}},
{
          "id":"efa25e0faf794c2da53ffb254eca3e7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":238,
              "y":220},
            "size":{
              "width":41,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc55bf7312394b8ab1367cdcd20ff5e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":238,
                  "y":220},
                "size":{
                  "width":41,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f29f8f576ca24d68878028282fd695ad",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":350,
              "y":137},
            "size":{
              "width":69,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e282362c296b44278edbbeb53130fa60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":350,
                  "y":137},
                "size":{
                  "width":69,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/附近/u15.png"}},
{
          "id":"1a604ed6ab45478bb187326e3a23c9f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":360,
              "y":220},
            "size":{
              "width":41,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b927595a4bbc401285e76b5605481c2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":360,
                  "y":220},
                "size":{
                  "width":41,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a630d365427c46c3a889f2865f64afa0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":464,
              "y":136},
            "size":{
              "width":69,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df866038e63f4ba7be51a055264a30fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":464,
                  "y":136},
                "size":{
                  "width":69,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/附近/u19.png"}},
{
          "id":"a7aa9aa25f3049feaf15c9723fe8c9bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":477,
              "y":219},
            "size":{
              "width":41,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"deb5951399044148b34020c8f3aa18a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":477,
                  "y":219},
                "size":{
                  "width":41,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd02732e1b6245ee8c8dc34a91d29530",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":108,
              "y":284},
            "size":{
              "width":69,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55f1e007349443a2be08dc475715aa46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":108,
                  "y":284},
                "size":{
                  "width":69,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/附近/u23.png"}},
{
          "id":"8c132e4e22da4c9297a774b6b3430b91",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":120,
              "y":365},
            "size":{
              "width":41,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1806fe9fb1ae4ab382803bc0995da613",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":120,
                  "y":365},
                "size":{
                  "width":41,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db183370eb3746e4a458e38e47b16d44",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":222,
              "y":284},
            "size":{
              "width":69,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f064ba1f89d7494d8b2be71de6f1a6a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":222,
                  "y":284},
                "size":{
                  "width":69,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/附近/u27.png"}},
{
          "id":"a95227471caf4a6dba55c62a73279df3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":228,
              "y":365},
            "size":{
              "width":61,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23f0097955e04f6ca2cb29457e39c0c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":228,
                  "y":365},
                "size":{
                  "width":61,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"03a00ca9d73f461f9649872e4724fad6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":350,
              "y":284},
            "size":{
              "width":69,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a40bdac5fc7d4ce4985e6844cbe493da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":350,
                  "y":284},
                "size":{
                  "width":69,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/附近/u31.png"}},
{
          "id":"f33a78899ecf4197ba7245c42bdc37ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":356,
              "y":365},
            "size":{
              "width":61,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffe66a8906f84903acddf1334fdfcacc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":356,
                  "y":365},
                "size":{
                  "width":61,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b49ac868ff8343e7a8ac39848e9e7681",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":464,
              "y":283},
            "size":{
              "width":69,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c8e72153d7f42678dda196572eed65a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":464,
                  "y":283},
                "size":{
                  "width":69,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/附近/u35.png"}},
{
          "id":"8ca0c13dc54a463b9c4a6b4700b8d1f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":478,
              "y":365},
            "size":{
              "width":41,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"903ceb566b4449769f7f90875ffe96c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":478,
                  "y":365},
                "size":{
                  "width":41,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca55463b238149cd8a80575824a581bb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":425},
            "size":{
              "width":480,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/路线/u8_line.png"}},
{
          "id":"ae5d8bfb2a0a462ca268f196341637f1",
          "label":"serahc_qingchnegshan",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":91,
              "y":540},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 搜索结果-青城山 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"搜索结果-青城山.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"11ddbf28a47b4c30aae85692506072d9",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ec55b6504ff94e268661308e4f14f5ed",
                  "label":"",
                  "parentDynamicPanel":"ae5d8bfb2a0a462ca268f196341637f1",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "size":{
                      "width":48,
                      "height":48}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"323feb8c02f943248e2abf0d0a72a6d4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ae5d8bfb2a0a462ca268f196341637f1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "size":{
                          "width":48,
                          "height":48}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/附近/near_search_btn_u5.png"}},
{
                  "id":"93d78bd325504226a4b5b58b09a5aa35",
                  "label":"",
                  "parentDynamicPanel":"ae5d8bfb2a0a462ca268f196341637f1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":65,
                      "y":9},
                    "size":{
                      "width":61,
                      "height":23}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9534679036bc4272946f620b591a1e26",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ae5d8bfb2a0a462ca268f196341637f1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":65,
                          "y":9},
                        "size":{
                          "width":61,
                          "height":23}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"c5decc6e63ce4c9f83a1fca2db7d752e",
          "label":"search_huanlegu",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":91,
              "y":463},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 搜索结果-欢乐谷 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"搜索结果-欢乐谷.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"184d6c56bf9143b8b5c81342db97df57",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"dc9d4b0f07724e7dac5cc2fdd99276bf",
                  "label":"",
                  "parentDynamicPanel":"c5decc6e63ce4c9f83a1fca2db7d752e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "size":{
                      "width":48,
                      "height":48}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fa189269e97a4e5493b9e702417f2869",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c5decc6e63ce4c9f83a1fca2db7d752e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "size":{
                          "width":48,
                          "height":48}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/附近/near_search_btn_u5.png"}},
{
                  "id":"36581342a137477880de2025262bc311",
                  "label":"",
                  "parentDynamicPanel":"c5decc6e63ce4c9f83a1fca2db7d752e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":65,
                      "y":10},
                    "size":{
                      "width":61,
                      "height":23}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eec89d65acef4428879ebf132650f1a4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c5decc6e63ce4c9f83a1fca2db7d752e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":65,
                          "y":10},
                        "size":{
                          "width":61,
                          "height":23}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"f8f7fed3a4274067b479a67b3c316ada",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":608,
              "y":69},
            "size":{
              "width":552,
              "height":111}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6acf97a1e3f4aaf9c5eb25156865d84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":608,
                  "y":69},
                "size":{
                  "width":552,
                  "height":111}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6aa8113eef4a4e9c8a711fe4aadc5f37",
          "label":"hint_window",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":false,
          "style":{
            "location":{
              "x":122,
              "y":233},
            "visible":false},
          "adaptiveStyles":{
},
          "masterId":"65c2341986374274911c60a8bdf15545"},
{
          "id":"6579e6c7b9cf4fcdb3ea1eb5e07ebefa",
          "label":"close_null_hint_btn",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":498,
              "y":242},
            "size":{
              "width":34,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b11c2d96d6d4626bed6ada63ba67bdc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":498,
                  "y":242},
                "size":{
                  "width":34,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Hide This,<br>hint_window/(Shape),<br>hint_window/(Shape),<br>close_null_hint_btn",
                      "objectsToFades":[{
                          "objectPath":["6579e6c7b9cf4fcdb3ea1eb5e07ebefa"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["6aa8113eef4a4e9c8a711fe4aadc5f37",
"fe4a0d2580ee4fe79f75517a2113116e"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["6aa8113eef4a4e9c8a711fe4aadc5f37",
"fc351c4556bb4adfad171d264e1ee1b9"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["6579e6c7b9cf4fcdb3ea1eb5e07ebefa"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/导航/close_win_u29.png"}}]}},
  "masters":{
    "65c2341986374274911c60a8bdf15545":{
      "packageId":"65c2341986374274911c60a8bdf15545",
      "type":"Axure:Master",
      "name":"输入空提醒",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"fc351c4556bb4adfad171d264e1ee1b9",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":410,
                "height":155}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dc709623920140ce88166370a2841c55",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":410,
                    "height":155}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/搜索/u53.png"}},
{
            "id":"fe4a0d2580ee4fe79f75517a2113116e",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "location":{
                "x":138,
                "y":56},
              "size":{
                "width":161,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"599046e659964fc18f905d6bbf3c1937",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "location":{
                    "x":138,
                    "y":56},
                  "size":{
                    "width":161,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "03d569d4259448fdb6f03be794c95e36":{
      "scriptId":"u0"},
    "c7d1d1af70294117b3614d8eb7db81a2":{
      "scriptId":"u1"},
    "9e0c573ad7cb40198fcd43369f43347e":{
      "scriptId":"u2"},
    "11cbd5643e4b47b888884e3887ac2f87":{
      "scriptId":"u3"},
    "93739182a6b64e0892cc47b1e56de17d":{
      "scriptId":"u4"},
    "5f48d31ad4454e7fa9ad7e86c66aecae":{
      "scriptId":"u5"},
    "c09a0328efbc44c892e3f56b5fe62d7e":{
      "scriptId":"u6"},
    "d69749ee683049f9b6cb09b2aa3826fe":{
      "scriptId":"u7"},
    "7440fd709b2d4e0c9f8552d47ea06cf4":{
      "scriptId":"u8"},
    "2819252a9c5444fa922473e7d65ddeeb":{
      "scriptId":"u9"},
    "e0eb3b977ba84ddebcae247a5ff397f7":{
      "scriptId":"u10"},
    "04e461af5ec54d92ba9d198acd51f94b":{
      "scriptId":"u11"},
    "af87680b44c04d7b8770bb15042b4b0e":{
      "scriptId":"u12"},
    "efa25e0faf794c2da53ffb254eca3e7c":{
      "scriptId":"u13"},
    "cc55bf7312394b8ab1367cdcd20ff5e2":{
      "scriptId":"u14"},
    "f29f8f576ca24d68878028282fd695ad":{
      "scriptId":"u15"},
    "e282362c296b44278edbbeb53130fa60":{
      "scriptId":"u16"},
    "1a604ed6ab45478bb187326e3a23c9f3":{
      "scriptId":"u17"},
    "b927595a4bbc401285e76b5605481c2e":{
      "scriptId":"u18"},
    "a630d365427c46c3a889f2865f64afa0":{
      "scriptId":"u19"},
    "df866038e63f4ba7be51a055264a30fd":{
      "scriptId":"u20"},
    "a7aa9aa25f3049feaf15c9723fe8c9bb":{
      "scriptId":"u21"},
    "deb5951399044148b34020c8f3aa18a2":{
      "scriptId":"u22"},
    "dd02732e1b6245ee8c8dc34a91d29530":{
      "scriptId":"u23"},
    "55f1e007349443a2be08dc475715aa46":{
      "scriptId":"u24"},
    "8c132e4e22da4c9297a774b6b3430b91":{
      "scriptId":"u25"},
    "1806fe9fb1ae4ab382803bc0995da613":{
      "scriptId":"u26"},
    "db183370eb3746e4a458e38e47b16d44":{
      "scriptId":"u27"},
    "f064ba1f89d7494d8b2be71de6f1a6a8":{
      "scriptId":"u28"},
    "a95227471caf4a6dba55c62a73279df3":{
      "scriptId":"u29"},
    "23f0097955e04f6ca2cb29457e39c0c5":{
      "scriptId":"u30"},
    "03a00ca9d73f461f9649872e4724fad6":{
      "scriptId":"u31"},
    "a40bdac5fc7d4ce4985e6844cbe493da":{
      "scriptId":"u32"},
    "f33a78899ecf4197ba7245c42bdc37ce":{
      "scriptId":"u33"},
    "ffe66a8906f84903acddf1334fdfcacc":{
      "scriptId":"u34"},
    "b49ac868ff8343e7a8ac39848e9e7681":{
      "scriptId":"u35"},
    "4c8e72153d7f42678dda196572eed65a":{
      "scriptId":"u36"},
    "8ca0c13dc54a463b9c4a6b4700b8d1f2":{
      "scriptId":"u37"},
    "903ceb566b4449769f7f90875ffe96c1":{
      "scriptId":"u38"},
    "ca55463b238149cd8a80575824a581bb":{
      "scriptId":"u39"},
    "ae5d8bfb2a0a462ca268f196341637f1":{
      "scriptId":"u40"},
    "ec55b6504ff94e268661308e4f14f5ed":{
      "scriptId":"u41"},
    "323feb8c02f943248e2abf0d0a72a6d4":{
      "scriptId":"u42"},
    "93d78bd325504226a4b5b58b09a5aa35":{
      "scriptId":"u43"},
    "9534679036bc4272946f620b591a1e26":{
      "scriptId":"u44"},
    "c5decc6e63ce4c9f83a1fca2db7d752e":{
      "scriptId":"u45"},
    "dc9d4b0f07724e7dac5cc2fdd99276bf":{
      "scriptId":"u46"},
    "fa189269e97a4e5493b9e702417f2869":{
      "scriptId":"u47"},
    "36581342a137477880de2025262bc311":{
      "scriptId":"u48"},
    "eec89d65acef4428879ebf132650f1a4":{
      "scriptId":"u49"},
    "f8f7fed3a4274067b479a67b3c316ada":{
      "scriptId":"u50"},
    "b6acf97a1e3f4aaf9c5eb25156865d84":{
      "scriptId":"u51"},
    "6aa8113eef4a4e9c8a711fe4aadc5f37":{
      "scriptId":"u52",
      "fc351c4556bb4adfad171d264e1ee1b9":{
        "scriptId":"u53"},
      "dc709623920140ce88166370a2841c55":{
        "scriptId":"u54"},
      "fe4a0d2580ee4fe79f75517a2113116e":{
        "scriptId":"u55"},
      "599046e659964fc18f905d6bbf3c1937":{
        "scriptId":"u56"}},
    "6579e6c7b9cf4fcdb3ea1eb5e07ebefa":{
      "scriptId":"u57"},
    "2b11c2d96d6d4626bed6ada63ba67bdc":{
      "scriptId":"u58"}}});