$axure.loadCurrentPage({
  "url":"导航.html",
  "generationDate":new Date(1495872720858.9),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"text_keyword"],
  "page":{
    "packageId":"b0a0306e3d3d4156b953ae1df09cf289",
    "type":"Axure:Page",
    "name":"导航",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"93e305ef6c8e44b8be66bc02a45f786e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":20},
            "size":{
              "width":480,
              "height":800}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43dab820de3f47b78ac591f6f6b74a57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":20},
                "size":{
                  "width":480,
                  "height":800}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/附近/u0.png"}},
{
          "id":"92c983e5f2d540829aaf5008a462bdb4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":189},
            "size":{
              "width":480,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/路线/u8_line.png"}},
{
          "id":"6a396a54fa41438a8aebff505a92d6f1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":67,
              "y":56},
            "size":{
              "width":93,
              "height":106}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef508baa6f92497dbb56e74d0a52f974",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":67,
                  "y":56},
                "size":{
                  "width":93,
                  "height":106}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航/u3.png"}},
{
          "id":"c47ff4c8516f4509882d24740e53bbc4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":201,
              "y":63},
            "size":{
              "width":159,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04b8ac6f90fa498bb09ed1af4ba6082e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":201,
                  "y":63},
                "size":{
                  "width":159,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7374e759c55d4b798bd206176dcfaab0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":201,
              "y":115},
            "size":{
              "width":82,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da0fe50a0c71445eb9d92c6099f25333",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":201,
                  "y":115},
                "size":{
                  "width":82,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"75282385b49249c79fe0e6fe007b7c00",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":212},
            "size":{
              "width":52,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dcd103387644f86819cf37a2bbc92ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":65,
                  "y":212},
                "size":{
                  "width":52,
                  "height":63}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航/u9.png"}},
{
          "id":"1f2f486ec29a448fbbdaeab006341a4d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":464,
              "y":297},
            "size":{
              "width":48,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34266ad25ee841559961c5c3583a0aec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":464,
                  "y":297},
                "size":{
                  "width":48,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航/u11.png"}},
{
          "id":"350a7bd5d843412784fc7f2fc4ae174d",
          "label":"exit_navigate",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":67,
              "y":723},
            "size":{
              "width":75,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"041897f07d86487198c142f8e7c473b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":67,
                  "y":723},
                "size":{
                  "width":75,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show close_win,<br>confirm,<br>hint_win",
                      "objectsToFades":[{
                          "objectPath":["2fd45669e5cf482e916dd330271188f0"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["4713e227c4244a6db89a0ab13c007b0f"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["d487b578ecbb4307b20226dc1b81d3a1"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/导航/exit_navigate_u13.png"}},
{
          "id":"9527f6d921604a7ab205eb10bdbcbaf8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":89,
              "y":730},
            "size":{
              "width":29,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fab62a4c0a644e3830dc7c491ff23cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":89,
                  "y":730},
                "size":{
                  "width":29,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航/u15.png"}},
{
          "id":"ebea327530134e3abebff209c3179b0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":83,
              "y":765},
            "size":{
              "width":41,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a1ab7fbb71b479dace5b996ab89a7d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":83,
                  "y":765},
                "size":{
                  "width":41,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81ceeff9fcaf42f0b91ea17a79f01486",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "location":{
              "x":159,
              "y":723},
            "size":{
              "width":343,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"076c1ea59c574a59a2723ce8c73a71cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "location":{
                  "x":159,
                  "y":723},
                "size":{
                  "width":343,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航/u19.png"}},
{
          "id":"e820cb63f7594be1873d71d422672bb0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":617,
              "y":50},
            "size":{
              "width":441,
              "height":93}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41cf36a915374493a76efa23a8031f5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":617,
                  "y":50},
                "size":{
                  "width":441,
                  "height":93}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6fce79c1ebb944efb02c9bfec9c47bc9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":462,
              "y":327},
            "size":{
              "width":52,
              "height":123}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b9a5f41800e4d48af9665cd3093c77b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":462,
                  "y":327},
                "size":{
                  "width":52,
                  "height":123}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航/u23.png"}},
{
          "id":"13e040e41caa4189b5ec09533d5aa04d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":462,
              "y":443},
            "size":{
              "width":52,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c650d13322f74bd382e9a96122e9cdab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":462,
                  "y":443},
                "size":{
                  "width":52,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航/u25.png"}},
{
          "id":"d487b578ecbb4307b20226dc1b81d3a1",
          "label":"hint_win",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":89,
              "y":310},
            "size":{
              "width":391,
              "height":170},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24690055e91149d1b7af1e7ada4bbde1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":89,
                  "y":310},
                "size":{
                  "width":391,
                  "height":170},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航/hint_win_u27.png"}},
{
          "id":"2fd45669e5cf482e916dd330271188f0",
          "label":"close_win",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":450,
              "y":310},
            "size":{
              "width":30,
              "height":30},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc4cac8770c245918d9c775a998ba7e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":450,
                  "y":310},
                "size":{
                  "width":30,
                  "height":30},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Hide close_win,<br>confirm,<br>hint_win",
                      "objectsToFades":[{
                          "objectPath":["2fd45669e5cf482e916dd330271188f0"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["4713e227c4244a6db89a0ab13c007b0f"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["d487b578ecbb4307b20226dc1b81d3a1"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/导航/close_win_u29.png"}},
{
          "id":"4713e227c4244a6db89a0ab13c007b0f",
          "label":"confirm",
          "type":"button",
          "styleType":"button",
          "visible":false,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":370,
              "y":446},
            "size":{
              "width":100,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 导航模块 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"导航模块.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "93e305ef6c8e44b8be66bc02a45f786e":{
      "scriptId":"u0"},
    "43dab820de3f47b78ac591f6f6b74a57":{
      "scriptId":"u1"},
    "92c983e5f2d540829aaf5008a462bdb4":{
      "scriptId":"u2"},
    "6a396a54fa41438a8aebff505a92d6f1":{
      "scriptId":"u3"},
    "ef508baa6f92497dbb56e74d0a52f974":{
      "scriptId":"u4"},
    "c47ff4c8516f4509882d24740e53bbc4":{
      "scriptId":"u5"},
    "04b8ac6f90fa498bb09ed1af4ba6082e":{
      "scriptId":"u6"},
    "7374e759c55d4b798bd206176dcfaab0":{
      "scriptId":"u7"},
    "da0fe50a0c71445eb9d92c6099f25333":{
      "scriptId":"u8"},
    "75282385b49249c79fe0e6fe007b7c00":{
      "scriptId":"u9"},
    "4dcd103387644f86819cf37a2bbc92ac":{
      "scriptId":"u10"},
    "1f2f486ec29a448fbbdaeab006341a4d":{
      "scriptId":"u11"},
    "34266ad25ee841559961c5c3583a0aec":{
      "scriptId":"u12"},
    "350a7bd5d843412784fc7f2fc4ae174d":{
      "scriptId":"u13"},
    "041897f07d86487198c142f8e7c473b4":{
      "scriptId":"u14"},
    "9527f6d921604a7ab205eb10bdbcbaf8":{
      "scriptId":"u15"},
    "8fab62a4c0a644e3830dc7c491ff23cb":{
      "scriptId":"u16"},
    "ebea327530134e3abebff209c3179b0f":{
      "scriptId":"u17"},
    "5a1ab7fbb71b479dace5b996ab89a7d9":{
      "scriptId":"u18"},
    "81ceeff9fcaf42f0b91ea17a79f01486":{
      "scriptId":"u19"},
    "076c1ea59c574a59a2723ce8c73a71cc":{
      "scriptId":"u20"},
    "e820cb63f7594be1873d71d422672bb0":{
      "scriptId":"u21"},
    "41cf36a915374493a76efa23a8031f5e":{
      "scriptId":"u22"},
    "6fce79c1ebb944efb02c9bfec9c47bc9":{
      "scriptId":"u23"},
    "5b9a5f41800e4d48af9665cd3093c77b":{
      "scriptId":"u24"},
    "13e040e41caa4189b5ec09533d5aa04d":{
      "scriptId":"u25"},
    "c650d13322f74bd382e9a96122e9cdab":{
      "scriptId":"u26"},
    "d487b578ecbb4307b20226dc1b81d3a1":{
      "scriptId":"u27"},
    "24690055e91149d1b7af1e7ada4bbde1":{
      "scriptId":"u28"},
    "2fd45669e5cf482e916dd330271188f0":{
      "scriptId":"u29"},
    "fc4cac8770c245918d9c775a998ba7e6":{
      "scriptId":"u30"},
    "4713e227c4244a6db89a0ab13c007b0f":{
      "scriptId":"u31"}}});