$axure.loadCurrentPage({
  "url":"最近活动.html",
  "generationDate":new Date(1495872722601.51),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"text_keyword"],
  "page":{
    "packageId":"675598c66beb4f3fbbe1e7430adf0f15",
    "type":"Axure:Page",
    "name":"最近活动",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fff6b910086c4e56bbfae6c2c4a33a47",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":480,
              "height":800}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6a95d12a5ae43f0a54e53a57ba0a000",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":480,
                  "height":800}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/附近/u0.png"}},
{
          "id":"f82f667685ca4d708953d182383720ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "size":{
              "width":480,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"856ba601b09e42fabc9c9aad307a1eb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "size":{
                  "width":480,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/最近活动/u2.png"}},
{
          "id":"e2bcc696ce2f4d3f8fda0cd1d1629314",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":26},
            "size":{
              "width":45,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c4e53ed91c94b319775062c45ca1a79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":26},
                "size":{
                  "width":45,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/最近活动/u4.png"}},
{
          "id":"54cee79ecc7340c4baa683562a0990d5",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":90}},
          "adaptiveStyles":{
},
          "masterId":"6b4e68f4cd91462991c8cf928261803b"}]}},
  "masters":{
    "6b4e68f4cd91462991c8cf928261803b":{
      "packageId":"6b4e68f4cd91462991c8cf928261803b",
      "type":"Axure:Master",
      "name":"活动模板",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"e958381d21a147c3b5c46abb4f9bfd92",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":480,
                "height":136},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0752ff4d95364be9a10920545f2280d8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":480,
                    "height":136},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/最近活动/u7.png"}},
{
            "id":"b48d2589f7ff4eca9ed1dcc3edd3d4b5",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":18,
                "y":16},
              "size":{
                "width":127,
                "height":102}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d50c85756617480c91cbf40f69e1eaf3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":18,
                    "y":16},
                  "size":{
                    "width":127,
                    "height":102}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/最近活动/u9.png"}},
{
            "id":"5574711cb1c84aec9b52c8c5d627728d",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "location":{
                "x":154,
                "y":16},
              "size":{
                "width":88,
                "height":37}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6fccd6f7be424ec2805af890d0524b0c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":154,
                    "y":16},
                  "size":{
                    "width":88,
                    "height":37}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"dd5bcbd6b9b34075830c8ef47f60f216",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":246,
                "y":26},
              "size":{
                "width":35,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4c153e29d9724c6ebd538888dee288a0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":246,
                    "y":26},
                  "size":{
                    "width":35,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"a70360c8639d4e3aaf3742a9b7a8b257",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":155,
                "y":62},
              "size":{
                "width":307,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b182ab3a53b343bfaaab2095b016de21",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":155,
                    "y":62},
                  "size":{
                    "width":307,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7c5f53d6d9f54b23994adf61abec354f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":154,
                "y":88},
              "size":{
                "width":199,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"12ac4a7d40d54b43abe8dc72255a53bb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":154,
                    "y":88},
                  "size":{
                    "width":199,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "fff6b910086c4e56bbfae6c2c4a33a47":{
      "scriptId":"u0"},
    "c6a95d12a5ae43f0a54e53a57ba0a000":{
      "scriptId":"u1"},
    "f82f667685ca4d708953d182383720ba":{
      "scriptId":"u2"},
    "856ba601b09e42fabc9c9aad307a1eb0":{
      "scriptId":"u3"},
    "e2bcc696ce2f4d3f8fda0cd1d1629314":{
      "scriptId":"u4"},
    "4c4e53ed91c94b319775062c45ca1a79":{
      "scriptId":"u5"},
    "54cee79ecc7340c4baa683562a0990d5":{
      "scriptId":"u6",
      "e958381d21a147c3b5c46abb4f9bfd92":{
        "scriptId":"u7"},
      "0752ff4d95364be9a10920545f2280d8":{
        "scriptId":"u8"},
      "b48d2589f7ff4eca9ed1dcc3edd3d4b5":{
        "scriptId":"u9"},
      "d50c85756617480c91cbf40f69e1eaf3":{
        "scriptId":"u10"},
      "5574711cb1c84aec9b52c8c5d627728d":{
        "scriptId":"u11"},
      "6fccd6f7be424ec2805af890d0524b0c":{
        "scriptId":"u12"},
      "dd5bcbd6b9b34075830c8ef47f60f216":{
        "scriptId":"u13"},
      "4c153e29d9724c6ebd538888dee288a0":{
        "scriptId":"u14"},
      "a70360c8639d4e3aaf3742a9b7a8b257":{
        "scriptId":"u15"},
      "b182ab3a53b343bfaaab2095b016de21":{
        "scriptId":"u16"},
      "7c5f53d6d9f54b23994adf61abec354f":{
        "scriptId":"u17"},
      "12ac4a7d40d54b43abe8dc72255a53bb":{
        "scriptId":"u18"}}}});